### ISSUE TITLE
descrypt-opencl "OpenCL CL_OUT_OF_RESOURCES error in opencl_DES_bs_plug.c:549" after 1+ hour

### ISSUE THREAD

**Issue by aguvillalba** [openwall/john#2653] opened 2017-08-05 14:48 UTC
After more than 1 hour running john, I got this error:

command:
`./john --format=descrypt-opencl --min-length=8 --progress-every=10 --device=0 --encoding=Latin1 --verbosity=4 ~/jonny.txt`
Output:
```
80g 0:01:39:55  3/3 0.01334g/s 134998p/s 180359Kc/s 235116KC/s GPU:77°C 2slangki..2slangki
80g 0:01:40:05  3/3 0.01332g/s 134773p/s 180461Kc/s 235250KC/s GPU:76°C 2slangki..2slangki
80g 0:01:40:15  3/3 0.01329g/s 134549p/s 180562Kc/s 235282KC/s GPU:77°C 2slangki..2slangki
80g 0:01:40:25  3/3 0.01327g/s 134325p/s 180664Kc/s 235360KC/s GPU:77°C 2slangki..2slangki
OpenCL CL_OUT_OF_RESOURCES error in opencl_DES_bs_plug.c:549 - Failed to read buffer buffer_hash_ids.
```
Build info:
```
Version: 1.8.0-jumbo-1-5774-g8d7ccaf
Build: linux-gnu 64-bit SSE4.1-ac MPI + OMP
SIMD: SSE4.1, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 5.4.0
GNU libc version: 2.23 (loaded: 2.23)
OpenCL headers version: 2.0
Crypto library: OpenSSL
OpenSSL library version: 01000207f
OpenSSL 1.0.2g  1 Mar 2016
GMP library version: 6.1.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by aguvillalba** [comment] 2017-08-05 14:55
GPU info:
```
./john --list=opencl-devices
Platform #0 name: NVIDIA CUDA, version: OpenCL 1.2 CUDA 8.0.0
    Device #0 (0) name:     GeForce GTX 970
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 CUDA
    Driver version:         375.66 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          3.0 GB
    Global Memory Cache:    208.2 KB
    Local Memory:           48.0 KB (Local)
    Max memory alloc. size: 1008.10 MB
    Max clock (MHz):        1304
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 13
    CUDA cores:             1664  (13 x 128)
    Speed index:            2169856
    Warp size:              32
    Max. GPRs/work-group:   65536
    Compute capability:     5.2 (sm_52)
    Kernel exec. timeout:   yes
    NVML id:                0
    PCI device topology:    03:00.0
    PCI lanes:              16/16
    Fan speed:              36%
    Temperature:            43°C
    Utilization:            18%
```

**Comment by solardiz** [comment] 2017-08-05 14:58
Please `--restore` this session and watch GPU memory usage in `nvidia-smi` output as the session runs - does the memory usage keep increasing? Until what level? Perhaps the code is leaking a certain resource, which could be GPU global memory or/and something else. Thanks.

**Comment by aguvillalba** [comment] 2017-08-05 15:00
If I try to run it with --restore I got this:

```
./john --format=descrypt-opencl --min-length=8 --progress-every=10 --device=0 --encoding=Latin1 --restore ~/jonny.txt 
Invalid options combination or duplicate option: "--min-length=8"
```
I don't get it

**Comment by solardiz** [comment] 2017-08-05 15:03
`--restore` should be the only option, you don't need to and must not re-list the old options explicitly. Not even the password hash file's name.

**Comment by aguvillalba** [comment] 2017-08-05 15:14
Ok, running again with --restore.

output of nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 0000:03:00.0      On |                  N/A |
| 55%   68C    P2   112W / 180W |   2097MiB /  4032MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1303    G   /usr/lib/xorg/Xorg                             276MiB |
|    0      4049    G   compiz                                         113MiB |
|    0      5941    G   ...el-token=0CA92C2FFFDE554AA2EB15EE46854624    92MiB |
|    0     10542    C   ./john                                        1610MiB |
+-----------------------------------------------------------------------------+
```
This is after 10 min running. I'll keep reporting.
Thanks for your help and good job with this software!

**Comment by aguvillalba** [comment] 2017-08-05 16:21
After 01:25 hr, this is the output of nvidia-smi:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 0000:03:00.0      On |                  N/A |
| 69%   76C    P2   115W / 180W |   2111MiB /  4032MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1303    G   /usr/lib/xorg/Xorg                             276MiB |
|    0      4049    G   compiz                                         113MiB |
|    0      5941    G   ...el-token=0CA92C2FFFDE554AA2EB15EE46854624   104MiB |
|    0     10719    C   ./john                                        1612MiB |
+-----------------------------------------------------------------------------+
```

**Comment by aguvillalba** [comment] 2017-08-05 16:47
After 01:50 hr, this is the output of nvidia-smi:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 0000:03:00.0      On |                  N/A |
| 69%   77C    P2   117W / 180W |   2112MiB /  4032MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1303    G   /usr/lib/xorg/Xorg                             276MiB |
|    0      4049    G   compiz                                         113MiB |
|    0      5941    G   ...el-token=0CA92C2FFFDE554AA2EB15EE46854624   104MiB |
|    0     10719    C   ./john                                        1612MiB |
+-----------------------------------------------------------------------------+
```

But only 6 guesses so far:
```
6g 0:01:51:06  3/3 0.000900g/s 141537p/s 185409Kc/s 237855KC/s GPU:76°C rbsmduki..rbsmduki
6g 0:01:51:15  3/3 0.000898g/s 141346p/s 185510Kc/s 237946KC/s GPU:77°C rbsmduki..rbsmduki
6g 0:01:51:25  3/3 0.000897g/s 141134p/s 185584Kc/s 237972KC/s GPU:77°C rbsmduki..rbsmduki
6g 0:01:51:36  3/3 0.000896g/s 140902p/s 185640Kc/s 239074KC/s GPU:77°C rbsmduki..rbsmduki

```

**Comment by solardiz** [comment] 2017-08-05 16:53
"Only 6 guesses" means you didn't actually restore the old session, which had cracked 80 - perhaps before you properly ran with `--restore`, you somehow overwrote the .rec file (e.g., ran some other attack from scratch). So you almost lost the first 1:40 hours of work, in terms of not having a record of what candidate passwords were already tested, and you redid this work now. That's why it's achieved so few new guesses so far - it had to reach the previous session's point first (with proper `--restore`, it wouldn't have to - it'd restart right there).

**Comment by solardiz** [comment] 2017-08-05 16:57
Since you're also using this same GPU for your desktop, could the "out of resources" error be caused by a spike in GPU resource usage by your desktop apps, rather than any bug in JtR?

**Comment by aguvillalba** [comment] 2017-08-05 22:47
Again the failure after 5hrs running:

```
47g 0:05:08:26  3/3 0.002539g/s 174277p/s 220687Kc/s 283014KC/s GPU:77°C kaeky321..kaeky321
47g 0:05:08:35  3/3 0.002538g/s 174193p/s 220710Kc/s 283036KC/s GPU:77°C kaeky321..kaeky321
47g 0:05:08:45  3/3 0.002537g/s 174099p/s 220721Kc/s 283025KC/s GPU:77°C kaeky321..kaeky321
47g 0:05:08:55  3/3 0.002535g/s 174005p/s 220732Kc/s 283021KC/s GPU:77°C kaeky321..kaeky321
OpenCL CL_OUT_OF_RESOURCES error in opencl_DES_bs_plug.c:549 - Failed to read buffer buffer_hash_ids.
```
JtR is the only application running in the in the computer, so I doubt that the failure is caused by something else than JtR.

**Comment by aguvillalba** [comment] 2017-08-05 22:57
@solardiz, you are right, before I overwrote the .rec file by running the same command with the --restore flag.
Now I did it correctly and it started from the last point where it crashed (47g).

Thanks for the advise!

**Comment by aguvillalba** [comment] 2017-08-06 09:37
Again, after 2 more hours of execution:

```
71g 0:07:13:30  3/3 0.002729g/s 178180p/s 223419Kc/s 286363KC/s GPU:77°C lythnoe2..lythnoe2
71g 0:07:13:40  3/3 0.002728g/s 178111p/s 223426Kc/s 286376KC/s GPU:77°C lythnoe2..lythnoe2
71g 0:07:13:50  3/3 0.002727g/s 178043p/s 223436Kc/s 286382KC/s GPU:77°C lythnoe2..lythnoe2
71g 0:07:14:00  3/3 0.002726g/s 177975p/s 223445Kc/s 286376KC/s GPU:77°C lythnoe2..lythnoe2
71g 0:07:14:10  3/3 0.002725g/s 177906p/s 223455Kc/s 286374KC/s GPU:76°C lythnoe2..lythnoe2
OpenCL CL_OUT_OF_RESOURCES error in opencl_DES_bs_plug.c:549 - Failed to read buffer buffer_hash_ids.
```

**Comment by solardiz** [comment] 2017-08-06 12:01
@aguvillalba "before I overwrote the .rec file by running the same command with the --restore flag." - no, it wouldn't (or at least shouldn't) have overwritten the file. When JtR complains about incompatible combination of options, it exits before writing any files. Perhaps you also ran some other command at the time, such as the same command without `--restore` at all.

As to the "out of resources" errors every few hours, the cause is still unclear. Notice how the durations and the numbers of guesses (until hitting the error again) both vary. This suggests that either the cause of the error is external (some of your desktop apps making greater use of the GPU for a moment), or it is internal but intermittent - e.g., it could be a race condition. To try and debug this, please run this command along with JtR:

    while :; do uptime; nvidia-smi; sleep 10; done | tee -a log

Then post in here an excerpt from the log file from the time around the error (starting shortly before the error and ending after the error).  Thanks!

**Comment by solardiz** [comment] 2017-08-07 12:46
I suspect that fixing #2613 could help mitigate the "out of resources" issue through not wasting GPU memory on unnecessarily large hash tables. That issue isn't a leak, so not directly what we see here, but fixing it may reduce the initial GPU memory usage, and thus make it less likely that we'll attempt to exceed what's available for allocation later.

**Comment by solardiz** [comment] 2017-08-14 16:34
@aguvillalba Any status update? Meanwhile, to reduce your GPU memory usage from 1.6 GB to perhaps 500 MB, try prefixing your "./john ..." commands with "GWS=524288 ", like this:

    GWS=524288 ./john ...

Does this possibly help avoid the out of resources errors?

(This advice is only valid for descrypt-opencl. Other formats may need different GWS settings, and you have no reason to alter their defaults yet.)

**Comment by magnumripper** [comment] 2017-08-15 08:46
It seems to me the (format specific) auto-tune code doesn't take number of salts in account. This may be one reason (of several) the margin gets too small.

opencl_DES_bs_[bh]_plug.c:
```c
	size_t gws_limit = get_max_mem_alloc_size(gpu_id) / (sizeof(opencl_DES_bs_transfer) * iter_count) ;
```

**Comment by solardiz** [comment] 2017-08-15 12:03
I think the salt count shouldn't affect the tuned GWS here. So that's fine. Per my testing, there's almost no difference in GPU memory usage when running descrypt-opencl against 1 or 2000+ salts - it's around 1.6 GB with auto-tuned GWS either way.

**Comment by solardiz** [comment] 2024-06-09 15:47
This was a discussion in 2017 where OP stopped commenting after a while. I'll close this issue now, but we can revisit if the same problem gets reported again.

**Closed by solardiz** 2024-06-09 15:47 UTC
Labels: bug
