### ISSUE TITLE
zip2john doesn't produce a crackable hash when zip was created with bsdtar 

### ISSUE THREAD

**Issue by mb720** [openwall/john#4541] opened 2021-01-06 17:05 UTC
Hi and thanks a lot for JtR!

I think that zip2john doesn't work when the zip file was created with bsdtar:

    bsdtar --options zip:encryption -acf with_bsdtar.zip test_file

Here's the example [`with_bsdtar.zip`](https://github.com/openwall/john/files/5777014/with_bsdtar.zip), the password is "test".

The output of `zip2john with_bsdtar.zip`:

    ver 2.0 efh 5455 efh 7875 with_bsdtar.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=0, decmplen=6, crc=0
    with_bsdtar.zip/test_file:$pkzip2$1*2*2*0*0*6*0*0*47*8*0*0000*8cd0**$/pkzip2$:test_file:with_bsdtar.zip::with_bsdtar.zip

On the other hand, things work fine when using a zip file created with

    zip --encrypt with_zip.zip test_file

where `zip2john with_zip.zip` yields

    ver 1.0 efh 5455 efh 7875 with_zip.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=18, decmplen=6, crc=775F54D8
    with_zip.zip/test_file:$pkzip2$1*2*2*0*12*6*775f54d8*0*43*0*12*775f*8cd0*a5ad914fcad388ac41ecf2a97498c2315730*$/pkzip2$:test_file:with_zip.zip::with_zip.zip

Here's [`with_zip.zip`](https://github.com/openwall/john/files/5777077/with_zip.zip).

The archive `with_bsdtar.zip` seems to be valid, since I can `unzip with_bsdtar.zip` successfully.

### System configuration ###
I'm on Arch Linux 5.9.14.

Output of `john --list=build-info`:

    Version: 1.9.0-jumbo-1
    Build: linux-gnu 64-bit x86_64 AVX AC MPI + OMP
    SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
    System-wide exec: /usr/lib/john
    System-wide home: /usr/share/john
    Private home: ~/.john
    CPU tests: AVX
    CPU fallback binary: john-non-avx
    $JOHN is /usr/share/john/
    Format interface version: 14
    Max. number of reported tunable costs: 4
    Rec file version: REC4
    Charset file version: CHR3
    CHARSET_MIN: 1 (0x01)
    CHARSET_MAX: 255 (0xff)
    CHARSET_LENGTH: 24
    SALT_HASH_SIZE: 1048576
    SINGLE_IDX_MAX: 2147483648
    SINGLE_BUF_MAX: 4294967295
    Effective limit: Number of salts vs. SingleMaxBufferSize
    Max. Markov mode level: 400
    Max. Markov mode password length: 30
    gcc version: 10.2.0
    GNU libc version: 2.32 (loaded: 2.32)
    OpenCL headers version: 2.2
    Crypto library: OpenSSL
    OpenSSL library version: 01010108f	(loaded: 01010109f)
    OpenSSL 1.1.1h  22 Sep 2020	(loaded: OpenSSL 1.1.1i  8 Dec 2020)
    GMP library version: 6.2.0	(loaded: 6.2.1)
    File locking: fcntl()
    fseek(): fseek
    ftell(): ftell
    fopen(): fopen
    memmem(): System's

**Comment by ghost** [comment] 2021-01-06 17:44
bleeding-jumbo version does produce a hash john recognizes. But it is not crackable.
```
$ /snap/john-the-ripper/current/run/zip2john with_bsdtar.zip
ver 2.0 efh 5455 efh 7875 with_bsdtar.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=20, decmplen=6, crc=775F54D8 type=8
with_bsdtar.zip/test_file:$pkzip2$1*2*2*0*14*6*775f54d8*0*47*8*14*775f*8cd0*11b75efed56a5795f07c509268a88b4a6ff362ef*$/pkzip2$:test_file:with_bsdtar.zip::with_bsdtar.zip
```

Unzip can handle the file:
```
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
$ unzip with_bsdtar.zip 
Archive:  with_bsdtar.zip
[with_bsdtar.zip] test_file password: 
  inflating: test_file       
```

**Comment by magnumripper** [comment] 2021-01-09 16:06
So we get false negatives? This will be very high on my to-do list unless someone else takes a stab on it (I'll assign it to myself only once I'm just about to look at it)

**Comment by magnumripper** [comment] 2021-02-03 12:55
Seems to be similar to #4300: If I change `$pkzip2$1*2*2*(...)` to `$pkzip2$1*1*2*(...)` (stating that only one byte of checksum is valid), it works fine.

**Comment by magnumripper** [comment] 2021-02-03 13:06
@jfoug Perhaps we need a whitelist for 2-byte checksums as opposed to a blacklist?

This file is "ver 2.0 efh 5455 efh 7875"

Edit: No wait, we are currently using a whitelist *and* a blacklist (for efh 6c78). In this case I can't see what to blacklist 😢

**Comment by magnumripper** [comment] 2021-02-03 13:32
I currently can't find any safe way to fix this except disabling 2-byte checksums, with a 10% performance loss.

**Comment by magnumripper** [comment] 2021-02-04 14:58
> I currently can't find any safe way to fix this except disabling 2-byte checksums, with a 10% performance loss.

So I did just that - by default. There was an existing option `-2` for *forcing* 2-byte checksums that in my mind was an experimental option irrelevant for an end user. I now changed its meaning to *allow* 2-byte checksums, which will impose the (fairly low) risk of false negatives. Using that will still end up with 1-byte checksum for #4300 now, bc we do have something to blacklist in that case, but it would again produce an uncrackable 2-byte cs hash for `with_bsdtar.zip` if used.

**Comment by solardiz** [comment] 2021-02-05 09:55
So `bsdtar` has `efh 7875`, which we had whitelisted for 2-byte checksum, but along with `cmplen=0` and `crc=0`:

```
ver 2.0 efh 5455 efh 7875 with_bsdtar.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=0, decmplen=6, crc=0
```

whereas `zip` has the same along with `cmplen=18` and non-zero `crc`:

```
ver 1.0 efh 5455 efh 7875 with_zip.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=18, decmplen=6, crc=775F54D8
```

I think this is sufficient for us to distinguish the two, and add an exclusion from the whitelist when (one of) those other conditions are (is) met.

**Comment by solardiz** [comment] 2021-02-05 10:08
> So `bsdtar` has `efh 7875`, which we had whitelisted for 2-byte checksum, but along with `cmplen=0` and `crc=0`

BTW, that's weird on its own. Why would they be zero? And why would that archive work correctly then? Per `zipinfo`, they are not actually zero:

```
  32-bit CRC value (hex):                         775f54d8
  compressed size:                                20 bytes
```

So something else went wrong there with parsing by `zip2john`. And maybe that's also why the archive couldn't be cracked when using 2-byte checksum? Maybe 2-byte would work against CRC, but doesn't work against TS? If so, fixing whatever bug caused the CRC to appear as zero would also fix this issue.

**Comment by solardiz** [comment] 2021-02-05 10:17
That line I quoted came from @mb720's original comment:

```
ver 2.0 efh 5455 efh 7875 with_bsdtar.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=0, decmplen=6, crc=0
```

However, @claudioandre-br's is different:

```
ver 2.0 efh 5455 efh 7875 with_bsdtar.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=20, decmplen=6, crc=775F54D8 type=8
```

So apparently different `zip2john` versions? Anyway, Claudio wrote the hash produced by his `zip2john` run above "is not crackable." If so, this disproves the guess from my previous comment. Unfortunately.

**Comment by solardiz** [comment] 2021-02-05 10:19
@mb720 Please send us a pull request against https://github.com/openwall/john-samples adding both of your sample archives, so that we can retest for possible regressions later. Thanks!

**Comment by mb720** [comment] 2021-02-05 14:43
@solardiz: Sure thing, [here](https://github.com/openwall/john-samples/pull/5)'s the PR.

Thanks for looking into this. 👍

**Closed as completed** 2021-02-07 19:37 UTC
Labels: bug

**Comment by magnumripper** [comment] 2021-02-08 16:26
Quotes from #4561:
> OK, I see that the issue we're trying to fix is `0x7875` doesn't guarantee 2-byte checksum.
> 
> I think we should add a comment that unfortunately checksum size seen with that EFH value varies between the two known archivers that use that value.

> So the main question is whether we want to hurt the speed at all other previously-whitelisted EFH values just because we found this problem for `0x7875` now. I doubt we want to do that, or at least we should have `zip2john` recommend use of `-2` for those. In fact, it could print a more verbose recommendation even for `0x7875`, mentioning the `bsdtar` issue.

Not sure why you single out 0x7875, 0x5455 is just as uncertain now. Either of them (actually the pair of them) are seen with 2-byte checksums, but now also sometimes with one-byte checksums.

So OK, we could have opted to drop only those two from the whitelist - but with this recent history, what's to say the other ones are actually safe? I intend to try to dig further into this but until then I think merging #4561 was the right thing to do.

**Comment by mb720** [comment] 2022-12-31 12:58
Does cracking the [zip file created with bsdtar](https://github.com/mb720/john-samples/blob/e919c0a976ff2e5a81b59352ee3377564693e4f3/ZIP/bsdtar_test%23.zip) work on your end?

I just tried again on Arch Linux with John the Ripper 1.9.0 jumbo and the zip2john version that comes with that. It says "No password hashes loaded (see FAQ)".

The file created with zip could be cracked just fine.

**Comment by ghost** [comment] 2022-12-31 15:12
> Does cracking the [zip file created with bsdtar](https://github.com/mb720/john-samples/blob/e919c0a976ff2e5a81b59352ee3377564693e4f3/ZIP/bsdtar_test%23.zip) work on your end?

Yes, it does.

> I just tried again on Arch Linux with John the Ripper 1.9.0 jumbo

Zip format saw a huge evolution after Jumbo 1 release. 

**Everyone who works with zip files should use the bleeding john from this repository (or a rolling version).**

```
$ john-the-ripper.zip2john bsdtar_test#.zip > hash.txt
ver 2.0 efh 5455 efh 7875 bsdtar_test#.zip/test_file PKZIP Encr: TS_chk, cmplen=20, decmplen=6, crc=775F54D8 ts=8CD0 cs=8cd0 type=8
```

```
$ john hash.txt 
Using default input encoding: UTF-8
Loaded 1 password hash (PKZIP [32/64])
Will run 8 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
test             (bsdtar_test#.zip/test_file)     
1g 0:00:00:00 DONE 1/3 (2022-12-31 12:06) 2.941g/s 70.58p/s 70.58c/s 70.58C/s bsdtarfile..testzip
Use the "--show" option to display all of the cracked passwords reliably
Session completed. 

```

```
$ cat hash.txt 
bsdtar_test#.zip/test_file:$pkzip$1*1*2*0*14*6*775f54d8*0*47*8*14*8cd0*11b75efed56a5795f07c509268a88b4a6ff362ef*$/pkzip$:test_file:bsdtar_test#.zip::bsdtar_test#.zip

```

**Comment by mb720** [comment] 2023-01-01 19:01
To be more precise, my version of john, according to `pacman -Qi john`, is 1.9.0.jumbo1-8.

I can see that my zip2john behaves differently compared to your version:

    $ zip2john bsdtar_test#.zip > hash.txt
    ver 2.0 efh 5455 efh 7875 bsdtar_test#.zip/test_file PKZIP Encr: 2b chk, TS_chk, cmplen=0, decmplen=6, crc=0

    $ cat hash.txt
    bsdtar_test#.zip/test_file:$pkzip2$1*2*2*0*0*6*0*0*47*8*0*0000*8cd0**$/pkzip2$:test_file:bsdtar_test#.zip::bsdtar_test#.zip

    $ which zip2john
    /usr/bin/zip2john
