### ISSUE TITLE
OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1386 - clBuildProgram

### ISSUE THREAD

**Issue by JeremyLing04** [openwall/john#5375] opened 2023-11-12 04:43 UTC
Error Description:
I tried to use my Nvidia RTX 2050 GPU to speed up encrypted word doc cracking but failed. Here is the command I performed and the error messages:
```
john --rules --wordlist=C:\Users\User\Documents\wordlist.txt --device=1 --format=office-opencl C:\Users\User\Documents\hash.txt
Device 1: NVIDIA GeForce RTX 2050
Using default input encoding: UTF-8
Loaded 1 password hash (office-opencl, MS Office [SHA1/SHA512 AES OpenCL])
Cost 1 (MS Office version) is 2013 for all loaded hashes
Cost 2 (iteration count) is 100000 for all loaded hashes
2 errors generated.
Options used: -I kernels -cl-mad-enable -DSM_MAJOR=8 -DSM_MINOR=6 -D__GPU__ -DDEVICE_INFO=18 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=546 -DDEV_VER_MINOR=1 -D_OPENCL_COMPILER -DHASH_LOOPS0710=500 -DHASH_LOOPS13=100 -DUNICODE_LENGTH=96 kernels/office_kernel.cl
Build log: <kernel>:224:22: error: passing 'const __generic uchar *' (aka 'const __generic unsigned char *') to parameter of type 'const void *' changes address space of pointer
        AES_set_decrypt_key(verifierInputKey, salt->keySize, &akey);
                            ^~~~~~~~~~~~~~~~
kernels/opencl_aes_bitslice.h:1002:61: note: expanded from macro 'AES_set_decrypt_key'
#define AES_set_decrypt_key(key, bits, ctx) AES_Setkey(ctx, key, (bits) / 8)
                                                            ^~~
kernels/opencl_aes_bitslice.h:690:45: note: passing argument to parameter 'key' here
AES_Setkey(AES_CTX *ctx, AES_KEY_TYPE void *key, int len)
                                            ^
<kernel>:225:37: error: passing '__generic uchar *' (aka '__generic unsigned char *') to parameter of type 'void *' changes address space of pointer
        AES_cbc_decrypt(encryptedVerifier, decryptedVerifier, length, &akey, iv);
                                           ^~~~~~~~~~~~~~~~~
kernels\opencl_aes.h:159:60: note: passing argument to parameter '_out' here
AES_cbc_decrypt(AES_SRC_TYPE void *_in, AES_DST_TYPE void *_out,
                                                           ^

Error building kernel kernels/office_kernel.cl. DEVICE_INFO=18
0: OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1386 - clBuildProgram
```

System Configuration:
`john --list=build-info`

Version: 1.9.0-jumbo-1
Build: cygwin 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010102f
OpenSSL 1.1.1b  26 Feb 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

`john --list=opencl-devices`

Platform #0 name: NVIDIA CUDA, version: OpenCL 3.0 CUDA 12.3.99
    Device #0 (1) name:     NVIDIA GeForce RTX 2050
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 3.0 CUDA
    Driver version:         546.01 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          4095 MB
    Global Memory Cache:    448 KB
    Local Memory:           48 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 1023 MB
    Max clock (MHz):        1575
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 16
    CUDA cores:             1024  (16 x 64)
    Speed index:            1612800
    Warp size:              32
    Max. GPRs/work-group:   65536
    Compute capability:     8.6 (sm_86)
    Kernel exec. timeout:   yes
    PCI device topology:    01:00.0
    
Please help me to solve this problem.

**Comment by solardiz** [comment] 2023-11-13 23:29
Hi @JeremyLing04, we've probably already fixed this issue, please try with our latest Windows build available from here: https://github.com/openwall/john-packages/releases/tag/jumbo-dev (also linked from the "Download Windows Build" badge in the README.md in this repo). Please let us know of your results.

Unfortunately, the 1.9.0-jumbo-1 release that you reported this issue against is rather old, and in general we expect GitHub issues to be used for latest code that we actually have here on GitHub. Thank you!

**Comment by solardiz** [comment] 2023-11-13 23:33
This is a duplicate of #5205, #5222 (where a comment also includes a workaround), #5319.

**Closed as completed** 2023-11-19 19:26 UTC
Labels: dupe, question
