### ISSUE TITLE
PUP-gen virus in Homebrew formula!

### ISSUE THREAD

**Issue by rodened** [openwall/john#4840] opened 2021-10-07 17:07 UTC
My antivirus put a file in quarantine when I installed john-jumbo with brew.

Just so you know and can act on it!

**Comment by solardiz** [comment] 2021-10-07 18:37
@rodened Thank you for letting us know, but I see no good way how we could act on it. Do you?

In context of so-called "anti-viruses", PUP stands for "potentially unwanted program". If you don't want your AV product to consider JtR "potentially unwanted", then please ask its developers to remove this detection. We'd appreciate that. Thank you!

For similar issues happening on Windows (and more frequently so) for past versions of JtR, we (conditionally) displayed a note on the JtR homepage (saying similar to what I write in the paragraph above). This is currently disabled, because the complaints aren't frequent enough (hopefully meaning the problem isn't as severe, maybe temporarily). Since yours is the first such report for macOS, this probably doesn't justify a note on the website (and that wouldn't be seen by someone installing with `brew` anyway).

Maybe maintainers of the Homebrew package of `john-jumbo` could include a note explaining the issue (and how to get around it) if it's in fact common enough. Please feel free to suggest this to them. Here, we are upstream maintainers, and don't work on that package directly.

Another thing we could do is make releases more frequently and have code change sufficiently that detection of past versions would hopefully not trigger on the new versions until someone adds them. However, fighting the AV windmills on purpose isn't something we should be doing, I think.

If someone thinks what we make is PUP, it probably is so for some of their users. At least they don't claim "virus". Maybe users of such AV products can request even clearer labeling than PUP - e.g., spelled out "potentially-unwanted". Would you?

Makes sense?

**Comment by solardiz** [comment] 2021-10-07 18:46
@rodened Oh, and what antivirus is that? What is it called, and is it running directly on your Mac or on some network node you're downloading files through? This knowledge would help us in case of further reports like yours. Thanks!

**Comment by solardiz** [comment] 2021-10-12 15:29
I'll close this issue since it is not actionable for us, but we'd appreciate a further comment by @rodened letting us know what antivirus that was and whether it was local on the Mac or somewhere on the network.

**Closed as completed by solardiz** 2021-10-12 15:29 UTC
Labels: notes/external issues
