### ISSUE TITLE
Error installing in windows

### ISSUE THREAD

**Issue by jmaravi** [openwall/john#4037] opened 2019-06-26 05:25 UTC
Trying to install in windows:
PC@DESKTOP-AU03JV2 /cygdrive/c/JohnTheRipper-bleeding-jumbo/JohnTheRipper-bleeding-jumbo/src
$ ./configure && make -s clean && make -sj4
checking build system type... x86_64-unknown-cygwin
checking host system type... x86_64-unknown-cygwin
checking whether to compile using MPI... no
checking for gcc... gcc[...]
Everything goes well, until it hits:
config.status: executing default commands
configure: creating ./fmt_externs.h
-fThe system cannot find the file specified.
configure: error: The build of fmt_externs.h failed. Can not continue!
Input record exceeds maximum length.  Specify larger maximum.

### Steps to reproduce ###
windows 10 and cygwin intalled

### System configuration ###
None since john was not installed

**Comment by solardiz** [comment] 2019-06-26 09:48
Looks like this build attempt tried to use the Windows-provided `sort` command instead of the Cygwin-provided one. We rely on the latter. Any idea why that happened, @jmaravi? Were you running this command from the Cygwin shell?

**Comment by solardiz** [comment] 2019-06-26 09:53
Analysis of what happened, except that we don't know _why_ Windows `sort` got invoked:

`-fThe system cannot find the file specified.` comes from our use of the `-f` option in `LC_ALL=C $SORT -f`. We want the formats sorted alphabetically ignoring case. This affects the order in which JtR lists the formats with `--test`, etc. Apparently, Windows `sort` doesn't support that option.

`Input record exceeds maximum length. Specify larger maximum.` is also a Windows `sort` message. However, I am more puzzled by this one. We shouldn't have any long lines in our input to `sort`. My best guess is Windows `sort` is confused by Unix linefeeds, treating its entire input as one line.

**Comment by jmaravi** [comment] 2019-06-26 13:01
@solardiz 
yes running this in side cygwin: look at the  prompt PC@DESKTOP-AU03JV2 /cygdrive/c/JohnTheRipper-bleeding-jumbo/JohnTheRipper-bleeding-jumbo/src, then:
$ ./configure && make -s clean && make -sj4

How do i fix it?

**Comment by solardiz** [comment] 2019-06-26 13:27
> How do i fix it?

Since we don't know what causes Windows `sort` to be used on your system whereas Cygwin `sort` is used on others' systems, we also don't know how to fix this. It would help if you somehow investigated this. For example, what do these commands say? -

```
which sort
type sort
```

Also, why did you choose to build from source rather than use the 1.9.0-jumbo-1 binaries for Windows that we've released? This is fine, and we appreciate your helping the project by testing our latest code and reporting this problem, but maybe your answer to this question would be helpful as well.

In general, our use of GitHub issues is for problems with code and fixing those for all users, rather than for providing user support. So if your goal is to help the project, then you're doing what's right - thank you! If your goal is to get JtR working for yourself, then using the pre-built binaries is the easiest.

**Comment by jmaravi** [comment] 2019-06-26 13:46
@solardiz ok, i fix that part.. now I am getting this in the very last part it looks like is this part:"make -sj4"
configure: creating ./fmt_externs.h
configure: creating ./fmt_registers.h

Configured for building John the Ripper jumbo:

Target CPU ................................. x86_64 AVX, 64-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-64.h

Optional libraries/features found:
Memory map (share/page large files) ........ yes
Fork support ............................... yes
OpenMP support ............................. yes (not for fast formats)
OpenCL support ............................. yes
Generic crypt(3) format .................... yes
libgmp (PRINCE mode and faster SRP formats)  yes
128-bit integer (faster PRINCE mode) ....... yes
libz (pkzip and some other formats) ........ yes
libbz2 (gpg2john extra decompression logic)  yes
libpcap (vncpcap2john and SIPdump) ......... no
OpenMPI support (default disabled) ......... no
ZTEX USB-FPGA module 1.15y support ......... no

Install missing libraries to get any needed features that were omitted.

Configure finished.  Now "make -s clean && make -sj4" to compile.
cp: missing destination file operand after '../run/kernels'
Try 'cp --help' for more information.
cp: missing destination file operand after '../run/kernels'
Try 'cp --help' for more information.
make[1]: *** [Makefile:229: ../run/kernels/7z_kernel.cl] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:229: ../run/kernels/DES_bs_finalize_keys_kernel.cl] Error 1
cp: missing destination file operand after '../run/kernels'
Try 'cp --help' for more information.
make[1]: *** [Makefile:229: ../run/kernels/DES_bs_hash_checking_kernel.cl] Error 1
make: *** [Makefile:189: default] Error 2

**Comment by jmaravi** [comment] 2019-06-26 13:49
@solardiz  where is the 1.9.0-jumbo-1 binaries for Windows you guys released?

**Comment by solardiz** [comment] 2019-06-26 16:14
> ok, i fix that part..

How did you fix it?

I don't know why you're also running into issues with the `cp` commands. The root cause might be the same as you had for `sort`.

**Comment by jmaravi** [comment] 2019-06-26 16:30
I started an instance of cygwin from the desktop shortcut... if you see the error:
cp: missing destination file operand after '../run/kernels' -> it is not complaining there is no cp, it seems the binary is ok, the problem is missing destination

**Comment by solardiz** [comment] 2019-06-26 16:53
I'm out of ideas. I'll let @claudioandre-br take over further discussion, or try to reproduce the issue, or
close this issue as non-reproducible (after confirming that it's not) and see if we get anything similar reported again.

**Comment by solardiz** [comment] 2019-06-26 16:57
> the problem is missing destination

It's more like missing source operand to `cp`, which is why it confuses the destination for source and says there's no destination. The question is why this would be the case. I'd suspect non-GNU `make` could cause this kind of failure, but then the build would have failed much earlier.

@jmaravi For your own use, if you don't need OpenCL, there's probably already a built `john` binary under `run` by this point. And you can also use our pre-built binaries. That said, if you're able to investigate the problem further and have ideas on that, please feel free to proceed - this would be helpful.

**Comment by solardiz** [comment] 2019-06-26 17:00
@jmaravi What do these commands say? -
```
which make
type make
make --version
```

**Comment by jmaravi** [comment] 2019-06-26 17:57
(Inside cygwin)
PC@DESKTOP-AU03JV2 ~
$ which make
/usr/bin/make

PC@DESKTOP-AU03JV2 ~
$ type make
make is /usr/bin/make

PC@DESKTOP-AU03JV2 ~
$ make --version
GNU Make 4.2.1
Built for x86_64-unknown-cygwin
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by solardiz** [comment] 2019-06-26 18:53
> GNU Make 4.2.1

I've just confirmed that building with this very version of `make` on Linux succeeds. (I don't have Windows handy.)

Can you try `make kernel-copy`?

(I was wondering why we even have that separate make target, but the commit message at cb482cc6d4ea159a324ad52d8bd2b0b3c86f51fc explains it.)

**Comment by solardiz** [comment] 2019-06-26 18:54
Regardless of the present issue, maybe we need to simplify the OpenCL kernel copying. We have this:
```make
opencl_%.h:     | ../run/kernels
        $(CP) $< ../run/kernels

%.cl:   | ../run/kernels
        $(CP) $< ../run/kernels

../run/kernels:
        $(MKDIR) ../run/kernels
```
and we also have this:
```make
.PHONY: kernel-copy

kernel-copy:
        $(MKDIR) ../run/kernels
        $(CP) opencl/*.cl ../run/kernels
        $(CP) opencl_*.h ../run/kernels
```
The latter is much less demanding on properties of `make`.

**Comment by jmaravi** [comment] 2019-06-26 19:08
That last command made the trick.. 
Running ..\run\john --test=0
 right now

**Comment by jmaravi** [comment] 2019-06-26 19:11
Spoke to early.While running the test:Testing: sha1crypt-opencl, (NetBSD) [PBKDF1-SHA1 OpenCL 8x]... Segmentation fault (core dumped)

**Comment by solardiz** [comment] 2019-06-26 20:11
What GPUs do you have in that machine? I wouldn't be surprised by random OpenCL failures if you use an embedded Intel GPU, although having the very first format fail test might indicate some other problem. If you don't really need OpenCL, you can `john --test --format=cpu`.

Please don't quote e-mails from GitHub in your replies. Edit: I don't normally edit other people's comments, but I've just edited out the quoted GitHub e-mails as this thread was hard to wade through otherwise.

**Comment by d0gkiller87** [comment] 2019-07-08 23:45
Thanks to the above comments, after a few tries I succeeded in building the executables.
Things worth to note:
1. After copying files to `../run/kernels`, I encountered another error:
```
make[1]: *** No rule to make target '../run/kernels/7z_kernel.cl', needed by 'kernels'.  Stop.
make: *** [Makefile:189: default] Error 2
```
2. In the DOC (INSTALL-WINDOWS), there's a step to do `./configure && make -s clean && make -sj4` at once, which means every time when you try to build, the `make -s clean` deletes all files under `../run/kernels`, reproduces the error, and interrupts the building process.
3. To fix this on User-Side, simply do `make kernel-copy`, OR manually copy `opencl/*.cl` and `opencl_*.h` to `../run/kernels`. And then do `make -sj4` separately.

**Comment by solardiz** [comment] 2019-07-09 10:31
Thank you, @vungsung. I expect our fix of #4038 will take care of this.

**Comment by magnumripper** [comment] 2019-07-10 06:45
I'm closing this - please reopen if problem remains now that #4038 is fixed.

**Closed as completed by magnumripper** 2019-07-10 06:45 UTC
Labels: portability

**Comment by MESWEB** [comment] 2019-11-19 01:45
I have same error:

> config.status: executing default commands
configure: creating ./fmt_externs.h
-fThe system cannot find the file specified.
configure: error: The build of fmt_externs.h failed. Can not continue!
Input record exceeds maximum length.  Specify larger maximum.

**Comment by solardiz** [comment] 2019-11-19 12:02
On Mon, Nov 18, 2019 at 05:45:52PM -0800, MESWEB wrote:
> Input record exceeds maximum length.  Specify larger maximum.

So I guess you're not running from a Cygwin shell.  You should be.
