### ISSUE TITLE
Problem with opencl

### ISSUE THREAD

**Issue by img507** [openwall/john#5346] opened 2023-07-27 15:47 UTC
I have a problem with my nvidia video card. After I enter the command john --list=opencl-devices I get the following message Device #0 (1) name: NVIDIA GeForce RTX 2060
-     Device vendor: NVIDIA Corporation
-     Device type: GPU (LE)
-     Device version: OpenCL 3.0 CUDA
-     OpenCL version support: OpenCL C 1.2
-     Driver version: 536.67 [recommended]
-     Native vector widths: char 1, short 1, int 1, long 1
-     Preferred vector width: char 1, short 1, int 1, long 1
-     Global Memory: 6143 MiB
-     Global Memory Cache: 960 KiB
-     Local Memory: 48 KiB (Local)
-     Constant Buffer size: 64 KiB
-     Max memory alloc. size: 1535 MiB
-     Max clock (MHz): 1680
-     Profiling timer res.: 1000 ns
-     Max Work Group Size: 1024
-     Parallel compute cores: 30
-     CUDA INT32 cores: 1920 (30 x 64)
-     Speed ​​index: 3225600
-     Warp size: 32
-     Max. GPRs/work-group: 65536
-     Compute capability: 7.5 (sm_75)
-     kernel exec. timeout: yes
-     PCI device topology: 01:00.0

The problem lies in the line: 
OpenCL version support: OpenCL C 1.2
I don't understand why this line appears, it means that I can only use version 1.2 of opencl. At the same time, performance drops and the video card does not work fully. I have windows 10, I installed JtR using cygwin and added the OpenCl.dll file according to the instructions, but JtR does not start inside it and then I decided to use the usual command line
How can I fix this?

**Comment by solardiz** [comment] 2023-07-27 16:57
> The problem lies in the line:
> OpenCL version support: OpenCL C 1.2

This isn't a problem. We don't need more than 1.2 anyway.

> At the same time, performance drops and the video card does not work fully.

Please be more specific - performance drops comparing what against what else? And what exactly does not work fully?

**Comment by img507** [comment] 2023-07-27 17:38
> > The problem lies in the line:
> > OpenCL version support: OpenCL C 1.2
> 
> This isn't a problem. We don't need more than 1.2 anyway.
> 
> > At the same time, performance drops and the video card does not work fully.
> 
> Please be more specific - performance drops comparing what against what else? And what exactly does not work fully?

c/s real is very different from c/s virtual
C:\Users\******\OneDrive\Desktop\JtR\run>john --test --format=wpapsk-opencl
Device 1: NVIDIA GeForce RTX 2060
Benchmarking: wpapsk-opencl, WPA/WPA2/PMF/PMKID PSK [PBKDF2-SHA1 OpenCL]... LWS=256 GWS=491520 (1920 blocks) DONE
Raw: 113936 c/s real, 351462 c/s virtual

JtR itself doesn't start from cygwin terminal after writing ./john --help nothing happens

**Comment by solardiz** [comment] 2023-07-27 17:45
> c/s real is very different from c/s virtual

That's normal. "Virtual" is measured in CPU time, but you're using GPU, so this indirectly shows you CPU load while using GPU. If virtual c/s is a lot higher than real, it means your CPU is mostly idle while using GPU, which is great.

> JtR itself doesn't start from cygwin terminal after writing ./john --help nothing happens

Now, that is finally a problem. I don't know why this would be happening.

Did you build JtR from source? Using git code from this repo? Can you show `john --list=build-info`?

**Comment by img507** [comment] 2023-07-27 18:08
> > c/s real is very different from c/s virtual
> 
> That's normal. "Virtual" is measured in CPU time, but you're using GPU, so this indirectly shows you CPU load while using GPU. If virtual c/s is a lot higher than real, it means your CPU is mostly idle while using GPU, which is great.
> 
> > JtR itself doesn't start from cygwin terminal after writing ./john --help nothing happens
> 
> Now, that is finally a problem. I don't know why this would be happening.
> 
> Did you build JtR from source? Using git code from this repo? Can you show `john --list=build-info`?


I downloaded JtR from here
https://github.com/openwall/john-packages/releases/tag/jumbo-dev
After that, I unpacked the archive winX64_1_JtR.7z in C:\cygwin64\home\****
After entering the command john --list=build-info in a normal command line
C:\cygwin64\home\****\JtR\run>john --list=build-info

- Version: 1.9.0-jumbo-1+bleeding-15b3b7c 2023-04-03 12:44:54 -0300
- Build: cygwin 64-bit x86_64 AVX2 AC OMP OPENCL
- SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
- CPU tests: AVX2
- CPU fallback binary: john-xop
- OMP fallback binary: john-avx2-non-omp
- $JOHN is
- Format interface version: 14
- Max. number of reported tunable costs: 4
- Rec file version: REC4
- Charset file version:CHR3
- CHARSET_MIN: 1 (0x01)
- CHARSET_MAX: 255 (0xff)
- CHARSET_LENGTH: 24
- SALT_HASH_SIZE: 1048576
- SINGLE_IDX_MAX: 2147483648
- SINGLE_BUF_MAX: 4294967295
- Effective limit: Number of salts vs. SingleMaxBufferSize
- Max. Markov mode level: 400
- Max. Markov mode password length: 30
- gcc version: 11.3.0
- OpenCL headers version: 2.2
- Crypto library: OpenSSL
- OpenSSL library version: 01010114f
- OpenSSL 1.1.1t Feb 7, 2023
- GMP library version: 6.2.1
- File locking: fcntl()
- fseek(): fseek
- ftell(): ftell
- fopen(): fopen
- memmem(): System's
- times(2) sysconf(_SC_CLK_TCK) is 1000
- Using times(2) for timers, resolution 1 ms
- HR timer: QueryPerformanceCounter(), latency 100ns
- Total physical host memory: 16302 MiB
- Available physical host memory: 11902 MiB
- Terminal locale string: C.UTF-8
- Parsed terminal locale: UTF-8

**Comment by solardiz** [comment] 2023-08-14 11:17
@claudioandre-br Did you possibly want to comment on this? -

> JtR itself doesn't start from cygwin terminal after writing ./john --help nothing happens

Maybe there's now a new build for @NordmanPro to test?

Other than that, I think we should close this issue, because everything else reported here was correct and intended behavior.

**Comment by ghost** [comment] 2023-08-14 11:25
> @claudioandre-br Did you possibly want to comment on this? -
> 
> > JtR itself doesn't start from cygwin terminal after writing ./john --help nothing happens

I cannot reproduce, locally or using cloud.

In fact, the Windows package (itself) is tested after "packaging" and before release. So, this is a kind of strange situation where clarification is required.

The released package is up to date with this Github repo. Nothing (new) to build for now.

**Comment by ghost** [comment] 2023-08-14 11:31
BTW: the version seen above `1.9.0-jumbo-1+bleeding-15b3b7c 2023-04-03 12:44:54 -0300` is not `jumbo-dev`, it is the `rolling` version. For Windows and NVIDIA anyone should use `jumbo-dev` [1] now.

[1] recommended when writing this.

**Comment by solardiz** [comment] 2023-08-14 11:36
OK, I'll close this issue now as we don't need to track it, but please feel free to add comments.

**Closed as completed by solardiz** 2023-08-14 11:36 UTC
Labels: question
