### ISSUE TITLE
Multiple dictionaries cannot be used in wordlist mode

### ISSUE THREAD

**Issue by EMU-TIME** [openwall/john#4951] opened 2021-12-21 07:09 UTC
For example:
```
--wordlist=D:\TOOLS\wl\*
Warning: no OpenMP support for this hash type, consider --fork=16
fopen: D:\TOOLS\wl\*: No such file or directory
```

**Because my dictionary is really too big, I divided it into a single file with a size of 1G**
Hope to improve

**Comment by solardiz** [comment] 2021-12-21 07:59
Thanks for the feature request. This is a duplicate of #3262, so I'll close this one. We can discuss the general issue/enhancement there.

That said, @EMU-TIME, for your particular use case:

I think this functionality would be most useful for wordlists that are genuinely distinct, not when you've artificially split them. Just where did they come from, and how did you split? I hear some people use `crunch` - well, just don't use it, at all! We have all of its functionality built-in.

I successfully use wordlists that are even 100 GB in a file, although I ended up adjusting some settings to work around #4906, #4907. Most importantly, in my case that size is a result of wordlist+rules deduplication with our `unique` utility, which I did because I run against slow hashes, whereas you seem to have a fast hash type there, and so shouldn't need anything this large (no need for the deduplication, it's quicker to run through everything including the dupes). I think the largest you'd currently reasonably run against a fast hash is ~15 GB (the size of reasonable wordlists available for download), and that should work as-is without issues. Doesn't it?

**Closed as completed by solardiz** 2021-12-21 07:59 UTC
Labels: enhancement, dupe
