### ISSUE TITLE
OpenCl RTX 3060 error

### ISSUE THREAD

**Issue by Banane480** [openwall/john#5319] opened 2023-06-14 14:05 UTC
C:\Hack\john-1.9.0-jumbo-1-win64\run>john --format=ZIP-opencl hash.txt
Device 1: NVIDIA GeForce RTX 3060 Laptop GPU
Using default input encoding: UTF-8
Loaded 1 password hash (ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL])
2 errors generated.
Options used: -I kernels -cl-mad-enable -DSM_MAJOR=8 -DSM_MINOR=6 -D__GPU__ -DDEVICE_INFO=18 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=536 -DDEV_VER_MINOR=23 -D_OPENCL_COMPILER -DKEYLEN=64 -DSALTLEN=64 -DOUTLEN=68 kernels/zip_kernel.cl
Build log: In file included from <kernel>:9:
kernels\opencl_sha1_ctx.h:150:22: error: passing '__generic uchar *' (aka '__generic unsigned char *') to parameter of type 'const uchar *' (aka 'const unsigned char *') changes address space of pointer
                _sha1_process(ctx, ctx->buffer);
                                   ^~~~~~~~~~~
kernels\opencl_sha1_ctx.h:69:46: note: passing argument to parameter 'data' here
void _sha1_process(SHA_CTX *ctx, const uchar data[64]) {
                                             ^
kernels\opencl_sha1_ctx.h:158:22: error: passing 'const __generic uchar *' (aka 'const __generic unsigned char *') to parameter of type 'const uchar *' (aka 'const unsigned char *') changes address space of pointer
                _sha1_process(ctx, input);
                                   ^~~~~
kernels\opencl_sha1_ctx.h:69:46: note: passing argument to parameter 'data' here
void _sha1_process(SHA_CTX *ctx, const uchar data[64]) {
                                             ^

Error building kernel kernels/zip_kernel.cl. DEVICE_INFO=18
0: OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1386 - clBuildProgram

C:\Hack\john-1.9.0-jumbo-1-win64\run>

**Comment by Banane480** [comment] 2023-06-14 14:21
### **New bug (updated driver)** Just no output :/

C:\Hack\john-1.9.0-jumbo-1-win64\run>john --format=ZIP-opencl hash.txt

C:\Hack\john-1.9.0-jumbo-1-win64\run>

**Comment by solardiz** [comment] 2023-06-14 17:07
This is a duplicate of #5205, #5222. We've already fixed the issue, but have not yet made a new release. To get around the issue, please either use a newer build available via the "Download Windows Build" badge off the README.md in this repo (currently points to https://github.com/openwall/john-packages/releases/tag/jumbo-dev and the file is winX64_1_JtR.7z) or use an _older_ version of the NVIDIA driver than you currently have.

We recommend using our newer build rather than downgrading your driver.

**Closed as completed by solardiz** 2023-06-14 17:07 UTC
Labels: portability, dupe

**Comment by Banane480** [comment] 2023-06-16 10:47
Yo, i fixed the problem but thx for supprt !
