### ISSUE TITLE
bitcoin2john.py doesn't work

### ISSUE THREAD

**Issue by savelyglazkov** [openwall/john#4928] opened 2021-12-10 18:13 UTC
Hi
I'm trying to convert 1GB wallet.dat into hashcat hash. wallet.dat has been created in 2020, bitcoin core works fine with this wallet.dat file
Here is output of bitcoin2john.py:

Traceback (most recent call last):
  File "bitcoin2john.py", line 619, in parse_wallet
    d['lockTime'] = vds.read_uint32()
  File "bitcoin2john.py", line 498, in read_uint32
    def read_uint32(self): return self._read_num('<I')
  File "bitcoin2john.py", line 539, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
error: unpack_from requires a buffer of at least 4 bytes
ERROR parsing wallet.dat, type txkey data: tx����P
                                                  ���yL�BZ[�CK�j^g��?�key data in hex: [removed]value data in hex:[removed]

**Comment by solardiz** [comment] 2021-12-10 18:37
@savelyglazkov You seem to be using an older version of the script coming from a JtR release. Please upgrade to the latest found in this repo, and the problem will most likely be gone. BTW, you would also be able to attack the resulting hash with JtR, including on GPU (again, if you use the latest from this repo), not only with hashcat.

**Comment by savelyglazkov** [comment] 2021-12-10 18:41
I'm using version 1.9.0

**Comment by ghost** [comment] 2021-12-10 18:45
> I'm using version 1.9.0

Solar is asking you to download the latest/bleeding version from this repository and try using it. The 1.9.0 script version is outdated.

**Comment by solardiz** [comment] 2021-12-11 13:48
@savelyglazkov So, have you tried the latest? Does it work?

Edit: To be specific, we mean https://raw.githubusercontent.com/openwall/john/bleeding-jumbo/run/bitcoin2john.py although it's better for you to use the whole JtR tree from here.

**Comment by solardiz** [comment] 2021-12-13 14:15
I'll close the issue now since it's not something we need to track - we believe the issue is avoided in our latest code, and those line numbers don't even exist anymore.

However, please feel free to add comments to this issue.

**Closed as completed by solardiz** 2021-12-13 14:15 UTC
Labels: question
