### ISSUE TITLE
zip2john segfault with AES archive that has 0 as compressed len in local header

### ISSUE THREAD

**Issue by srett** [openwall/john#4054] opened 2019-07-22 08:07 UTC
I have an AES encrypted zip file that was created with Threema for Android in 2017. zip2john immediately crashes when processing the file. Upon inspection I found that the local header of every file has the compressed_size set to 0, which then leads to an unsigned underflow when [calculating real_cmpr_len](https://github.com/magnumripper/JohnTheRipper/blob/9b4335e7c004f3fc0986c2e06aa3aa8ba8f5ee74/src/zip2john.c#L292).  According [to wikipedia](https://en.wikipedia.org/wiki/Zip_(file_format)#Data_descriptor) this is legal under some circumstances, and the compessed_length could be extracted from the central directory entry. This would probably require two passes over the archive and building an index, or seeking around quite a bit while processing. I didn't check yet whether the archive I got here actually has that 12/16 byte data descriptor appended to the compressed BLOB at all, and whether it's supposed to come before or after the 10 byte authentication code.

I've been sitting on this for 2 months now planning to take a stab at it during the weekends but never got around to it, so I better open this issue before forgetting about it entirely, so the next person running into this doesn't have to start from scratch.

**Comment by magnumripper** [comment] 2019-07-29 09:50
Thanks for reporting. IIRC we're supposed to handle such files, but maybe we only do so for legacy pkzip archives?

**Comment by srett** [comment] 2019-07-29 11:40
Took a quick look, the old code does handle this, but not by parsing the central directory entry, but by scanning for the 16 byte data descriptor that will be appended to the compressed data. The problem here might be that the existing code does so by looking for the *optional* descriptor signature (0x08074b50), so this will not work in case that signature is omitted, or if that sequence appears in the compressed/encrypted data stream. So I think parsing the central directory would be the safest approach, and then skip over the 12/16 bytes data descriptor, or maybe use it for validation, since it should obviously match what's in the central directory.

**Comment by magnumripper** [comment] 2019-07-30 10:51
Just so you know, we'd love if you'd fix it (ideally for both cases old/new, perhaps with some shared code if applicable) and make a PR. We're seriously low on developers and you seem to know what you're doing here.

**Comment by srett** [comment] 2019-07-30 14:50
I'm still interested in doing that. I hope I can get back to this in a couple weeks. Currently very busy IRL.

**Comment by magnumripper** [comment] 2019-11-26 21:20
@srett we seem to have more issues related to (or dupe of) this issue. Do you think you'll get any time to look into it? I might get down to it this year, or not...

**Comment by srett** [comment] 2019-12-07 10:55
@magnumripper  I'm still interested in giving it a try; got another busy week at work and then the usual hunt for presents... *Maybe* between Christmas and new year's, but January will be quite busy again. :(

When I took a look at it back in July I was unsure whether a quick and dirty fix extending the current code would do, or if it would be worth considering re-doing the whole thing, since as you mentioned, there is some duplicated code/functionality between old and new archive types. Just from poking through the specs back then, in theory there can be a lot of little variations to which fields are omitted, which could be set to zero, etcpp., so covering every possibility would be tedious, especially as we have no clue which of these actually get produced by real world tools. Also one might optionally want to verify whether the information from the local header and central directory matches up, but that somewhat goes beyond the scope of what this tool is supposed to do I guess...

Anyways, a suite of different archive types produced by different tools to test against would probably come in handy when doing this. Anything like this around?

**Comment by magnumripper** [comment] 2019-12-08 07:29
There's some samples at https://openwall.info/wiki/john/sample-non-hashes#ZIP but we don't seem to have the same for 'pkzip' hashes

**Comment by srett** [comment] 2019-12-29 11:29
Got to start working on this. ZIP files are a real rabbit hole. Found a couple of other potential issues where the current code would fail and trying my best to address those. Some are more or less theoretical. One funny issue I found is that the current code that scans for the magic signatures of file headers could easily be fooled by prefixing them with another 0x50 byte, which would still make a valid zip archive but zip2john would skip over all of those.

My current plan is to scan the central directory at the end first, and then process all the files from there, so the sizes and CRCs should be known in advance. The downside is that this won't work for multi-part archives (without significant additional work), so I will leave the old approach of "just scan for local file headers from the beginning and hope for the best" as a command line switch.

**Comment by magnumripper** [comment] 2019-12-30 15:50
Sounds great, thanks for your efforts!

**Comment by srett** [comment] 2020-01-01 23:26
Getting there. Did a first commit at https://github.com/srett/JohnTheRipper/tree/zip2john-central-dir if anyone wants to test it. Still needs some more cleanup.

I found that when using the current zip2john on the AES-256 test file you linked above, john doesn't like the resulting hash. Did I just mess up my local test environement? It seems to work with my version though.. :-)
The tarball also contains some old pkzip samples, but no strong encryption ones, so that code path is still untested.

**Comment by magnumripper** [comment] 2020-01-02 15:38
I can do some testing next week (although we can merge this earlier if/when everything seems fine and dandy).

**Comment by srett** [comment] 2020-01-03 11:48
OK ignore what this comment said before; I just realized john extracts the password from the file name :man_facepalming: 

I'll test a couple more encryption schemes and zip creation tools, do a little more renaming and refactoring and then it should be good to go.

**Comment by magnumripper** [comment] 2020-01-03 13:15
Good stuff 👍🏼

**Closed as completed** 2020-03-04 17:50 UTC
Labels: bug
