### ISSUE TITLE
error: size of array element is not a multiple of its alignment

### ISSUE THREAD

**Issue by Petomai** [openwall/john#5445] opened 2024-03-09 09:12 UTC
during ./configure && make

 -Wunused-but-set-variable -std=gnu89 -Wdate-time -D_POSIX_SOURCE -D_GNU_SOURCE -D_XOPEN_SOURCE=600   -fopenmp   -DHAVE_HT  -I/usr/local/include -funroll-loops argon2_core_plug.c -o argon2_core_plug.o
In file included from argon2_core_plug.c:32:
blake2.h:112:5: error: size of array element is not a multiple of its alignment
  112 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
blake2.h:113:5: error: size of array element is not a multiple of its alignment
  113 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~
make[1]: *** [Makefile:1624: argon2_core_plug.o] Error 1

OS Linux Mint
Linux mint 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Python 3.10.12

**Comment by solardiz** [comment] 2024-03-09 13:42
Hi @Petomai. This is a known and fixed issue, please update to our latest code from here and try again. Duplicate of #4604 #5351 #5442.

**Closed as completed by solardiz** 2024-03-09 13:42 UTC
Labels: portability, dupe

**Comment by rlovell3** [comment] 2024-04-17 13:19
For what it's worth, today (2024-04-17) I downloaded the john-1.9.0-jumbo-1.tar.gz from the openwall website, and received the same blake2.h blake2b_state errors during make. I will try downloading the code from here (github repository) and look for diffs.  I'm using gcc -version 11.4.0.

**Comment by rlovell3** [comment] 2024-04-17 13:32
Cloning this Github repo and running the config and make steps was successful.  No build errors.
Below is from the website tar.gz file that I downloaded earlier today.
```bash
sha256sum john-1.9.0-jumbo-1.tar.gz
8b40499a20fdd66d5f651b439bf9846367182bb93e8bff3fd39ba267576dd317  john-1.9.0-jumbo-1.tar.gz
```
