### ISSUE TITLE
Can't build john-1.9.0-jumbo-1 at macOS Sierra and High Sierra

### ISSUE THREAD

**Issue by catap** [openwall/john#4077] opened 2019-08-28 10:08 UTC
Het,

I've tried to upgrade brew's john-jumbo formula and it doesn't build on Sierra and High Sierra: https://github.com/Homebrew/homebrew-core/pull/43531

```
==> make -s CC=clang
ar: creating archive aes.a
ar: creating archive secp256k1.a
ar: creating archive ed25519-donna.a
Undefined symbols for architecture x86_64:
  "_fmt_stribog_256", referenced from:
      _john_register_all in john.o
  "_fmt_stribog_512", referenced from:
      _john_register_all in john.o
ld: symbol(s) not found for architecture x86_64
```

@magnumripper can you have any ideas what should I do?

**Comment by catap** [comment] 2019-08-29 13:43
As discussed at #4078 let move back to this issue to continue discussing.

Cc: @magnumripper, @solardiz

**Comment by catap** [comment] 2019-08-29 20:18
A bit more info about this machine:

Testing for SSE4.1 that is failed:

```
configure:10866: result: no
configure:10878: checking special compiler flags
configure:10880: result: Intel x86
configure:10893: checking whether OS X 'as' needs -q option
configure:10905: clang -mavx -o conftest -m64 -g -O2 -I/usr/local/include -I/usr/local/opt/openssl/include   -O0  -I/usr/local/include -I/usr/local/opt/openssl/include -m64  -L/usr/local/lib -L/usr/local/opt/openssl/lib conftest.c  >&5
configure:10905: $? = 0
configure:10906: result: no
configure:11359: Testing tool-chain's CPU support with given options
configure:11361: checking for MMX
configure:11373: clang -o conftest -m64 -g -O2 -I/usr/local/include -I/usr/local/opt/openssl/include   -O0  -I/usr/local/include -I/usr/local/opt/openssl/include -m64  -L/usr/local/lib -L/usr/local/opt/openssl/lib conftest.c  >&5
configure:11373: $? = 0
configure:11379: result: yes
configure:11392: checking for SSE2
configure:11404: clang -o conftest -m64 -g -O2 -I/usr/local/include -I/usr/local/opt/openssl/include   -O0  -I/usr/local/include -I/usr/local/opt/openssl/include -m64  -L/usr/local/lib -L/usr/local/opt/openssl/lib conftest.c  >&5
configure:11404: $? = 0
configure:11410: result: yes
configure:11425: checking for SSSE3
configure:11437: clang -o conftest -m64 -g -O2 -I/usr/local/include -I/usr/local/opt/openssl/include   -O0  -I/usr/local/include -I/usr/local/opt/openssl/include -m64  -L/usr/local/lib -L/usr/local/opt/openssl/lib conftest.c  >&5
configure:11437: $? = 0
configure:11440: result: yes
configure:11456: checking for SSE4.1
configure:11468: clang -o conftest -m64 -g -O2 -I/usr/local/include -I/usr/local/opt/openssl/include   -O0  -I/usr/local/include -I/usr/local/opt/openssl/include -m64  -L/usr/local/lib -L/usr/local/opt/openssl/lib conftest.c  >&5
conftest.c:30:52: error: '__builtin_ia32_roundpd' needs target feature sse4.1
        int main(){__m128d t;*((long long*)&t)=1;t=_mm_round_pd(t,1);if((*(long long*)&t)==88)printf(".");exit(0);}
                                                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include/smmintrin.h:323:12: note: expanded from macro '_mm_round_pd'
  (__m128d)__builtin_ia32_roundpd((__v2df)(__m128d)(X), (M)); })
           ^
1 error generated.
configure:11468: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "john"
| #define PACKAGE_TARNAME "john"
| #define PACKAGE_VERSION "jumbo"
| #define PACKAGE_STRING "john jumbo"
| #define PACKAGE_BUGREPORT "john-users mailing list at openwall.com"
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define SIZEOF_SHORT 2
| #define SIZEOF_INT 4
| #define SIZEOF_LONG 8
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_WCHAR_T 4
| #define SIZEOF_INT_P 8
| #define SIZEOF_VOID_P 8
| /* end confdefs.h.  */
| 
|     #include <smmintrin.h>
|         #include <stdio.h>
|         extern void exit(int);
|         int main(){__m128d t;*((long long*)&t)=1;t=_mm_round_pd(t,1);if((*(long long*)&t)==88)printf(".");exit(0);}
| 
| 
configure:11476: result: no
```

I've attached full build log that contains output of `config.log`, `fmt_externs.h` and `fmt_registers.h`

[consoleText.txt](https://github.com/magnumripper/JohnTheRipper/files/3557206/consoleText.txt)

**Comment by magnumripper** [comment] 2019-08-29 23:05
Looks like some patch is still applied to stribog formats? Why? As long as I can't see that patch I will suspect it. Without any patch, you won't get the Stribog formats unless `__SSE4_1__` is defined, and that's about it. Either there's some screw-up in that patch - or something, somewhere is actually *defining* `__SSE4_1__` before/while creating fmt_externs.h and fmt_registers.h. You just need to find it...

**Comment by catap** [comment] 2019-08-30 09:32
@magnumripper clang defines it.

```
==> clang -dM -E test.c
...
#define __SSE2_MATH__ 1
#define __SSE2__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE_MATH__ 1
#define __SSE__ 1
#define __SSP__ 1
#define __SSSE3__ 1
...
```

I've attached updated full log that contains also this output.

[consoleText.txt](https://github.com/magnumripper/JohnTheRipper/files/3559292/consoleText.txt)

So, I don't understand why:
 - clang defines `__SSE4_1__`
 - clang can't compile test with error `'__builtin_ia32_roundpd' needs target feature sse4.1`

**Comment by solardiz** [comment] 2019-08-30 10:25
On Fri, Aug 30, 2019 at 02:32:20AM -0700, Kirill A. Korinsky wrote:
> So, I don't understand why:
>  - clang defines `__SSE4_1__`
>  - clang can't compile test with error `'__builtin_ia32_roundpd' needs target feature sse4.1`

Maybe we're passing a certain flag (enabling SSE4.1 use) during compilation, but not during linking.  Generally, these flags are not needed during linking, but maybe we have an exception for clang on macOS.

**Comment by catap** [comment] 2019-08-30 10:30
@solardiz I've hacked my brew script to run just clang and dump all default defined options `-dM -E test.c` where `test.c` is just empty file.

and it has defined `__SSE4_1__`

But when `./configure` test the system and try to build
```
int main(){__m128d t;*((long long*)&t)=1;t=_mm_round_pd(t,1);if((*(long long*)&t)==88)printf(".");exit(0);}
```

it can't with error: `needs target feature sse4.1`

So, I do not understand what's going on.

**Comment by solardiz** [comment] 2019-08-30 10:35
Looks like this build of clang is misconfigured, but maybe we can workaround it.

What happens if you try to build https://www.openwall.com/php_mt_seed/ ?

**Comment by catap** [comment] 2019-08-30 10:38
@solardiz it is tricky part: I have access to this machine only over github pull request's hook :)

I'll try but not sure that I can.

**Comment by catap** [comment] 2019-09-12 09:40
@solardiz I've tried and php_mt_seed builds without any issue at all three brew's build machine. Just `make` and it works.

**Comment by magnumripper** [comment] 2019-09-12 19:04
Try configuring Jumbo with `./configure CC="clang -mno-sse4.1" --disable-native-tests`. That ought to work fine.

~~BTW what exactly is the `configure` line in that Homebrew formula?~~ I've tried all sorts of ways to reproduce your problem on Mojave, but I can't. I did use Sierra and High Sierra when they were they latest'n'greatest and never saw any problem like this one.

**EDIT**: I see the formula has it as `./configure --disable-native-tests --disable-native-march`. The problem is simply that clang enables SSE-4.1 by default.

On a side note, `--disable-native-march` is no longer needed cause that's default now.

**Comment by magnumripper** [comment] 2019-09-12 19:05
Then again, you'll get a much better build (faster AND with OpenMP support) if you build using gcc instead, as mentioned in bottom of `doc/INSTALL`

**Comment by catap** [comment] 2019-09-12 23:18
@magnumripper thanks for feedback.

I've updated a formula:
 - removed `--disable-native-march`
 - added `-mno-sse4.1` if machine doesn't support sse4 (I've found test `Hardware::CPU.sse4?` let test it)
 - added `libomp`, atleast at php-mt-seed it works with clang.

I hope soon I've closed this magic issue.

**Comment by catap** [comment] 2019-09-13 07:52
Welll, `Hardware::CPU.sse4?` returns `true` at this machines => it crashed

**Comment by catap** [comment] 2019-09-13 08:39
@magnumripper 

and it doesn't build with `mnosse-4.1` at all:

```
0:34:23 checking openssl/opensslv.h presence... yes
10:34:23 configure: WARNING: openssl/opensslv.h: present but cannot be compiled
10:34:23 configure: WARNING: openssl/opensslv.h:     check for missing prerequisite headers?
10:34:23 configure: WARNING: openssl/opensslv.h: see the Autoconf documentation
10:34:23 configure: WARNING: openssl/opensslv.h:     section "Present But Cannot Be Compiled"
10:34:23 configure: WARNING: openssl/opensslv.h: proceeding with the compiler's result
10:34:23 configure: WARNING:     ## ------------------------------------------------------ ##
10:34:23 configure: WARNING:     ## Report this to john-users mailing list at openwall.com ##
10:34:23 configure: WARNING:     ## ------------------------------------------------------ ##
10:34:23 checking for openssl/opensslv.h... no
10:34:23 configure: error: in `/private/tmp/john-jumbo-20190913-15196-1yupq1z/john-1.9.0-jumbo-1/src':
10:34:23 configure: error: JtR requires OpenSSL headers being installed
10:34:23 See `config.log' for more details
```

**Comment by catap** [comment] 2019-09-13 09:06
I can build it at their buildservices with *very* wired hack:
```
ENV.append "CFLAGS", "-U__SSE4_1__" unless MacOS.version.requires_sse4?
```

**Comment by catap** [comment] 2019-09-13 11:20
~After I've spent a bit more time to debugging it, I've discovered a root cause why we have it.~

~compilers options at generation `fmt_registers.h` and `fmt_externs.h` a bit different than at compiling `stribog_fmt_plug.o`.~

~Let's compare:~
```
clang -E -P -DAC_BUILT   -I/usr/local/include -I/usr/local/opt/openssl/include -DCL_SILENCE_DEPRECATION -mssse3 -m64 -DJOHN_SYSTEMWIDE=1 -DJOHN_SYSTEMWIDE_EXEC='"/usr/local/Cellar/john-jumbo/1.9.0/share/john"' -DJOHN_SYSTEMWIDE_HOME='"/usr/local/Cellar/john-jumbo/1.9.0/share/john"' -I/usr/local/include -I/usr/local/opt/openssl/include -DARCH_LITTLE_ENDIAN=1 -DHAVE_OPENCL   -Wall -Wno-tautological-constant-out-of-range-compare -fno-omit-frame-pointer -Wno-deprecated-declarations -Wformat-extra-args -Qunused-arguments -std=gnu89 -Wdate-time   -DFMT_EXTERNS_H *_fmt_plug.c
```

~with~

```
clang -DAC_BUILT -mssse3 -DJOHN_SSSE3 -c -m64 -DJOHN_SYSTEMWIDE=1 -DJOHN_SYSTEMWIDE_EXEC='"/usr/local/Cellar/john-jumbo/1.9.0/share/john"' -DJOHN_SYSTEMWIDE_HOME='"/usr/local/Cellar/john-jumbo/1.9.0/share/john"' -I/usr/local/include -I/usr/local/opt/openssl/include -DARCH_LITTLE_ENDIAN=1  -Wall -Wno-tautological-constant-out-of-range-compare -fno-omit-frame-pointer -Wno-deprecated-declarations -Wformat-extra-args -Qunused-arguments -std=gnu89 -Wdate-time    -D_THREAD_SAFE -pthread -I/usr/local/include -I/usr/local/opt/openssl/include -DCL_SILENCE_DEPRECATION -DHAVE_OPENCL -D_THREAD_SAFE -pthread -funroll-loops stribog_fmt_plug.c -o stribog_fmt_plug.o
```

~How you can see `$CPU_BEST_FLAGS` hasn't got any value here => it brokes everything.~

I've made more clear diff and it isn't cause.

**Comment by fxcoudert** [comment] 2019-09-13 13:21
I've been trying to look into it, but found another issue instead: https://github.com/magnumripper/JohnTheRipper/issues/4098

**Comment by fxcoudert** [comment] 2019-09-13 13:35
Building without OpenSSL fails, as reported above.
But building with OpenSSL also fails: https://github.com/magnumripper/JohnTheRipper/issues/4099

**Comment by solardiz** [comment] 2024-05-25 23:37
> Undefined symbols for architecture x86_64:
>   "_fmt_stribog_256", referenced from:
>       _john_register_all in john.o
>   "_fmt_stribog_512", referenced from:
>       _john_register_all in john.o
> ld: symbol(s) not found for architecture x86_64

Per other comments in here, the above was happening because of an inconsistency around SSE 4.1 (non-)support by clang and/or the linker. Well, this specific issue should no longer be present here because we got rid of the SSE 4.1+ dependency for Stribog in 3238f8f2f369db7eb8fc50286261a44d11468228 fixing #4974.

So I'm closing this issue. If anything in here is still relevant, we can reopen - or open new issue(s) accordingly.

**Closed as completed by solardiz** 2024-05-25 23:37 UTC
