### ISSUE TITLE
On recent NVIDIA drivers, OpenCL formats in 1.9.0-jumbo-1 fail with: error: passing '__generic uchar *' (aka '__generic unsigned char *') to parameter of type 'const uchar *' (aka 'const unsigned char *') changes address space of pointer

### ISSUE THREAD

**Issue by baikaishui007** [openwall/john#5464] opened 2024-04-27 12:54 UTC
Benchmarking: pfx-opencl, PKCS12 PBE (.pfx, .p12) [SHA1 OpenCL]... 3 errors generated.
Options used: -I kernels -cl-mad-enable -DSM_MAJOR=8 -DSM_MINOR=9 -D__GPU__ -DDEVICE_INFO=18 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=551 -DDEV_VER_MINOR=86 -D_OPENCL_COMPILER -DPLAINTEXT_LENGTH=32 -DMAX_DATA_LENGTH=8192 kernels/pfx_kernel.cl
Build log: In file included from <kernel>:12:
In file included from kernels\opencl_pkcs12.h:10:
kernels/opencl_sha1_ctx.h:150:22: error: passing '__generic uchar *' (aka '__generic unsigned char *') to parameter of type 'const uchar *' (aka 'const unsigned char *') changes address space of pointer
                _sha1_process(ctx, ctx->buffer);
                                   ^~~~~~~~~~~
kernels/opencl_sha1_ctx.h:69:46: note: passing argument to parameter 'data' here
void _sha1_process(SHA_CTX *ctx, const uchar data[64]) {
                                             ^
kernels/opencl_sha1_ctx.h:158:22: error: passing 'const __generic uchar *' (aka 'const __generic unsigned char *') to parameter of type 'const uchar *' (aka 'const unsigned char *') changes address space of pointer
                _sha1_process(ctx, input);
                                   ^~~~~
kernels/opencl_sha1_ctx.h:69:46: note: passing argument to parameter 'data' here
void _sha1_process(SHA_CTX *ctx, const uchar data[64]) {
                                             ^
In file included from <kernel>:12:
kernels\opencl_pkcs12.h:93:14: error: passing '__generic uchar *' (aka '__generic unsigned char *') to parameter of type 'uchar *' (aka 'unsigned char *') changes address space of pointer
                SHA1_Final((uchar*)hash_output, &md_ctx);
                           ^~~~~~~~~~~~~~~~~~~
kernels/opencl_sha1_ctx.h:175:23: note: passing argument to parameter 'output' here
void SHA1_Final(uchar output[20], SHA_CTX *ctx) {
                      ^

Error building kernel kernels/pfx_kernel.cl. DEVICE_INFO=18
0: OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1386 - clBuild

**Comment by ghost** [comment] 2024-04-27 14:06
We've probably already fixed this issue, please try with our latest code from this repository.

**Comment by solardiz** [comment] 2024-04-27 17:20
This is a duplicate of #4667, #5205, #5222 (where a comment also includes a workaround), #5319, #5375. It's already fixed. Please use one of: our latest code from this repo (you'll need Cygwin to build from source on Windows), our recent build from https://github.com/openwall/john-packages/releases (Cygwin not required then), or the workaround from #5222:

Edit `john.conf` and find `GlobalBuildOpts`. Append `-cl-std=CL1.2` to what is already there:

```
GlobalBuildOpts = -cl-mad-enable -cl-std=CL1.2
```

**Closed as completed by solardiz** 2024-04-27 17:20 UTC
Labels: portability, dupe
