### ISSUE TITLE
Issue running John.

### ISSUE THREAD

**Issue by sleepy124** [openwall/john#5381] opened 2023-12-04 07:59 UTC
sighan364@penguin:~$ john
-bash: john: command not found
sighan364@penguin:~$ 

i've installed it correctly and tried restarting and installing again still get same issue with any command. im on Linux debain 11.

**Comment by solardiz** [comment] 2023-12-04 15:46
@sleepy124 Are you still having this issue? If you've solved it, please describe how you were installing John, what the issue was, and how you solved it in case others later find this (closed) issue. Thanks.

Edit: I assume @sleepy124 was no longer having the issue due to their comment https://github.com/openwall/john/issues/4245#issuecomment-1838267499

**Comment by ghost** [comment] 2023-12-04 16:00
> no longer having the issue due to their comment 

He was using the flatpak from flathub. I have already merged a workaround for #5380 , the package will be updated soon.
- see https://github.com/flathub/com.openwall.John/pull/10

Anyway, flatpak is not run using the `john` command. 

Once the new package is uploaded, I will post a message in the PR with the necessary update commands.

**Comment by solardiz** [comment] 2023-12-04 18:25
Not an issue we need to track, so closing, but @sleepy124 can feel free to add comments/questions. As it is, we can't provide support not knowing whether the issue is possibly already solved nor any specifics about where it occurred.

We also primarily use GitHub to track issues with our project rather than to provide user support, but we currently don't mind the latter as well.

**Closed as completed by solardiz** 2023-12-04 18:25 UTC
Labels: question

**Comment by ghost** [comment] 2023-12-04 20:35
> I will post a message in the PR with the necessary update commands

Done at https://github.com/flathub/com.openwall.John/pull/10#issuecomment-1839431970

**Comment by sleepy124** [comment] 2023-12-05 07:38
yep its solved thanks to @claudioandre-br =>>>
