### ISSUE TITLE
bcrypt-opencl bugs

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4393] opened 2020-10-01 23:17 UTC
bcrypt-opencl shares CPU-side code with bcrypt, so this issue should be looked into only after fixing #4388 and #4390. It really looks like it may be a single bug ending up in all these issues.

bcrypt-opencl show similar results as the CPU format, with the test-vector "./jtrts.pl -internal" tests:
```
$ rm -f ../run/john.pot && ../run/john --format=bcrypt-opencl BF_hashes.txt -w:BF_TS_wordlist.txt 
Device 1: GeForce RTX 2080 Ti
LWS=8 GWS=4096
Loaded 13 password hashes with 6 different salts (2.2x same-salt boost) (bcrypt-opencl [Blowfish OpenCL])
Cost 1 (iteration count) is 32 for all loaded hashes
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 12 candidates left, minimum 4096 needed for performance.
U*U              (vec_0)
U*U*             (vec_1)
                 (vec_3)
                 (vec_3)
U*U*U            (vec_13)
U*U*U            (vec_2)
�                (vec_5)
�                (vec_6)
�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U�U (vec_10)
U��U��U��U��U��U��U��U��U��U��U��U��U��U��U��U��U��U��U��U��U��U��U��U�� (vec_12)
������           (vec_8)
ё               (vec_7)
12g 0:00:00:00 DONE (2020-10-02 00:58) 60.00g/s 60.00p/s 360.0c/s 780.0C/s Dev#1:31°C 123456789012345678901234567890123456789012345678901234567..U*U*U
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed. 
```
Unlike the CPU format it cracks "12 of 13" hashes. It fails to crack `vec_4` and `vec_9`. And **just like CPU format, it cracks vec_3 twice**.
```
$ wc -l ../run/john.pot 
11 ../run/john.pot

$ sort ../run/john.pot | uniq -d
$2a$05$CCCCCCCCCCCCCCCCCCCCC.7uG0VCzI2bS7j6ymqJi9CdcdxiRTWNy:
```
It only writes 11 of them to the pot file though, even though vec_3 is written twice to it (just like with the CPU format).
```
$ ../run/john --format=bcrypt-opencl BF_hashes.txt -show=left
Device 1: GeForce RTX 2080 Ti
LWS=8 GWS=4096
vec_9:$2a$05$/OK.fbVrR/bpIqNJ5ianF.swQOIzjOiJ9GHEPuhEkvqrUyvWhEMx6
vec_2:$2a$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a
vec_4:$2a$05$abcdefghijklmnopqrstuu5s2v8.iXieOjg/.AySBTTZIIVFJeBui
```
Just like CPU format, we fail to write `vec_2` to the potfile. If we run again, `vec_2` is again cracked and now it's in pot file as well.

**Comment by solardiz** [comment] 2020-10-30 13:59
Per my testing, as expected #4422 fixes the first bug reported here: there's no longer a duplicate crack and line in `john.pot` for `vec_3`.

Also as expected there's still the issue with `vec_2` only getting properly written (with its `$2a$` hash prefix) to `john.pot` on a rerun. That's because of #4388.

Further, somehow the OpenCL format doesn't crack `vec_4` and `vec_9`. Running the CPU format after two runs of the OpenCL format does finally crack those two. This looks like an OpenCL format specific bug to me.

**Comment by solardiz** [comment] 2020-10-30 16:24
> Further, somehow the OpenCL format doesn't crack `vec_4` and `vec_9`.

I figured this out - this format misses `FMT_TRUNC`, which makes JtR think the limit of 72 is implementation-specific and thus skip longer candidates. Adding that flag fixes the issue. I've checked that the CPU and ZTEX formats do have this flag.

Maybe we need to enhance our self-test to complain about formats that have longer than `plaintext_length` test vectors (intended to test truncation) yet lack `FMT_TRUNC`.

**Comment by solardiz** [comment] 2020-10-31 12:13
This issue is currently only kept open to retest the `vec_2` aspect of it after having fixed #4388, if we do. We'll also need to similarly test bcrypt-ztex.

**Comment by solardiz** [comment] 2020-11-01 19:03
Confirmed that #4428 also fixes bcrypt-opencl. Didn't test the patched bcrypt-ztex yet.

**Comment by solardiz** [comment] 2020-11-01 19:48
Also tested the patched bcrypt-ztex. Closing.

**Closed as completed by solardiz** 2020-11-01 19:48 UTC
Labels: bug

**Comment by magnumripper** [comment] 2020-11-02 19:25
> I figured this out - this format misses `FMT_TRUNC`

Wow. Good thing we have that self-test now
