### ISSUE TITLE
Old zip file does not produce hash

### ISSUE THREAD

**Issue by erikdj** [openwall/john#4164] opened 2019-11-25 19:52 UTC
### Steps to reproduce ###
- Zip2John produces the following output:
ver 2.0 crazy.zip/my list.txt PKZIP Encr: cmplen=0, decmplen=1033, crc=68B4A057
crazy.zip/my list.txt:$pkzip2$1*1*2*0*0*409*68b4a057*4*29*8*0*68b4*58ef**$/pkzip2$:my list.txt:crazy.zip::/tmp/crazy.zip

- No hash is produced from this file.

The archive appears valid and tests fine:
unzip -v /tmp/crazy.zip
Archive:  /tmp/crazy.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    1033  Defl:N      486  53% 1997-07-23 11:07 68b4a057  my list.txt
--------          -------  ---                            -------
    1033              486  53%                            1 file

### System configuration ###
- zipdetails on the file:
 $ zipdetails ~/Downloads/crazy.zip
0000 PREFIX DATA           PK00

0004 LOCAL HEADER #1       04034B50
0008 Extract Zip Spec      14 '2.0'
0009 Extract OS            00 'MS-DOS'
000A General Purpose Flag  0009
     [Bit  0]              1 'Encryption'
     [Bits 1-2]            1 'Maximum Compression'
     [Bit  3]              1 'Streamed'
000C Compression Method    0008 'Deflated'
000E Last Mod Time         22F758EF 'Wed Jul 23 11:07:30 1997'
0012 CRC                   68B4A057
0016 Compressed Length     00000000
001A Uncompressed Length   00000409
001E Filename Length       000B
0020 Extra Length          0000
0022 Filename              'my list.txt'
002D PAYLOAD

021F STREAMING DATA HEADER 08074B50
0223 CRC                   68B4A057
0227 Compressed Length     000001F2
022B Uncompressed Length   00000409

022F CENTRAL HEADER #1     02014B50
0233 Created Zip Spec      14 '2.0'
0234 Created OS            00 'MS-DOS'
0235 Extract Zip Spec      14 '2.0'
0236 Extract OS            00 'MS-DOS'
0237 General Purpose Flag  0009
     [Bit  0]              1 'Encryption'
     [Bits 1-2]            1 'Maximum Compression'
     [Bit  3]              1 'Streamed'
0239 Compression Method    0008 'Deflated'
023B Last Mod Time         22F758EF 'Wed Jul 23 11:07:30 1997'
023F CRC                   68B4A057
0243 Compressed Length     000001F2
0247 Uncompressed Length   00000409
024B Filename Length       000B
024D Extra Length          0000
024F Comment Length        0000
0251 Disk Start            0000
0253 Int File Attributes   0001
     [Bit 0]               1 Text Data
0255 Ext File Attributes   81B60020
     [Bit 5]               Archive
0259 Local Header Offset   00000004
025D Filename              'my list.txt'

0268 END CENTRAL HEADER    06054B50
026C Number of this disk   0000
026E Central Dir Disk no   0000
0270 Entries in this disk  0001
0272 Total Entries         0001
0274 Size of Central Dir   00000039
0278 Offset to Central Dir 0000022F
027C Comment Length        0000
Done
- `$ ./john --list=build-info`.
Version: 1.9.0-jumbo-1
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.2.0
GNU libc version: 2.29 (loaded: 2.29)
Crypto library: OpenSSL
OpenSSL library version: 01010103f
OpenSSL 1.1.1c  28 May 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by magnumripper** [comment] 2019-11-26 21:14
`cmplen=0` means zip2john thinks the compressed length is zero which is obviously not correct. I expect this to be a dupe of #4063 and/or #4054.

**Comment by magnumripper** [comment] 2019-11-26 21:17
The `[Bit 3] 1 'Streamed'` also points to #4054 BTW

**Comment by erikdj** [comment] 2019-11-26 21:30
> `cmplen=0` means zip2john thinks the compressed length is zero which is obviously not correct. I expect this to be a dupe of #4063 and/or #4054.

More likely #4063. This file was created in 1997.  It's not as likely it was AES back then. ZipCrypto is more likely.

**Comment by magnumripper** [comment] 2020-03-04 17:52
I'm hoping this was fixed with #4207

**Comment by magnumripper** [comment] 2020-04-01 17:25
Closing bc wo

**Closed as completed by magnumripper** 2020-04-01 17:25 UTC
Labels: fixed - pending verify
