### ISSUE TITLE
Support for KDBX

### ISSUE THREAD

**Issue by SO-InformationTECH** [openwall/john#5159] opened 2022-06-07 22:19 UTC
I am attempting to use Keepass2John to crack a KDBX file from a KeePass database that I forgot the password to.

The error I'm receiving states that "version 40001 is currently not supported". I am assuming this is because the software has not been updated to work with the new KDBX 4.1 version
![Command Line KDBX](https://user-images.githubusercontent.com/107079901/172492485-17d8670c-49e0-4bfe-921d-4a3a4d2e9550.png)
The image above is the command I am running. I have searched the internet extensively and found no reliable information about potential ways to extract this files hash.

**Comment by SO-InformationTECH** [comment] 2022-06-07 22:20
I forgot to mention, I am running Kali Linux on a VirtualBox VM.

**Comment by solardiz** [comment] 2022-06-08 06:28
@SO-InformationTECH You're correct - this is currently unsupported. We already have #5097 for the desirable enhancement, so I'm closing this new issue as a duplicate of that one.

**Closed as completed by solardiz** 2022-06-08 06:28 UTC
Labels: dupe, question
