### ISSUE TITLE
ERROR: make -sj4 (creating secp256k1.a / Dynamic / Dynamic_func) install-windows file

### ISSUE THREAD

**Issue by Skynzor** [openwall/john#4857] opened 2021-10-30 20:24 UTC
**Story:**

Followed the INSTALL-WINDOWS file.
Had to install a couple more packages like Make and GCC (C compiler) that were not presented in the INSTALL-WINDOWS file.

Tried Cygwinx86 and Cygwinx86_64 build, both threw the same error on package " Secp256k1.a " after command: 
`_./configure && make -s clean && make -sj4_ .`

**System:** Windows 10 Pro (Version: 21H1)
**Architecture:** x64

**Steps:**

1. Installed latest Cygwinx86_64 and Cygwinx86 build
2. Downloaded latest john-bleeding-jumbo
3. Installed required packages

_Packages mentioned in INSTALL-WINDOWS file:_ 
libssl-devel , libbz2-devel , libgmp-devel , zlib-devel , libOpenCL-devel, libcrypt-devel

_Packages I installed manually after running into John errors:_

make , gcc-core

4. Did everything with CMD / Cygwin terminal with admin privileges

**The error:**

```
ar: creating aes.a **successful**
ar: creating poly1305-donna.a **successful**
ar: creating ed25519-donna.a **successful**

ar: creating secp256k1.a **error**
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_fmt.o: in function  crypt_all':
/cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:1701: undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:1703: undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:1758: undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_append_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:1760: undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_append_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_fmt.o: in function  isKECCAKFunc':
/cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_append_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_append_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_append_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_append_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7315: undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_fmt.o: in function  isLargeHashFinalFunc':
/cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7331: undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7332: undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7332: undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:7332: undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x101e4): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_append_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x101ec): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_append_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x101f4): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_at_offset_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x101fc): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_at_offset_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10204): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_at_offset_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1020c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_at_offset_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10214): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1021c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10224): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1022c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10234): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1023c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10244): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output3'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1024c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output4'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10254): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1025c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10264): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output3'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1026c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output4'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10274): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1027c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10324): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_append_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1032c): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_append_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10334): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_at_offset_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1033c): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_at_offset_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10344): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_at_offset_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1034c): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_at_offset_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10354): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1035c): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10364): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1036c): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_overwrite_input1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10374): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1037c): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10384): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output3'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1038c): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output4'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x10394): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output1'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x1039c): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x103a4): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output3'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x103ac): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output4'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x103b4): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_parser.o:dynamic_parser:(.rdata+0x103bc): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x50a4): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_append_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x50ac): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x50c0): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x50d4): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x50e4): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x50f0): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x50f4): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x50fc): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5100): undefined reference to  DynamicFunc__KECCAK_384_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5114): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5128): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5130): undefined reference to  DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5804): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_append_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x580c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5820): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5834): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5844): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5850): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5854): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x585c): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_overwrite_input2'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5860): undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5874): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5888): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x5890): undefined reference to  DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:596: ../run/john.exe] Error 1
make: *** [Makefile:190: default] Error 2```

**Comment by Slawka** [comment] 2021-11-01 12:26
Duplicate of #4856

**Comment by solardiz** [comment] 2021-11-01 12:37
> ar: creating secp256k1.a **error**
> /usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: dynamic_fmt.o: in function  crypt_all':
> /cygdrive/c/Users/Username/Downloads/john-bleeding-jumbo/src/dynamic_fmt.c:1701: undefined reference to  DynamicFunc__KECCAK_224_crypt_input2_overwrite_input1'

While the error message appears after `ar: creating secp256k1.a`, it has nothing to do with that command (which I guess succeeds without other messages). The error messages appear when compiling `dynamic_fmt.c`.

I'd suspect some local issue on one machine or with following build instructions, however we got @Slawka's report of what looks like the same issue at almost the same time. So I guess something changed perhaps in recent Cygwin causing this?

I'll close this issue as it's a duplicate of the one @Slawka opened earlier. Let's proceed to figure this out on that one.

**Closed as completed by solardiz** 2021-11-01 12:37 UTC
Labels: dupe

**Comment by solardiz** [comment] 2021-11-02 19:48
@Skynzor Discussion did proceed on the other issue - you'll probably want to subscribe to it.

**Comment by Skynzor** [comment] 2021-11-04 14:03
> @Skynzor Discussion did proceed on the other issue - you'll probably want to subscribe to it.

Thank you for letting me know 👍
