### ISSUE TITLE
no opencl devices

### ISSUE THREAD

**Issue by ghost** [openwall/john#4327] opened 2020-08-30 11:32 UTC
Hello everyone,

I have a disk which is locked with bitlocker and I went throught this proces but I'm stuck at the phase where I want to attack the hash. As you can see at the first picture I've the error "no opencl devices  found" while I installed nvidia cuda which gives you the possibility to program in opencl and I checked it in the drivers of the card which you can see on the second photo.  I've tried it already on a pc with a Quadro P2000 and a pc with a Quadro P4000 but all 3 devices give this same error. 

Image 1
![image](https://user-images.githubusercontent.com/47211800/91657319-5b9f2c00-eac0-11ea-91ca-3655db896d40.png)
Image 2
![image](https://user-images.githubusercontent.com/47211800/91657191-7d4be380-eabf-11ea-81cb-b8daf821de3a.png)

Any help would be appreciated.
Jonathan Bernaerts

**Comment by solardiz** [comment] 2020-08-30 21:44
I guess this will help, like it usually does in such cases:

https://github.com/magnumripper/JohnTheRipper/issues/3191#issuecomment-639818020

Copy OpenCL.dll installed in C:\Windows\System32 to JtR's run directory, and rename it to cygOpenCL-1.dll.

I'll close this as duplicate of #3191 for now, unless shown otherwise.

Please note that our use of GitHub is primarily to track issues for us to fix in JtR, not to provide user support. We have the john-users mailing list for the latter.

**Closed as completed by solardiz** 2020-08-30 21:44 UTC
Labels: dupe
