### ISSUE TITLE
Undefined reference to DynamicFunc__* without Perl

### ISSUE THREAD

**Issue by Slawka** [openwall/john#4856] opened 2021-10-30 16:21 UTC
```
`/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:/cygdrive/c/cygwin64/john-bleeding-jumbo/src/dynamic_preloads.c:3168: undefined reference to `DynamicFunc__KECCAK_384_crypt_input1_overwrite_input2'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x7108): undefined reference to `DynamicFunc__KECCAK_384_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x7138): undefined reference to `DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x7178): undefined reference to `DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:/cygdrive/c/cygwin64/john-bleeding-jumbo/src/dynamic_preloads.c:3168: undefined reference to `DynamicFunc__KECCAK_384_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x7f28): undefined reference to `DynamicFunc__KECCAK_224_crypt_input1_append_input2'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x7f38): undefined reference to `DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x7f78): undefined reference to `DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x7fb8): undefined reference to `DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x7ff0): undefined reference to `DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x8008): undefined reference to `DynamicFunc__KECCAK_224_crypt_input1_overwrite_input2'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x8010): undefined reference to `DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:/cygdrive/c/cygwin64/john-bleeding-jumbo/src/dynamic_preloads.c:3120: undefined reference to `DynamicFunc__KECCAK_224_crypt_input1_overwrite_input2'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x8028): undefined reference to `DynamicFunc__KECCAK_224_crypt_input2_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x8058): undefined reference to `DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:dynamic_preloa:(.data+0x8098): undefined reference to `DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: dynamic_preloads.o:/cygdrive/c/cygwin64/john-bleeding-jumbo/src/dynamic_preloads.c:3120: undefined reference to `DynamicFunc__KECCAK_224_crypt_input1_to_output1_FINAL'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1462: ../run/john.exe] Error 1
make: *** [Makefile:190: default] Error 2
`
```
Windows 10
I suspect there is no package, but there is no link in the description

**Comment by solardiz** [comment] 2021-11-01 12:41
Also reported in #4857. My current best guess is something changed in Cygwin causing this. If the issue is a Cygwin bug, then hopefully it'll be gone soon, but regardless we might want to look into it ourselves, too. @jfoug @claudioandre-br Maybe you?

**Comment by Slawka** [comment] 2021-11-01 13:57
cygwin64 3.3.1(0.341/5/3)

**Comment by ghost** [comment] 2021-11-01 18:46
Perl is not installed (probably).

We should remove or update `INSTALL-WINDOWS`.

As a side note: Cygwin 3.3.0 is the last version supporting 32 bit Windows versions.

So, this is another reason to create a release soon. 
* It will be more difficult to build a 32-bit Windows package in the near future.
*****
It works:
```
$ uname -r
3.3.1(0.341/5/3)
```
```
$ date
Mon Nov  1 15:44:59 -03 2021
```
```
$ ../run/john
John the Ripper 1.9.0-jumbo-1+bleeding-3590ef9b93 2021-10-29 19:03:29 +0200 OMP [cygwin 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2021 by Solar Designer and others
Homepage: https://www.openwall.com/john/

Usage: john [OPTIONS] [PASSWORD-FILES]
```

**Comment by magnumripper** [comment] 2021-11-01 19:12
Good catch @claudioandre-br. Is `INSTALL-WINDOWS` good except for that?

If so, this should be committed:
```diff
diff --git a/doc/INSTALL-WINDOWS b/doc/INSTALL-WINDOWS
index 57cb27bef..bb3b380fc 100644
--- a/doc/INSTALL-WINDOWS
+++ b/doc/INSTALL-WINDOWS
@@ -20,6 +20,7 @@ system.
       - C:\cygwin64\setup-x86_64.exe -q -P libssl-devel -P libbz2-devel
       - C:\cygwin64\setup-x86_64.exe -q -P libgmp-devel -P zlib-devel
       - C:\cygwin64\setup-x86_64.exe -q -P libOpenCL-devel -P libcrypt-devel
+      - C:\cygwin64\setup-x86_64.exe -q -P perl
 
     - Open a CygWin terminal. To do that, inside the Command Prompt, type:
       - C:\cygwin64\bin\bash
```

**Comment by magnumripper** [comment] 2021-11-01 19:20
While at it, we might want to add libpcap-devel as well (is that the correct name?).

**Comment by ghost** [comment] 2021-11-01 19:27
I think the name is `perl-base`, but I'm not sure. pcap is worse, I think you should use a port like `winpcap`.

**Comment by Slawka** [comment] 2021-11-01 21:45
Perl installed
x86
x86_64
make bad

**Comment by ghost** [comment] 2021-11-02 14:44
I can reproduce the error without `perl` and fix it with `perl`. Please, try to `make distclean; ./configure && make` again.

The `dynamic_*` error is related to the message below (seen during the build process):
``` 
./dynamic_big_crypt_generator.sh: line 7: perl: command not found
``` 

Run this script manually is also a fix (actually, i just did this plus a `make`).

If you need more help, I'm afraid something is wrong in your environment and you need to debug and provide more details. I tested it inside a VM. At the very least, I believe you will be able to create binaries within a VM and use them on your host machine.

BTW: I did this:

```
> setup-x86_64.exe -q -P libssl-devel -P libbz2-devel perl
> setup-x86_64.exe -q -P libgmp-devel -P zlib-devel
> setup-x86_64.exe -q -P libOpenCL-devel -P libcrypt-devel
> setup-x86_64.exe -q --packages=make
> setup-x86_64.exe -q --packages=perl
```

PS:  CI is also happy after magnum's most recent commit. 

In fact, using the prebuilt package is always a best practice (no one here uses Windows, we don't know what is happening in the Windows world).

**Comment by ghost** [comment] 2021-11-02 15:12
See https://github.com/openwall/john-packages/issues/16

**Comment by Slawka** [comment] 2021-11-02 17:45
`make distclean && ./configure && make -s clean && make -sj4`


```
zed_fmt_plug.c:135:25: note: referencing argument 4 of type ‘const unsigned char **’
zed_fmt_plug.c:135:25: warning: ‘pkcs12_pbe_derive_key_simd’ accessing 26880 bytes in a region of size 32 [-Wstringop-overflow=]
zed_fmt_plug.c:135:25: note: referencing argument 5 of type ‘size_t *’ {aka ‘long unsigned int *’}
zed_fmt_plug.c:135:25: warning: ‘pkcs12_pbe_derive_key_simd’ accessing 26880 bytes in a region of size 32 [-Wstringop-overflow=]
zed_fmt_plug.c:135:25: note: referencing argument 8 of type ‘unsigned char **’
In file included from zed_fmt_plug.c:30:
pkcs12.h:54:5: note: in a call to function ‘pkcs12_pbe_derive_key_simd’
   54 | int pkcs12_pbe_derive_key_simd( int md_type, int iterations, int id, const unsigned char *pwd[SIMD_MAX_GROUP_PFX],
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
Securing executables.

Make process completed.
```

**All Ok**

**Comment by solardiz** [comment] 2021-11-02 19:47
@Slawka In your previous attempts, did you possibly install Perl not right away, but after having run `./configure`?

> The `dynamic_*` error is related to the message below (seen during the build process):
> 
> ```
> ./dynamic_big_crypt_generator.sh: line 7: perl: command not found
> ```

When this happens, does the build continue anyway (until failing later)? If so, maybe that's something we should fix - have this shell script exit non-zero and the build stop there?

**Comment by ghost** [comment] 2021-11-02 20:05
> When this happens, does the build continue anyway (until failing later)?

Yes. I saw the `perl` error message and, later, the linking issue.

**Comment by Slawka** [comment] 2021-11-02 21:00
> 
> 
> @Slawka In your previous attempts, did you possibly install Perl not right away, but after having run `./configure`?
> 
> > The `dynamic_*` error is related to the message below (seen during the build process):
> > ```
> > ./dynamic_big_crypt_generator.sh: line 7: perl: command not found
> > ```
> 
> When this happens, does the build continue anyway (until failing later)? If so, maybe that's something we should fix - have this shell script exit non-zero and the build stop there?

Yes,   I ran `./configure && make -s clean && make -sj4` saw errors perl, installed perl and started again `./configure && make -s clean && make -sj4`

**Comment by solardiz** [comment] 2021-11-02 21:11
A  broken `dynamic_big_crypt.c` shouldn't be left around if `dynamic_big_crypt_generator.sh` fails. We already have the below at the beginning of this script:

```sh
rm -f dynamic_big_crypt.c
perl ./dynamic_big_crypt_chopper.pl TEST || exit 1
```

and this at its end:

```sh
mv xxx dynamic_big_crypt.c
```

So it looks like without `perl`, we shouldn't have created that file. Is this somehow not working? Or does the build somehow proceed to those link errors even without a `dynamic_big_crypt.c` (isn't it a required dependency per the generated `Makefile`)?

**Comment by Skynzor** [comment] 2021-11-05 15:26
I downloaded the zip John-bleed-jumbo again, just in case and unpacked it. Installed **_Perl_** on the 32bit through Cygwin installer. And then went to \src folder through Cygwin Bash. And when running the command `./configure && make -s clean && make -sj4`, I got the confirmation it worked.

So if anyone else is catching this error, install these packages (tested on x86 cygwin, not on x64):

1. libssl-devel
2. libbz2-devel
3. libgmp-devel
4. zlib-devel
5. libOpenCL-devel
6. libcrypt-devel
7. gcc-core
8. libgcc1
9. make
10. Perl

If any of these packages were missing, I couldn't run command: `./configure && make -s clean && make -sj4`
Or I couldn't run command: `make windows-package`

I'm running command: `..\run\john --test` now, will keep you updated how that's going.

**Comment by Skynzor** [comment] 2021-11-08 07:59
`..\run\john --test` worked, but `..\run\john --test=0` threw an error. Can't replicate it today as i'm not at my workstation.

**Comment by magnumripper** [comment] 2021-11-08 11:44
> `..\run\john --test` worked, but `..\run\john --test=0` threw an error

Sounds like an intermittent problem. Try running `..\run\john --test=0` many times.

**Comment by solardiz** [comment] 2021-11-10 15:25
After @magnumripper's documentation update, I think the remaining task here is to figure out (and if reasonable fix) why the build got that far without Perl installed, instead of erroring out earlier (I think it should, as that would probably reduce the confusion).

**Closed as completed** 2021-11-11 13:23 UTC
Labels: maintenance/cleanup, documentation
