### ISSUE TITLE
gpg2john internal error with symmetrically encrypted files above approximately 90000 bytes

### ISSUE THREAD

**Issue by jasoncarr0** [openwall/john#4720] opened 2021-05-09 22:45 UTC
The current version of gpg2john

Bad parameter: give(len=216277, buf=0x1ccb280, buf_size=90000), len can not be bigger than buf_size.

The issue appears to be that the buffer is a fixed size: https://github.com/openwall/john/blob/bleeding-jumbo/src/gpg2john.c#L143

### Steps to reproduce ###

Pass a large symmetrically-encrypted zip file to `gpg2john`. The smallest of mine was 212K which was still too large.

If the size is smaller than the 90,000 bytes, there is no issue. When I re-compiled the latest release, updating that previously linked size to be greater than the expected size, it worked without issue.

### System configuration ###
Attach details about your OS and about JtR, including:
- `$ ./john --list=build-info`.
[john-build-info.txt](https://github.com/openwall/john/files/6448556/john-build-info.txt)
- `$ ./john --list=opencl-devices` (if applicable).
[john-devices.txt](https://github.com/openwall/john/files/6448555/john-devices.txt)

**Comment by ghost** [comment] 2021-05-10 00:14
I'll close this as duplicate of #4631. Please post your comments there if you have anything new to add..

**Closed as completed by ghost** 2021-05-10 00:14 UTC
Labels: dupe

**Comment by jasoncarr0** [comment] 2021-05-10 01:01
Sorry about that @claudioandre-br
