### ISSUE TITLE
bcrypt problem with $2a vs. $2b handling

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4388] opened 2020-09-30 13:37 UTC
I opened https://github.com/openwall/john-tests/issues/88 and started to investigate. It's actually a format quirk, not a TS shortcoming, and I realized I've scratched my head over it before. I'm pretty sure it's reproducible with John Proper. Perhaps this problem is not likely to surface IRL though. Like I said, it's about `$2a` vs. `$2b` (I had a faint memory of looking into it long ago).

Here's the full input file (TS assembled it from format's test vectors along with a corresponding wordlist)
```
$ cat tst-.in 
vec_0:$2a$05$CCCCCCCCCCCCCCCCCCCCC.E5YPO9kmyuRGyh0XouQYb4YMJKvyOeW
vec_1:$2a$05$CCCCCCCCCCCCCCCCCCCCC.VGOzA784oUp/Z0DY336zx7pLYAy0lwK
vec_2:$2a$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a
vec_3:$2a$05$CCCCCCCCCCCCCCCCCCCCC.7uG0VCzI2bS7j6ymqJi9CdcdxiRTWNy
vec_4:$2a$05$abcdefghijklmnopqrstuu5s2v8.iXieOjg/.AySBTTZIIVFJeBui
vec_5:$2x$05$/OK.fbVrR/bpIqNJ5ianF.CE5elHaaO4EbggVDjb8P19RukzXSM3e
vec_6:$2y$05$/OK.fbVrR/bpIqNJ5ianF.Sa7shbm4.OzKpvFnX1pQLmQW96oUlCq
vec_7:$2x$05$6bNw2HLQYeqHYyBfLMsv/OiwqTymGIGzFsA4hOTWebfehXHNprcAS
vec_8:$2x$05$6bNw2HLQYeqHYyBfLMsv/O9LIGgn8OMzuDoHfof8AQimSGfcSWxnS
vec_9:$2a$05$/OK.fbVrR/bpIqNJ5ianF.swQOIzjOiJ9GHEPuhEkvqrUyvWhEMx6
vec_10:$2a$05$/OK.fbVrR/bpIqNJ5ianF.R9xrDjiycxMbQE2bp.vgqlYpW5wx2yy
vec_11:$2a$05$CCCCCCCCCCCCCCCCCCCCC.7uG0VCzI2bS7j6ymqJi9CdcdxiRTWNy
vec_12:$2a$05$/OK.fbVrR/bpIqNJ5ianF.9tQZzcJfm3uj2NvJ/n5xkhpqLrMpWCe
vec_13:$2b$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a
```
Note that vec_2 and vec_13 are same hash but different prefix.

The wordlist is also made by TS from the test vectors, along with some distraction extras for exercising the format.

Reproducing manually (using the commands `./jtrts.pl bcrypt -internal -stoponerror` gave me):
```
$ rm -f tst-.pot && ../run/john -ses=tst-  -skip -pot=tst-.pot tst-.in --wordlist=tst-.dic -form=bcrypt
Using default input encoding: UTF-8
Loaded 13 password hashes with 6 different salts (2.2x same-salt boost) (bcrypt [Blowfish 32/64 X3])
Cost 1 (iteration count) is 32 for all loaded hashes
Will run 16 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 19 candidates left, minimum 48 needed for performance.
U*U              (vec_0)
U*U*             (vec_1)
                 (vec_3)
                 (vec_3)
U*U*U            (vec_13)
U*U*U            (vec_2)
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 (vec_4)
?                (vec_5)
?                (vec_6)
???????????????????????????????????????????????????????????????????????? (vec_9)
?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U (vec_10)
U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??               (vec_12)
??????              (vec_8)
ё                (vec_7)
14g 0:00:00:00 DONE (2020-09-30 14:42) 700.0g/s 950.0p/s 5700c/s 12350C/s 123456789012345678901234567890123456789012345678901234567890123456789012..U*U*U
No remaining hashes
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed. 
```
Note that `vec_2` is reported above, cracked as `U*U*U` (just like `vec_13`).
The fact `vec_3` is reported twice and `vec_11` is not reported is because they're having the same exact hash, including prefix. That's a known problem and will be correct with `--show`. Things are not as well with `vec_2` though:
```
$ ../run/john -show   -pot=tst-.pot tst-.in -form=bcrypt
vec_0:U*U
vec_1:U*U*
vec_3:
vec_4:0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
vec_5:?
vec_6:?
vec_7:ё
vec_8:??????
vec_9:????????????????????????????????????????????????????????????????????????
vec_10:?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U?U
vec_11:
vec_12:U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??U??
vec_13:U*U*U

13 password hashes cracked, 1 left
```
Now, `vec_2` is missing even though it was reported.

```
$ grep -F 'U*U*U' tst-.pot 
$2b$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a:U*U*U
```
Right, it's not in there with `$2a`.

A second run cracks the last hash:
```
$ ../run/john -ses=tst-  -skip -pot=tst-.pot tst-.in --wordlist=tst-.dic -form=bcrypt
Using default input encoding: UTF-8
Loaded 13 password hashes with 6 different salts (2.2x same-salt boost) (bcrypt [Blowfish 32/64 X3])
Warning: invalid UTF-8 seen reading tst-.pot
Remaining 1 password hash
Cost 1 (iteration count) is 32 for all loaded hashes
Will run 16 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 19 candidates left, minimum 48 needed for performance.
U*U*U            (vec_2)
1g 0:00:00:00 DONE (2020-09-30 15:06) 100.0g/s 1900p/s 1900c/s 1900C/s 123456789012345678901234567890123456789012345678901234567890123456789012..U*U*U
No remaining hashes
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed. 
```
```
$ grep -F 'U*U*U' tst-.pot 
$2b$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a:U*U*U
$2a$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a:U*U*U
```

**Comment by solardiz** [comment] 2020-09-30 13:50
> The fact `vec_3` is reported twice and `vec_11` is not reported is because they're having the same exact hash, including prefix.

This explains why `vec_11` isn't even loaded (except in single or batch mode or with dupe checking disabled), but it does not explain why `vec_3` is reported twice. That's a bug. Also, the final `14g` is a result of that bug (should be `13g`). I suspect those are jumbo bugs, not core. Can you reproduce any of this on core? I started experimenting, and so far I can't.

**Comment by solardiz** [comment] 2020-09-30 13:53
I also guess the problem isn't specific to bcrypt, nor to its different prefixes. `vec_3` and `vec_11` have literally the same hash string, including the same prefix. I guess the bug is in some shared code, not format-specific.

**Comment by magnumripper** [comment] 2020-09-30 13:55
OK but the vec3/vec11 is (I think) a separate problem. I'll try with John Proper now.

**Comment by solardiz** [comment] 2020-09-30 13:56
OK, maybe two bugs here.

**Comment by magnumripper** [comment] 2020-09-30 14:10
~This issue (the vec_2) is~ Both issues are present in John Proper as well. I'll open a new issue for vec3/vec11 ~which is, like you say, a Jumbo bug~.

**Comment by solardiz** [comment] 2020-09-30 14:14
> This issue (the vec_2) is present in John Proper as well.

Confirmed. I'll look into that.

**Comment by magnumripper** [comment] 2020-09-30 20:21
John proper doesn't even seem to have that second (`$2b$`) test vector for `U*U*U`. I tested it using the files generated from Jumbo's test vectors.

**Comment by solardiz** [comment] 2020-10-30 00:32
We should be able to fix the issue for bcrypt by unifying the hash variations in `split`, but the issue is really not limited to just bcrypt. Here's a test case using invalid descrypt salt (yet supported by some systems and by JtR):

```
!!5bgZuCO.hxM
nn5bgZuCO.hxM
```

```
$ ./john pw-des
Loaded 2 password hashes with no different salts (descrypt, traditional crypt(3) [DES 128/128 SSE2])
Will run 4 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
test             (?)
test             (?)
2g 0:00:00:01 100% 2/3 1.307g/s 10708p/s 10708c/s 21416C/s 123456..betabeta
Use the "--show" option to display all of the cracked passwords reliably
Session completed
$ cat john.pot 
nn5bgZuCO.hxM:test
$ ./john pw-des -sho
?:test

1 password hash cracked, 1 left
$ ./john pw-des
Loaded 2 password hashes with no different salts (descrypt, traditional crypt(3) [DES 128/128 SSE2])
Remaining 1 password hash
Will run 4 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
test             (?)
1g 0:00:00:01 100% 2/3 0.6060g/s 9929p/s 9929c/s 9929C/s 123456..betabeta
Use the "--show" option to display all of the cracked passwords reliably
Session completed
$ ./john pw-des
Loaded 2 password hashes with no different salts (descrypt, traditional crypt(3) [DES 128/128 SSE2])
No password hashes left to crack (see FAQ)
$ ./john pw-des -sho
?:test
?:test

2 password hashes cracked, 0 left
```

**Comment by solardiz** [comment] 2020-10-30 17:46
@magnumripper @claudioandre-br Do we even want to fix this issue? And if so, per-format or in shared code? The issue is that on loading we detect matching binary hashes (unless dupe detection is disabled) and matching binary salts, however on "--show" we match source hash pieces (after `split`, but before `binary`). So if a format is such that multiple sources map onto the same binary, we have this issue. We avoid it for varying-case hex-encoded hashes by unifying them in `split`, but we don't yet do anything similar for other format-specific cases as can be seen here for bcrypt and descrypt.

It's fairly easy to fix this in a format-specific way (in `split`) for bcrypt. It's slightly trickier to do that for descrypt (perhaps would need to add a function that would map binary descrypt salts back onto ASCII ones, always producing the canonical ones).

A concern is this will actually break ASCII-based matching on "--show" for some old pot records, which already have non-canonical versions matching what was in the input files. We currently solve this for hex-encoded hashes by also calling `split` on pot file entries when `FMT_SPLIT_UNIFIES_CASE` is set. We'll need something similar, and it'll add similar performance impact.

Worse, our `ldr_cracked_hash` is only ASCII case insensitive. It would produce different hash values for strings that differ in other ways. So we'll need some different or additional trick, which probably means either more of a hack (format-specific logic) or even greater performance impact.

A way to fix this solely in shared code would be reworking that to consistently match either binaries or sources, but not mix the two types of matching. However, that's an invasive change that also has drawbacks.

Overall, I am tempted to mark this WONTFIX.

**Comment by solardiz** [comment] 2020-10-30 17:51
> Worse, our `ldr_cracked_hash` is only ASCII case insensitive. It would produce different hash values for strings that differ in other ways. So we'll need some different or additional trick

We can hack this function to skip the first 2 chars for descrypt and the 3rd char for bcrypt, or to always skip the first 3 chars.

**Comment by solardiz** [comment] 2020-10-30 17:59
Here's yet another test case (behaves the same as the one for descrypt I posted above):

```
_J9..nnnnjJLvT4t85dU
_J9..!!!!jJLvT4t85dU
```

I haven't seen invalid-salt bsdicrypt hashes in the wild, but that might be because bsdicrypt hashes are rare, not because there's anything preventing invalid salts from being used in the wild. The implementation that we have in Owl rejects invalid salts for those hashes, though.

**Comment by solardiz** [comment] 2020-10-30 18:19
For bsdicrypt, I am thinking simply:

```diff
+++ b/src/BSDI_fmt.c
@@ -117,10 +117,7 @@ static int valid(char *ciphertext, struct fmt_main *self)
 
        if (ciphertext[0] != '_') return 0;
 
-       for (pos = &ciphertext[1]; pos < &ciphertext[9]; pos++)
-       if (!*pos) return 0;
-
-       for (pos = &ciphertext[9]; atoi64[ARCH_INDEX(*pos)] != 0x7F; pos++);
+       for (pos = &ciphertext[1]; atoi64[ARCH_INDEX(*pos)] != 0x7F; pos++);
        if (*pos || pos - ciphertext != CIPHERTEXT_LENGTH) return 0;
 
        if (atoi64[ARCH_INDEX(*(pos - 1))] & 3) return 0;
```

For bcrypt, this appears to work, although I expected it to be incomplete:

```diff
diff --git a/src/BF_common.c b/src/BF_common.c
index 4ab3f14..c0799b3 100644
--- a/src/BF_common.c
+++ b/src/BF_common.c
@@ -73,6 +73,7 @@ unsigned char BF_atoi64[0x80] = {
        64, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
        43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 64, 64, 64, 64, 64
 };
+
 int BF_common_valid(char *ciphertext, struct fmt_main *self)
 {
        int rounds;
@@ -99,6 +100,18 @@ int BF_common_valid(char *ciphertext, struct fmt_main *self)
        return 1;
 }
 
+char *BF_common_split(char *ciphertext, int index, struct fmt_main *self)
+{
+       if (ciphertext[2] == 'b' || ciphertext[2] == 'y') {
+               static char out[CIPHERTEXT_LENGTH + 1];
+               strcpy(out, ciphertext);
+               out[2] = 'a';
+               return out;
+       }
+
+       return ciphertext;
+}
+
 /*
  * I'm not doing any error checking in the routines below since the
  * ciphertext should have already been checked to be fmt_BF.valid().
diff --git a/src/BF_common.h b/src/BF_common.h
index a58182d..dc08106 100644
--- a/src/BF_common.h
+++ b/src/BF_common.h
@@ -58,6 +58,7 @@ extern BF_word BF_magic_w[6];
 extern struct BF_ctx BF_init_state;
 
 int BF_common_valid(char *ciphertext, struct fmt_main *self);
+char *BF_common_split(char *ciphertext, int index, struct fmt_main *self);
 void *BF_common_get_binary(char *ciphertext);
 void *BF_common_get_salt(char *ciphertext);
 unsigned int BF_common_iteration_count(void *salt);
diff --git a/src/BF_fmt.c b/src/BF_fmt.c
index a793c72..9d88cb6 100644
--- a/src/BF_fmt.c
+++ b/src/BF_fmt.c
@@ -209,7 +209,7 @@ struct fmt_main fmt_BF = {
                fmt_default_reset,
                fmt_default_prepare,
                BF_common_valid,
-               fmt_default_split,
+               BF_common_split,
                BF_common_get_binary,
                BF_common_get_salt,
                {
```

Somehow this manages to "--show" the correct line even when I patch the `john.pot` line from `a` to `b`. I don't yet understand why - I expected we would be skipping unification of pot entries for non-hex-encoded hashes and would bump into the `ldr_cracked_hash` issue even if we tried.

**Comment by solardiz** [comment] 2020-10-30 18:27
Looks like in jumbo, we may redundantly call `split` twice on pot entries. First here:

```c
/*
 * Jumbo-specific; split() needed for legacy pot entries so we need to
 * enumerate formats and call valid(). This also takes care of the situation
 * where a specific format was requested.
 */
                if (!(options.flags & FLG_MAKECHR_CHK)) {
                        struct fmt_main *format = fmt_list;

                        do {
                                if (ldr_trunc_valid(ciphertext, format) == 1)
                                        break;
                        } while((format = format->next));

                        if (!format)
                                return;

                        ciphertext =
                                format->methods.split(ciphertext, 0, format);
                }
                hash = ldr_cracked_hash(ciphertext);
```

and then here:

```c
/* This extra check, along with ldr_cracked_hash() being case-insensitive,
 * is only needed for matching some pot file records produced by older
 * versions of John and contributed patches where split() didn't unify the
 * case of hex-encoded hashes. */
                        if (unify &&
                            format->methods.valid(pot, format) == 1 &&
                            !strcmp(split(pot, 0, format), piece))
                                break;
```

Perhaps the second call above, coming from core, can be dropped now that jumbo calls `split` when populating the in-memory pot file contents. @magnumripper What do you say?

Anyway, I now have an explanation on why my patch above might actually be sufficient (for bcrypt on CPU): we use `ldr_cracked_hash` on post-`split` strings.

**Comment by solardiz** [comment] 2020-10-30 18:32
I am now thinking:

```diff
+++ b/src/loader.c
@@ -2207,7 +2207,7 @@ static void ldr_show_pw_line(struct db_main *db, char *line)
        char *orig_line = NULL;
        struct fmt_main *format;
        char *(*split)(char *ciphertext, int index, struct fmt_main *self);
-       int index, count, unify;
+       int index, count;
        char *login, *ciphertext, *gecos, *home, *uid;
        char *piece;
        int pass, found, chars;
@@ -2248,7 +2248,6 @@ static void ldr_show_pw_line(struct db_main *db, char *line)
 
        if (format) {
                split = format->methods.split;
-               unify = format->params.flags & FMT_SPLIT_UNIFIES_CASE;
                if (format->params.flags & FMT_UNICODE) {
                        static int setting = -1;
                        if (setting < 0)
@@ -2266,7 +2265,6 @@ static void ldr_show_pw_line(struct db_main *db, char *line)
        } else {
                split = fmt_default_split;
                count = 1;
-               unify = 0;
        }
 
        if (options.target_enc != UTF_8 &&
@@ -2294,8 +2292,6 @@ static void ldr_show_pw_line(struct db_main *db, char *line)
        for (found = pass = 0; pass == 0 || (pass == 1 && found); pass++)
        for (index = 0; index < count; index++) {
                piece = split(ciphertext, index, format);
-               if (unify)
-                       piece = strcpy(mem_alloc(strlen(piece) + 1), piece);
 
                hash = ldr_cracked_hash(piece);
 
@@ -2305,19 +2301,8 @@ static void ldr_show_pw_line(struct db_main *db, char *line)
 
                        if (!ldr_pot_source_cmp(pot, piece))
                                break;
-/* This extra check, along with ldr_cracked_hash() being case-insensitive,
- * is only needed for matching some pot file records produced by older
- * versions of John and contributed patches where split() didn't unify the
- * case of hex-encoded hashes. */
-                       if (unify &&
-                           format->methods.valid(pot, format) == 1 &&
-                           !strcmp(split(pot, 0, format), piece))
-                               break;
                } while ((current = current->next));
 
-               if (unify)
-                       MEM_FREE(piece);
-
                if (pass) {
                        chars = 0;
                        if (show || loop) {
```

This also obsoletes `FMT_SPLIT_UNIFIES_CASE`, so we can drop it from all formats. I had introduced it and the code above in core as an optimization, but if jumbo invokes `split` on pot file entries all the time anyway, we don't need it. Or maybe we need to rename this flag and use it in more formats and then make jumbo's call to `split` in `ldr_show_pot_line` conditional again?

**Comment by solardiz** [comment] 2020-10-30 18:50
> rename this flag and use it in more formats

How about calling it simply `FMT_SPLIT_UNIFIES`?

@magnumripper Would you be able to identify all formats that currently need the logic you(?) added in `ldr_show_pot_line`? If so, set that flag on those formats, and limit the logic to formats with the flag. Then also make use of it for bcrypt and descrypt.

**Comment by solardiz** [comment] 2020-10-31 01:25
BTW, my `FMT_SPLIT_UNIFIES_CASE` logic only worked with an explicit format specified, whereas jumbo's logic goes through the entire list of formats until finding one matching the pot line - and does so for every line (ouch). So jumbo's is much more generic, but also much slower (luckily, only affecting "--show"). Maybe we can speed it up by caching the previous line's format and testing that format's `valid` first rather than always starting from the beginning of the formats list.

Another detail I notice is that jumbo would skip pot lines which no format recognizes. In core, basic string matching works even for unrecognized formats, except when running with explicit "--format". Perhaps this difference is unintentional (looks like it got introduced in 0ceedb24f4941bd06ce56b31398df19aa633a7c1 without being documented), and is easy to fix.

**Comment by solardiz** [comment] 2020-11-01 18:29
> map binary descrypt salts back onto ASCII ones, always producing the canonical ones

This works:

```diff
+++ b/src/DES_fmt.c
@@ -129,8 +129,13 @@ static char *split(char *ciphertext, int index, struct fmt_main *self)
                memcpy(&out[2], &ciphertext[13], 11);
        } else
                memcpy(out, ciphertext, 13);
-
        out[13] = 0;
+
+/* Replace potential invalid salts with their valid counterparts */
+       unsigned int salt = DES_raw_get_salt(out);
+       out[0] = itoa64[salt & 0x3f];
+       out[1] = itoa64[salt >> 6];
+
        return out;
 }
 
```

**Closed as completed** 2020-11-01 19:06 UTC
Labels: core branch, bug

**Comment by magnumripper** [comment] 2020-11-02 19:35
> How about calling it simply `FMT_SPLIT_UNIFIES`?
> 
> @magnumripper Would you be able to identify all formats that currently need the logic you(?) added in `ldr_show_pot_line`? If so, set that flag on those formats, and limit the logic to formats with the flag. Then also make use of it for bcrypt and descrypt.

I think I could, and I think we should do this. I believe this can speed things up considerably in some (many) cases.

> BTW, my `FMT_SPLIT_UNIFIES_CASE` logic only worked with an explicit format specified, whereas jumbo's logic goes through the entire list of formats until finding one matching the pot line - and does so for every line (ouch). So jumbo's is much more generic, but also much slower (luckily, only affecting "--show"). Maybe we can speed it up by caching the previous line's format and testing that format's `valid` first rather than always starting from the beginning of the formats list.

That sounds like a good idea too.

> Another detail I notice is that jumbo would skip pot lines which no format recognizes. In core, basic string matching works even for unrecognized formats, except when running with explicit "--format". Perhaps this difference is unintentional (looks like it got introduced in [0ceedb2](https://github.com/openwall/john/commit/0ceedb24f4941bd06ce56b31398df19aa633a7c1) without being documented), and is easy to fix.

Yes, definitely unintentional.
