### ISSUE TITLE
Problem with dmg-opencl - Gets stuck

### ISSUE THREAD

**Issue by blandyuk** [openwall/john#5341] opened 2023-07-14 07:15 UTC
Noticed john has problems with dmg-opencl as it gets stuck at 0% GPU utilization, but cracking a same iteration count PBKDF2-HMAC-SHA1-opencl hash works.

Environment: Win10

I managed to get it working by using john "1.9.0-jumbo-1 64-bit" and the CUDA Toolkit "cuda_11.2.2_461.33_win10". The CUDA driver is March 2021 as any later, I get kernel compile errors.

I have since got the latest john build and used the October 2022 "cuda_11.8.0_522.06_windows" drivers and no longer get the compile error, but it's very slow at starting and then gets stuck with 0% GPU. The speed is ZERO on john after waiting numerous minutes.

Odd that it's not working. Something not right.

**Comment by solardiz** [comment] 2023-07-14 11:16
Duplicate of #5340. Let's discuss there.

**Closed as completed by solardiz** 2023-07-14 11:16 UTC
Labels: bug, dupe
