### ISSUE TITLE
zip-opencl suboptimal speeds

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4031] opened 2019-06-15 11:46 UTC
As prompted by this Twitter thread:

https://twitter.com/solardiz/status/1139844055100059650

It appears that we have a crucial optimization that hashcat missed, so we appear to be much faster than hashcat at these "non-hashes" now, but while at it I also noticed that:

1. We benchmark for a mix of two different "non-hashes", and the speeds for those differ somewhat. As seen with actual mask mode cracking on GTX 1080, Titan X Maxwell, Titan Kepler, respectively:

`$zip2$*0*1`: 2206K, 1543K, 693K

`$zip2$*0*3`: 1970K, 1415K, 656K

Perhaps we should standardize on the former for our benchmarks, which is what hashcat just did (with a couple of commits today: https://github.com/hashcat/hashcat/commit/f660b95ac6ad30aca8d3540641c2abf4592780a5 https://github.com/hashcat/hashcat/commit/cf3dd5f3db6c3f32f54f01001d1c2c3772831d3a). I think for us this means changing the 0x107 to 0x507. Right?

2. Our `--test` benchmark speeds are a lot higher than what's seen in actual cracking. For example, on GTX 1080 verbose auto-tune and `--test` gives ~2700K, but as we can see above actual cracking is at ~2100K (average for the two test vectors, and is actually seen when I load both for cracking at once). How can we fix and/or explain this?

3. GPU utilization for the faster GPUs is on the order of 85% during cracking. Why is that? Are we still doing much work on host? Can we fix that?

I expect that once hashcat implements the missed optimization, it'll actually be faster than us by at least this missed 15% of GPU utilization.

4. When we compute the 2 bytes of PBKDF2 and occasionally have to (re)compute the rest, perhaps we can skip the PBKDF2 output block that included the 2 bytes? When we compute the 2 bytes of PBKDF2 and occasionally have to (re)compute the rest, perhaps we can skip the PBKDF2 output block that included the 2 bytes _if_ they were part of a block that we need anyway? (We'd need to store the full block, not just the 2 bytes, for that to work.) It appears that the performance cost of the code divergence the full PBKDF2 computation occasionally causes is actually measurable and not entirely negligible. So we'd save time not only for the work-item doing this full computation, but also for its 63 adjacent ones, by having it compute one output block less. But perhaps this would clatter our source code too much? Also, maybe storing the full block would increase register pressure and hurt speeds for the common case in that way. So it's a questionable additional optimization. Just thinking out loud here.

Edit: hashcat just implemented the optimization by going through the PBKDF2 output blocks in reverse order and checking the 2 bytes inside the custom PBKDF2 implementation: https://github.com/hashcat/hashcat/commit/dbbdb7e5ac4f7db2dd503c1820b91fbbcfc37c92

5. When we early-reject a password with the 2 bytes check, which we do most of the time, we end up transferring a bunch of zeroes back to the host. This is wasteful. We might want to introduce a protocol where we'd only transfer actually computed derived keys perhaps tagged with the numbers of the corresponding input passwords.

Off-topic for this issue, but FWIW:

6. Isn't this a violation of aliasing rules:

```c
        if (*(__global ushort*)outbuffer[idx].v ==
            *(__constant ushort*)salt->passverify) {
```

(It would be in C. We need to figure our how it's in OpenCL.)

7. This format fails self-test on Vega 64 with our currently installed driver, whereas older hashcat works fine on the same system. Perhaps we can try and workaround whatever driver(?) bug causes this. Perhaps the same workaround will also help several other formats.

**Comment by solardiz** [comment] 2019-06-15 15:36
Apparently, the `--test` benchmark and auto-tune speed difference came from the latency of transferring data from/to host, which at ~2M c/s is far from negligible. That latency is mostly avoided in "Many salts" benchmarks, but it's fairly unlikely someone will be cracking that many archives at once ("Many salts" assumes 256).

When preparing for the 1.9.0-jumbo-1 release, we set our "Raw" benchmarks to correspond to "Many salts" rather than "Only one salt". We did this for easy `relbench` against 1.8.0-jumbo-1. In hindsight, maybe we should have done that only in the 1.8 legacy benchmarks mode, leaving 1.9 core's new default of having "Raw" correspond to "Only one salt" intact. Maybe we should fix that for next release, but then we also need to introduce 1.9.0-jumbo-1 legacy benchmarks for further `relbench` runs.

Making this explicit:

```
[solar@super run]$ git diff
diff --git a/src/opencl_zip_fmt_plug.c b/src/opencl_zip_fmt_plug.c
index 49fb644..c4a6e9c 100644
--- a/src/opencl_zip_fmt_plug.c
+++ b/src/opencl_zip_fmt_plug.c
@@ -403,7 +403,7 @@ struct fmt_main fmt_opencl_zip = {
                FORMAT_NAME,
                ALGORITHM_NAME,
                WINZIP_BENCHMARK_COMMENT,
-               WINZIP_BENCHMARK_LENGTH,
+               WINZIP_BENCHMARK_LENGTH & ~0x100U,
                0,
                PLAINTEXT_LENGTH,
                WINZIP_BINARY_SIZE,
[solar@super run]$ ./john -test -form=zip-opencl -dev=4
Device 4: GeForce GTX 1080
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]... DONE
Many salts:	2672K c/s real, 2521K c/s virtual, Dev#4 util: 85%
Only one salt:	2160K c/s real, 2077K c/s virtual
```

Maybe we should do that for now, since it does make some sense that someone might be cracking more than 1 archive at once and would get an inbetween speed.

I also tried duplicating the first test vector in `pkzip.c`, so that both salts alternated in the "Many salts" benchmark are of the same type. I expected this would very slightly improve the speed, but somehow I got the opposite:

```
[solar@super run]$ ./john -test -form=zip-opencl -dev=4
Device 4: GeForce GTX 1080
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]... DONE
Many salts:	2641K c/s real, 2469K c/s virtual, Dev#4 util: 84%
Only one salt:	2129K c/s real, 2009K c/s virtual

[solar@super run]$ ./john -test -form=zip-opencl -dev=4
Device 4: GeForce GTX 1080
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]... DONE
Many salts:	2625K c/s real, 2502K c/s virtual, Dev#4 util: 85%
Only one salt:	2140K c/s real, 2038K c/s virtual
```

**Comment by solardiz** [comment] 2019-06-15 15:52
magnum, why are we seeing "85%" next to "Many salts" here, whereas we're getting "99%" next to "Many salts" e.g. for the faster md5crypt-opencl format? -

```
[solar@super run]$ ./john -test -form=md5crypt-opencl -dev=4 
Device 4: GeForce GTX 1080
Benchmarking: md5crypt-opencl, crypt(3) $1$ [MD5 OpenCL]... DONE
Warning: "Many salts" test limited: 15/256
Many salts:	9544K c/s real, 9544K c/s virtual, Dev#4 util: 99%
Only one salt:	8113K c/s real, 8113K c/s virtual
```

Does zip-opencl involve many times larger data transfers to/from host? Maybe, but I guess not to that extent. And this gave me another thought - zip-opencl auto-tunes to GWS=10240, which is much lower than md5crypt-opencl's GWS=327680. Using the latter (and with only the patch above, no `pkzip.c` test vector duplication), I got:

```
[solar@super run]$ GWS=327680 ./john -test -form=zip-opencl -dev=4 -v=4
Device 4: GeForce GTX 1080
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]...  
Local worksize (LWS) 640, global worksize (GWS) 327680 (512 blocks)
DONE
Warning: "Many salts" test limited: 9/256
Many salts:	2808K c/s real, 2564K c/s virtual, Dev#4 util: 94%
Only one salt:	2730K c/s real, 2520K c/s virtual
```

or even better:

```
[solar@super run]$ GWS=655360 ./john -test -form=zip-opencl -dev=4 -v=4
Device 4: GeForce GTX 1080
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]...  
Local worksize (LWS) 640, global worksize (GWS) 655360 (1024 blocks)
DONE
Warning: "Many salts" test limited: 5/256
Many salts:	2978K c/s real, 2753K c/s virtual, Dev#4 util: 97%
Only one salt:	2824K c/s real, 2642K c/s virtual
```

So we can improve speeds a lot, especially for "Only one salt", by simply using higher GWS. I guess this emphasizes that our auto-tuning needs further improvements, as discussed on another issue, to include more of the format's methods used during actual cracking in its time measurements.

**Comment by solardiz** [comment] 2019-06-16 11:06
hashcat has just implemented the 2 bytes check, and as expected got much better speeds than ours - see that Twitter thread referenced above. hashcat is now at ~3300K on GTX 1080.

I've just edited item 4 in my original comment, and inserted this new item:

5. When we early-reject a password with the 2 bytes check, which we do most of the time, we end up transferring a bunch of zeroes back to the host. This is wasteful. We might want to introduce a protocol where we'd only transfer actually computed derived keys perhaps tagged with numbers of the corresponding input passwords.

**Comment by magnumripper** [comment] 2019-06-17 23:23
So much to do, so little time!

**Comment by magnumripper** [comment] 2021-09-16 10:02
> When we compute the 2 bytes of PBKDF2 and occasionally have to (re)compute the rest, perhaps we can skip the PBKDF2 output block that included the 2 bytes if they were part of a block that we need anyway? (We'd need to store the full block, not just the 2 bytes, for that to work.)

Trying to grok this now. Here's our current (non-SIMD) CPU code:
```c
		union {
			unsigned char pwd_ver[64];
			uint32_t w;
		} x;
		unsigned char *pwd_ver = x.pwd_ver;

		pbkdf2_sha1((unsigned char *)saved_key[index], strlen(saved_key[index]),
		            saved_salt->salt, SALT_LENGTH(saved_salt->v.mode),
		            KEYING_ITERATIONS, pwd_ver, 2,
		            2 * KEY_LENGTH(saved_salt->v.mode));
		if (!memcmp(pwd_ver, saved_salt->passverify, 2)) {
			pbkdf2_sha1((unsigned char *)saved_key[index],
			            strlen(saved_key[index]), saved_salt->salt,
			            SALT_LENGTH(saved_salt->v.mode), KEYING_ITERATIONS,
			            pwd_ver, KEY_LENGTH(saved_salt->v.mode),
			            KEY_LENGTH(saved_salt->v.mode));
			hmac_sha1(pwd_ver, KEY_LENGTH(saved_salt->v.mode),
			          (const unsigned char*)saved_salt->datablob,
			          saved_salt->comp_len, crypt_key[index],
			          WINZIP_BINARY_SIZE);
		}
		else
			memset(crypt_key[index], 0, WINZIP_BINARY_SIZE);
```
`KEY_LENGTH()` can be 16..32 so the `pwd_ver[64]` is unnecessarily twice the needed size with the code as-is. But anyway:

Last two arguments to `pbkdf2_sha1()` are `out_len, skip_bytes`.

[Edited]
Given a `KEY_LENGTH()` of 32, we first do a PBKDF2 for 2 bytes  with `skip_bytes` set to 64. Given 20-byte blocks this means we skip 1st..3rd block and only calculate the 4th block, where we get our two bytes from. If the early-reject passes, we do a PBKDF2 for 32 bytes with `skip_bytes` set to 32. That means we skip 1st block and get our 32 bytes from 2nd..4th block. We should re-use the 4th block!

Given a `KEY_LENGTH()` of 24, we first do a PBKDF2 for 2 bytes  with `skip_bytes` set to 48. So we skip 1st..2nd block and only calculate the 3rd, where we get our two bytes from. If the early-reject passes, we do a PBKDF2 for 24 bytes with `skip_bytes` set to 24. That means we skip 1st block and get our 24 bytes from 2nd and 3rd block. This time we could re-use the first calculation of 3rd block.

Given a `KEY_LENGTH()` of 16, we first do a PBKDF2 for 2 bytes  with `skip_bytes` set to 32. So we skip 1st block and only calculate the 2nd, where we get our two bytes. If the early-reject passes, we do a PBKDF2 for 16 bytes with `skip_bytes` set to 16. That means we don't skip any full block, we get our 16 bytes from 1st and 2nd block. This time we could actually re-use the first calculation of 2nd block.

**Comment by magnumripper** [comment] 2021-09-16 10:31
> Did I get this right?

No I didn't, will edit.

**Comment by magnumripper** [comment] 2021-09-16 12:28
Unintuitively (to me) I ~only see a 1.5% boost~ can't reliably see *any* boost from re-using that first block. That's with non-SIMD, non-OMP CPU code.
```c
	int early_skip, late_skip, late_size;

	switch(key_len) {
	case 32: /* We need 4th block for early-reject, and 2nd..4th for verify */
		early_skip = 3;
		late_skip = 1;
		late_size = 2;
		break;

	case 24: /* We need 3rd block for early-reject and 2nd..3rd for verify */
		early_skip = 2;
		late_skip = 1;
		late_size = 1;
		break;

	default:
	case 16: /* We need 2nd block for early-reject and 1st..2nd for verify */
		early_skip = 1;
		late_skip = 0;
		late_size = 1;
	}

	/* Get the block that contains the two-byte verifier */
	pbkdf2_sha1((unsigned char *)saved_key[index], strlen(saved_key[index]),
	            saved_salt->salt, SALT_LENGTH(saved_salt->v.mode), KEYING_ITERATIONS,
	            pwd_ver + early_skip * SHA1_SIZE, SHA1_SIZE, early_skip * SHA1_SIZE);

	/* Early-rejection */
	if (!memcmp(pwd_ver + 2 * key_len, saved_salt->passverify, 2)) {
		/* Get the remaining block(s) needed for the HMAC */
		pbkdf2_sha1((unsigned char *)saved_key[index], strlen(saved_key[index]),
		            saved_salt->salt, SALT_LENGTH(saved_salt->v.mode), KEYING_ITERATIONS,
		            pwd_ver + late_skip * SHA1_SIZE, late_size * SHA1_SIZE, late_skip * SHA1_SIZE);

		hmac_sha1(pwd_ver + key_len, key_len,
		          (const unsigned char*)saved_salt->datablob, saved_salt->comp_len,
		          crypt_key[index], WINZIP_BINARY_SIZE);
	}
	else
		memset(crypt_key[index], 0, WINZIP_BINARY_SIZE);
```

**Comment by magnumripper** [comment] 2021-09-16 14:10
The boost seem to be more noticable using SIMD and OpenMP (I'll do OpenCL as well).

@solardiz the approach I used above is slightly wasteful with needed buffers, it's `unsigned char pwd_ver[4 * SHA1_SIZE];` although it never actually fills all of it: It could be `3 * SHA1_SIZE` if I add a little more complexity, or even `2 * SHA1_SIZE` with even less readable code. Not hard to write but a real mess to debug or understand later. Would you expect that to make any performance difference? Perhaps on GPU? I'm not sure I even want to try it.

Edit: It's now `3 * SHA1_SIZE`. Code will be a tad harder to digest but it's fairly trivial once you see what is happening.

**Comment by solardiz** [comment] 2021-09-17 19:07
@magnumripper Thank you for working on this. I don't currently have an opinion on the approach to take. We got the new hashcat's speeds as reference of what's possible to achieve, so ideally we'd use whatever achieves similar or better speeds. There was also the issue with unexpectedly not-high-enough GPU utilization, as seen from my comparison against e.g. md5crypt-opencl above - perhaps this should be looked into and can be dealt with, too.

**Comment by magnumripper** [comment] 2021-09-19 14:32
I've done a lot work with the GPU format the last couple of days:
- The "never recalculate" thing. Should be at least a slight boost (although it only matters when the early-rejection passes - once in 64K). I did it similarly to what's posted above so there aren't diverging branches or anything like that (and all threads are working with the same salt anyway).
- Switched to a non-shared PBKDF2 so we're working with private memory as long as we can, instead of global.
- Added mask mode just for the sake of it. More importantly than the actual on-device mask generation, this comes with packed key buffers even without a mask, so key transfer is almost 90% smaller than the current 68 bytes * GWS.
- Decreased result transfer to the actual needed (i.e. normally just the four byte result count), close to 100% smaller than current 68 bytes * GWS (which was actually seven times larger than ever needed due to using a generic PBKDF2 kernel). Should definitely make at least a *little* boost but none seen, rather a small regression.

All that to no avail! It's no faster than before. Even changing benchmark length to 0x507 and using a `$zip2$*0*1` test vector for benchmark doesn't make any difference. It's like I'm doing some general mistake but I can't find it. Will keep on trying.

**Comment by magnumripper** [comment] 2021-09-19 16:15
Oh... There's just something wrong with my internal mask stuff! Turning it off:
```
$ ../run/john -test -form:zip-opencl -no-mask
Device 2: NVIDIA GeForce RTX 2080 Ti
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]... LWS=32 GWS=278528 (8704 blocks) DONE
Raw:    6127K c/s real, 6127K c/s virtual, Dev#2 util: 89%
```
This is 10% faster than latest hashcat's speed on this same gear (5590K c/s) and 12% faster than current bleeding-jumbo.

I still see "GPU util" figures around 90%, not sure why.

**Comment by solardiz** [comment] 2021-09-19 16:36
What was the output for this same test on your gear prior to your optimizations (that is, with the current bleeding-jumbo)?

**Comment by magnumripper** [comment] 2021-09-19 19:31
This seems to be representative for current bleeding. It nearly always autotunes to these figures but the speed varies a little:
```
Device 2: NVIDIA GeForce RTX 2080 Ti
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]... LWS=32 GWS=278528 (8704 blocks) DONE
Raw:    5351K c/s real, 5075K c/s virtual, Dev#2 util: 97%
```

Figures vary more now. It often autotunes too low, like this:
```
Device 2: NVIDIA GeForce RTX 2080 Ti
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]... LWS=32 GWS=34816 (1088 blocks) DONE
Raw:    5646K c/s real, 5675K c/s virtual, Dev#2 util: 96%
```
While that is still better than current bleeding, it's much less than it can be. [The test posted above](https://github.com/openwall/john/issues/4031#issuecomment-922498711) actually tuned to 278528 but it doesn't do so reliably yet. I will try to tweak the autotune settings.

**Comment by magnumripper** [comment] 2021-09-19 20:48
The autotune does everything right, but for some reason the speeds seen at that time doesn't reflect the actual ones later. I have yet to see what's different.

Best seen manually tuned right now:
```
Device 2: NVIDIA GeForce RTX 2080 Ti
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]... LWS=32 GWS=4194304 (131072 blocks) DONE
Raw:    6168K c/s real, 6168K c/s virtual, Dev#2 util: 98%
```

**Comment by magnumripper** [comment] 2021-09-19 22:29
Added AES size as a "cost", for autotune to work better with real hashes. And I just verified (again) that when cracking as opposed to benchmarking, the shared autotune uses the worst salt (worst cost 0) loaded (not because that is always the best idea but because we might overtax the GPU if we don't).

But I realize now that for this format, the key or salt lengths virtually doesn't matter but the data length does (we HMAC all of it unless early rejected). Maybe I should add the data blob length as cost 0. This is also true for some other formats, such as 7z (along with padding size - if it's big enough the data size doesn't matter) and RAR (unless solid).

**Comment by solardiz** [comment] 2021-09-20 16:05
> LWS=32 GWS=4194304

Why is optimal GWS so high? Do we use global memory frequently? Explicitly or via register spilling? What for?

**Comment by magnumripper** [comment] 2021-09-20 16:12
> > LWS=32 GWS=4194304
> 
> Why is optimal GWS so high? Do we use global memory frequently? Explicitly or via register spilling? What for?

I have no idea yet. During autotune, much lower sizes (such as 69632) are measured as given even better speeds (such as 6862K) but then in the benchmark speed ends up as 5819K for that size. I have yet to see what is wrong - or what is different between those two cases.

I believe the kernel is about as lean as it can get now. This doesn't look alarming to me:
```
Build log: 
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function 'zip' for 'sm_75'
ptxas info    : Function properties for zip
ptxas         .     672 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 78 registers, 416 bytes cmem[0]
ptxas info    : Function properties for SHA1_Final
ptxas         .     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
```

**Comment by magnumripper** [comment] 2021-09-20 19:46
I also see a weird low start speed and then increasing. I can't recall seeing this in mask mode often:
```
$ ../run/john test1.in -form:zip-opencl -prog=15 -mask:?a -len=7
Device 2: NVIDIA GeForce RTX 2080 Ti
Using default input encoding: UTF-8
Loaded 1 password hash (ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL])
Cost 1 (HMAC size) is 528 for all loaded hashes
LWS=32 GWS=278528 (8704 blocks) 
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:23 0.00% (ETA: 2022-04-20 02:40) 0g/s 3797Kp/s 3797Kc/s 3797KC/s Dev#2:68°C util:95% _)Vleaa..sw@leaa
0g 0:00:00:38 0.00% (ETA: 2022-03-15 04:03) 0g/s 4582Kp/s 4582Kc/s 4582KC/s Dev#2:73°C util:95% |?Lc1aa.._swc1aa
0g 0:00:00:53 0.00% (ETA: 2022-03-03 15:32) 0g/s 4914Kp/s 4914Kc/s 4914KC/s Dev#2:78°C util:95% iUo4iaa..Ibo4iaa
0g 0:00:01:08 0.00% (ETA: 2022-02-26 02:22) 0g/s 5091Kp/s 5091Kc/s 5091KC/s Dev#2:81°C util:95%  Bm7oaa..CZ07oaa
0g 0:00:01:23 0.00% (ETA: 2022-02-22 22:44) 0g/s 5197Kp/s 5197Kc/s 5197KC/s Dev#2:83°C util:95% &y!jnaa..(LDjnaa
0g 0:00:01:38 0.00% (ETA: 2022-02-21 05:54) 0g/s 5256Kp/s 5256Kc/s 5256KC/s Dev#2:84°C util:95% 7Ipwraa..?)gwraa
0g 0:00:01:53 0.00% (ETA: 2022-02-20 07:16) 0g/s 5292Kp/s 5292Kc/s 5292KC/s Dev#2:84°C util:95% WA'zlaa..p=&zlaa
0g 0:00:02:08 0.00% (ETA: 2022-02-19 17:06) 0g/s 5313Kp/s 5313Kc/s 5313KC/s Dev#2:84°C util:95% dP Asaa..iiJAsaa
(...keeps rising...)
```
A clue might be that the first progress output come 8 seconds too late. This might be caused by some completely unrelated recent change, I'm not sure

**Comment by magnumripper** [comment] 2021-09-20 19:54
OK that seems to be caused by our "time reset" occurring before the autotune, so unrelated:
```
$ ../run/john test1.in -form:zip-opencl -prog=15 -mask:?a -len=7 -lws=32 -gws=278528
Device 2: NVIDIA GeForce RTX 2080 Ti
Using default input encoding: UTF-8
Loaded 1 password hash (ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL])
Cost 1 (HMAC size) is 528 for all loaded hashes
LWS=32 GWS=278528 (8704 blocks) 
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:15 0.00% (ETA: 2022-02-02 15:12) 0g/s 5957Kp/s 5957Kc/s 5957KC/s Dev#2:52°C util:95% No>0eaa..5x[0eaa
0g 0:00:00:30 0.00% (ETA: 2022-02-03 11:21) 0g/s 5940Kp/s 5940Kc/s 5940KC/s Dev#2:61°C util:95% "WPy1aa..~g!y1aa
0g 0:00:00:45 0.00% (ETA: 2022-02-04 04:20) 0g/s 5913Kp/s 5913Kc/s 5913KC/s Dev#2:68°C util:95% 167kiaa..|-4kiaa
```

Edit: This is fixed in #4823

**Comment by magnumripper** [comment] 2021-09-22 20:25
I think I have solved most problems, by separating the HMAC (that is possibly *huge* because it's a datablob of arbitrary size - and yes it obviously sits in global memory) from the main kernel. I'm testing two alternatives: One is with only the HMAC in the final kernel, the other has the 2nd PBKDF2 as well. Both seem to give tremendously better results, both with tiny or huge datablobs. Autotune ends up correct and speed is better than I could imagine, over 4 Mp/s, with my "big sample" having 24 MB of data (hashcat wont even read it BTW, their data size limits rejects the hash).

Some teething problems remains to iron out, ~so no commits to #4813 as of yet~.

**Comment by magnumripper** [comment] 2021-09-23 11:42
There's an 8th thing to address for optimal speed: That HMAC of a chunk (potentially large) of global memory. We currently do it the naive "SHA1_CTX" way, in chunks where we copy it to private memory and process it byte wise.

We're guaranteed alignment so we could do that with optimized code, much less copying back and forth and definitely processing 32 bits at a time. This will be a whole lot faster, I will look into it next.

**Comment by magnumripper** [comment] 2021-09-24 05:11
Tried the above now. Speed for that HMAC almost doubled 😎 but it wont show in the benchmarks. ~Will commit later, I'll do the same change to other shared HMACs first.~

**Closed as completed** 2021-09-29 15:53 UTC
Labels: enhancement
