### ISSUE TITLE
bitcoin2john.py - unsupported btree version: 10

### ISSUE THREAD

**Issue by deathmorlock** [openwall/john#4273] opened 2020-06-14 23:12 UTC
Hello! Today have an eror while tried to get hash:
unsupported btree version: 10

**Comment by solardiz** [comment] 2020-06-15 11:28
Hi @deathmorlock. It is unclear from what you said why exactly you said that and what you want. So let me clarify: our use of GitHub issues is to track issues with JtR that we might want to fix. It is not to provide user support. Please use the john-users mailing list for user support.

Anyway, the specific error you're reporting is generally caused by the version of Berkeley DB in use by Python on your system being incompatible with the Berkeley DB version being used by the altcoin wallet in question. I say altcoin because Bitcoin uses an older version of Berkeley DB, as far as I'm aware not requiring btree version 10.

Given the above, I see nothing for us to fix in JtR on this, other than maybe document this sort of issues and how to work around them in some documentation file. Would you like to help research this and contribute the documentation?

Also, what altcoin is this? What distro are you on? What Python version? What version of Berkeley DB does it use? Are you using the latest `bitcoin2john.py` from this repo or from an older release? These answers would provide a maybe-useful data point for others stumbling upon this issue.

I'll keep this issue open for now in case you suggest how to turn it into anything productive for our project (e.g., use it for work on related documentation, which you'd help write). However, if that doesn't happen we'll likely just close it as a user support issue (thus, misplaced) rather than an issue with JtR. Thanks!

**Comment by deathmorlock** [comment] 2020-06-15 15:39
Thanks for reply.
-For example it is https://github.com/DigitalNoteXDN/DigitalNote-2/releases (but i met such error in many other wallets). 
i uploaded empty wallet.dat with 123 pass for you here: https://transferxl.com/08jCHvK3mXfVdZ

-I have last version of bitcoin2john.py from github
-I have python 2.7 on windows
as i just read " bsddb module has been updated from 4.7.2devel9 to version 4.8.4 of the"
It has old Berkeley DB version as you said.

Today I installed python 3.7 on windows , read that since python 3 there is no bsddb lib included.
Then i  tried 
>>pip install bsddb3
But had errors during install, and found that i need to download precompiled from here
https://www.lfd.uci.edu/~gohlke/pythonlibs/#bsddb3
then 
>>pip install bsddb3 bsddb3-6.2.7-cp37-cp37m-win_amd64.whl

but it didn't help with this problem. So it will be very useful to make some documentation about this issue. Will be glad to assist you

**Comment by solardiz** [comment] 2020-06-15 15:56
Please upload the test wallet with known password to: https://openwall.info/wiki/john/sample-non-hashes

In what way did your last attempt to install precompiled bsddb3 not help?

**Comment by solardiz** [comment] 2020-06-15 17:18
Per my notes in #4143, this works on Fedora:

```
dnf install libdb-devel python3-devel
pip3 install bsddb3
```

along with running the script under `python3`.

**Comment by solardiz** [comment] 2020-06-15 18:41
@deathmorlock Thank you for uploading the file to the wiki. However, you didn't link to that file from the wiki page. Please do.

**Comment by deathmorlock** [comment] 2020-06-15 18:57
https://openwall.info/wiki/_media/john/xdn_wallet.zip

I just tested on Ubuntu18 with python3 -  also have unsupported btree version: 10 
https://pypi.org/project/bsddb3/
pip3 install bsddb3
also needed to change str 124 in bitcoin2john.py cuz a bit new DBerror structure.

same i have on Windows

**Comment by solardiz** [comment] 2020-06-15 20:23
@deathmorlock You still have not added this to the wiki page. Please do.

Anyway, I've tried your test wallet on Fedora, and yes - same error. I vaguely recall that approach worked for me for btree version 9, but maybe not for 10. Maybe it takes a fully custom build of Berkeley DB to get version 10.

What change did you need to make on line 124? Does that change preserve compatibility with older systems as well?

**Comment by deathmorlock** [comment] 2020-06-15 20:53
Oh sry, i added it to article.

I need just to replace
 logging.error("{0}:{1}".format(e[0], e[1]))  >> logging.error(e)
to prevent error: **TypeError: 'DBInvalidArgError' object does not support indexing**

Hm, i wonder what Berkeley DB version has btree 10 ...
Tried to look at coin source ( it should have needed libs in readme, but didn't found... )

**Comment by solardiz** [comment] 2020-06-15 21:02
Thanks for reporting this issue with the `logging.error` call. Per my quick tests now, this change you describe is needed for Python 3, but is also OK to have with Python 2 (where it results in not so pretty, yet acceptable output).

BDB 6 has that btree version 10. Many distros don't carry that version because of license change since BDB 5. However, at least Zcash and its forks build with BDB 6.

**Comment by deathmorlock** [comment] 2020-06-15 22:43
Oh i win it :)
For Ununtu, don't know how to do same for Windows ..
We need to compile newer version of Berkeley than in pip
Compile Berkeley DB C libs
```
sudo wget http://download.oracle.com/berkeley-db/db-6.2.32.NC.tar.gz
sudo tar zxf db-6.2.32.NC.tar.gz
cd db-6.2.32.NC/build_unix
sudo /home/db-6.2.32.NC/dist/configure --prefix /usr/local/berkeley-db/6.2.32
sudo make install
```
Download python wrapper for Berkeley and install with our libs
```
sudo wget https://files.pythonhosted.org/packages/fa/ad/eb82bcccbfb076b6a6797f48c339460699103065fb2a2fc72403b16970fe/bsddb3-6.2.7.tar.gz
sudo tar zxf bsddb3-6.2.7.tar.gz
cd bsddb3-6.2.7
```
 
`sudo -H nano /etc/environment`
add
YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION="/home"  
BERKELEYDB_DIR=/usr/local/berkeley-db/6.2.32

`sudo python3 setup.py install `

**Comment by ghost** [comment] 2020-06-16 14:03
FTR (at this right moment): 
* Ubuntu 20.10 is using libdb (5.3) and fails.
* Fedora Rawhide is using libdb (5.3) and fails.

So, this is not about "documenting". We need to teach how to install from source, use unusual distros, or, even better, use a docker image we can provide.

**Comment by solardiz** [comment] 2020-06-16 14:17
@deathmorlock Thank you for these instructions. You're over-using `sudo`. Can you come up with a tested alternative that makes minimum use of `sudo` (perhaps only for the two `install` steps and for editing the file in `/etc`), which we could recommend to users? In fact, ideally the new BDB and Python module would be installed in the user's home directory, thus without `sudo` at all, but that probably requires more trickery.

@claudioandre-br This is not about documenting what we have in JtR, but it is about providing specific instructions for this use case on specific distros.

As to "unusual distros", per my package searches yesterday, I think Arch Linux has BDB 6 (as an option?)

**Comment by ghost** [comment] 2020-06-16 14:48
I found only 5.3 https://www.archlinux.org/packages/?sort=&q=db&maintainer=&flagged=

**Comment by solardiz** [comment] 2020-06-16 19:19
@deathmorlock I've included a revision of your instructions (untested) in PR #4275 - please take a look and comment, if you can. Thank you!

**Comment by solardiz** [comment] 2020-06-16 19:21
> YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION="/home"

What do you mean by setting this to `"/home"`? Would any other string like e.g. `yes` work just as well?

Edit: some googling suggests people commonly set this to 1 or yes.

**Comment by deathmorlock** [comment] 2020-06-17 09:36
>>What do you mean by setting this to "/home"


it can be any random value, no matter

**Closed as completed** 2020-06-17 14:09 UTC
Labels: documentation
