### ISSUE TITLE
blockchain2john.py: "json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)" on wallets recently downloaded from blockchain.com

### ISSUE THREAD

**Issue by Drax4545** [openwall/john#5607] opened 2024-12-06 22:09 UTC
\blockchain2john.py", line 44, in <module>
    decoded_data = json.loads(data.decode("utf-8"))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by solardiz** [comment] 2024-12-06 22:58
@exploide Can you help look into this, please? Is it maybe a new issue with more recent Python 3.x than the script had been tested with? Thank you!

**Comment by Drax4545** [comment] 2024-12-06 23:02
This is the error when run on btcrecover. I just downloaded the hash, it is wallet 2 and wallet 3. same error.

Starting btcrecover 1.11.0-Cryptoguide on Python 3.11.0 64-bit, 21-bit unicodes, 64-bit ints
Error: unrecognized wallet format; heuristic parser(s) reported:
    WalletPywallet: Unrecognized pywallet format (can't find mkey)
    WalletMultiBitHD: MultiBit HD wallet files must be named mbhd.wallet.aes
    WalletElectrum2: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
    WalletBlockchain: Incorrect padding

**Comment by solardiz** [comment] 2024-12-07 01:32
Oh, I didn't read closely enough. It's crashing on trying to parse the data, so I guess whatever is in the wallet file is either unsupported by the script as-is or is wrong.

> I just downloaded the hash, it is wallet 2 and wallet 3.

What do you mean by these two things? Downloaded what hash, from where? How can it be [version?] 2 and 3 at once?

I'll label this as user support question for now, but as it is it's just confusing - something does not work, but no idea if it was supposed to work.

**Comment by Drax4545** [comment] 2024-12-07 01:38
I downloaded two hash today from blockchain.com. one is wallet version 2 the other is wallet version 3. All same error when I run it.

**Comment by solardiz** [comment] 2024-12-07 01:42
> json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Here's how I can reproduce this exact error message:

```
$ cat f
{
$ ls -l f
-rw------- 1 user user 2 Dec  7 02:36 f
$ ./blockchain2john.py --json f
Traceback (most recent call last):
  File "/home/user/j/john/run/./blockchain2john.py", line 44, in <module>
    decoded_data = json.loads(data.decode("utf-8"))
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

When I run on a larger yet broken JSON file, I get messages about offsets much further into the file (where it becomes clear to the parser that the file isn't valid JSON). When I run on a large correct JSON file that isn't a valid Blockchain wallet, I get empty output (no error).

So this error message means the file looks a tiny bit like JSON initially, but isn't valid JSON.

You could want to check what your downloaded files actually look like.

I'll close this issue since there appears to be nothing for us to do on it, but please feel free to add comments.

**Closed as completed by solardiz** 2024-12-07 01:42 UTC
Labels: question

**Comment by Drax4545** [comment] 2024-12-07 01:48
The file downloaded is not corrupted it is directly downloaded from blockchain.com. just recently.

**Comment by solardiz** [comment] 2024-12-07 02:50
OK, I suppose they may have changed the format of downloaded files. We would need a sample file (without funds in the wallet) to troubleshoot this, or at least the first few characters from a recently downloaded file like this.

However, as you're aware, we have other open issues related to Blockchain wallet support, and aren't currently investing time into fixing those. So if things broke even further since, I'm afraid we'll just leave them broken for now. :-(
