### ISSUE TITLE
md5crypt-opencl fails self tests on AMD Radeon Pro Duo

### ISSUE THREAD

**Issue by crioux** [openwall/john#2216] opened 2016-08-16 05:50 UTC
To fix this, I have found that adding '-O1' to the clBuildProgram opencl compiler argument list made things work. While this is suboptimal, I haven't found a better solution to this issue as of yet. Note that '-O1' is only a valid option for AMD's opencl driver, and not other platforms.

**Comment by crioux** [comment] 2016-08-16 05:51
Unfortunately, the way I fixed this is pretty much tied to the jtrdll fork implementation, so a seperate fix (preferably just fixing the kernel itself somehow) would be required for jumbo.

**Comment by magnumripper** [comment] 2016-08-16 13:25
Thanks for reporting. Please post the output of `--list=opencl-devices` for this driver and GPU.

**Comment by crioux** [comment] 2016-08-16 13:41
```
Platform #0 name: AMD Accelerated Parallel Processing, version: OpenCL 2.0 AMD-APP (2004.6)
    Device #0 (0) name:     Fiji
    Board name:             Radeon (TM) Pro Duo
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 2.0 AMD-APP (2004.6)
    Driver version:         2004.6 (VM)
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          4.0 GB
    Global Memory Cache:    16.0 KB
    Local Memory:           32.0 KB (Local)
    Max memory alloc. size: 2.0 GB
    Max clock (MHz):        1000
    Profiling timer res.:   1 ns
    Max Work Group Size:    256
    Parallel compute cores: 64
    Speed index:            64000
    SIMD width:             16
    Wavefront width:        64
    PCI device topology:

    Device #1 (1) name:     Fiji
    Board name:             Radeon (TM) Pro Duo
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 2.0 AMD-APP (2004.6)
    Driver version:         2004.6 (VM)
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          4.0 GB
    Global Memory Cache:    16.0 KB
    Local Memory:           32.0 KB (Local)
    Max memory alloc. size: 2.0 GB
    Max clock (MHz):        1000
    Profiling timer res.:   1 ns
    Max Work Group Size:    256
    Parallel compute cores: 64
    Speed index:            64000
    SIMD width:             16
    Wavefront width:        64
    PCI device topology:

    Device #2 (2) name:     Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Device vendor:          GenuineIntel
    Device type:            CPU (LE)
    Device version:         OpenCL 1.2 AMD-APP (2004.6)
    Driver version:         2004.6 (sse2,avx)
    Native vector widths:   char 16, short 8, int 4, long 2
    Preferred vector width: char 16, short 8, int 4, long 2
    Global Memory:          31.0 GB
    Global Memory Cache:    32.0 KB
    Local Memory:           32.0 KB (Global)
    Max memory alloc. size: 7.0 GB
    Max clock (MHz):        4008
    Profiling timer res.:   255 ns
    Max Work Group Size:    1024
    Parallel compute cores: 8
    Speed index:            128256
    PCI device topology:

Detected avx2 instruction set
```

**Comment by claudioandre** [comment] 2016-08-16 17:12
The same here: I'm missing info.

**Comment by crioux** [comment] 2016-08-16 17:34
Radeon Pro Duo list:
```
./jtrexe --verb=5 --list=opencl-devices
Platform #0 name: AMD Accelerated Parallel Processing, version: OpenCL 2.0 AMD-APP (2004.6)
    Platform extensions:    cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices
    Device #0 (0) name:     Fiji
    Board name:             Radeon (TM) Pro Duo
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 2.0 AMD-APP (2004.6)
    Driver version:         2004.6 (VM)
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          4.0 GB
    Device extensions:      cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_fp16
    Global Memory Cache:    16.0 KB
    Local Memory:           32.0 KB (Local)
    Max memory alloc. size: 2.0 GB
    Max clock (MHz):        1000
    Profiling timer res.:   1 ns
    Max Work Group Size:    256
    Parallel compute cores: 64
    Speed index:            64000
    SIMD width:             16
    Wavefront width:        64
    PCI device topology:

    Device #1 (1) name:     Fiji
    Board name:             Radeon (TM) Pro Duo
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 2.0 AMD-APP (2004.6)
    Driver version:         2004.6 (VM)
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          4.0 GB
    Device extensions:      cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_fp16
    Global Memory Cache:    16.0 KB
    Local Memory:           32.0 KB (Local)
    Max memory alloc. size: 2.0 GB
    Max clock (MHz):        1000
    Profiling timer res.:   1 ns
    Max Work Group Size:    256
    Parallel compute cores: 64
    Speed index:            64000
    SIMD width:             16
    Wavefront width:        64
    PCI device topology:

    Device #2 (2) name:     Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Device vendor:          GenuineIntel
    Device type:            CPU (LE)
    Device version:         OpenCL 1.2 AMD-APP (2004.6)
    Driver version:         2004.6 (sse2,avx)
    Native vector widths:   char 16, short 8, int 4, long 2
    Preferred vector width: char 16, short 8, int 4, long 2
    Global Memory:          31.0 GB
    Device extensions:      cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_spir cl_khr_gl_event
    Global Memory Cache:    32.0 KB
    Local Memory:           32.0 KB (Global)
    Max memory alloc. size: 7.0 GB
    Max clock (MHz):        4008
    Profiling timer res.:   255 ns
    Max Work Group Size:    1024
    Parallel compute cores: 8
    Speed index:            128256
    PCI device topology:

Detected avx2 instruction set
initUnicode(UNICODE, UTF-8/ISO-8859-1)
UTF-8 -> UTF-8 -> UTF-8
```

**Comment by crioux** [comment] 2016-08-16 17:45
Failing Test on md5-crypt:
```
./jtrexe --verb=5 --device=0 --format=md5crypt-opencl --test=5

Benchmarking: md5crypt-opencl, crypt(3) $1$ [MD5 OpenCL]... FAILED (cmp_all(1) $1$Btiy90iG$bGn4vzF3g1rIVGZ5odGIp/)

Detected avx2 instruction set
initUnicode(UNICODE, ASCII/ASCII)
ASCII -> ASCII -> ASCII
Device 0: Fiji [Radeon (TM) Pro Duo]
Loaded 61 hashes with 39 different salts to test db from test vectors
Options used: -I G:\l0phtcrack\lc7\build_Win64\dist\Beta\lcplugins\lc7jtr{9846c8cf-1db1-467e-83c2-c5655aa81936}\kernels -cl-mad-enable -frontend=edg  -D__GPU__ -DDEVICE_INFO=522 -DSIZEOF_SIZE_T=8 -DDEV_VER_MAJOR=2004 -DDEV_VER_MINOR=6 -D_OPENCL_COMPILER -DPLAINTEXT_LENGTH=15  $JOHN/kernels/cryptmd5_kernel.cl
binary size 60272
Calculating best GWS for LWS=64; max. 250ms single kernel invocation.
Raw speed figures including buffer transfers:
pass xfer: 4.480us, crypt: 2.934ms, result xfer: 4.160us
gws: 1024        347958c/s347958000 rounds/s   2.942ms per crypt_all()!
pass xfer: 6.560us, crypt: 2.894ms, result xfer: 5.120us
gws: 2048        704768c/s704768000 rounds/s   2.905ms per crypt_all()!
pass xfer: 11.040us, crypt: 2.899ms, result xfer: 7.200us
gws: 4096         1403Kc/s1403970000 rounds/s   2.917ms per crypt_all()+
pass xfer: 20.160us, crypt: 2.993ms, result xfer: 11.520us
gws: 8192         2707Kc/s2707562000 rounds/s   3.025ms per crypt_all()+
pass xfer: 36.640us, crypt: 3.352ms, result xfer: 21.120us
gws: 16384        4803Kc/s4803677000 rounds/s   3.410ms per crypt_all()+
pass xfer: 72.960us, crypt: 5.678ms, result xfer: 39.520us
gws: 32768        5658Kc/s5658396000 rounds/s   5.791ms per crypt_all()+
pass xfer: 141.440us, crypt: 11.139ms, result xfer: 77.760us
gws: 65536        5769Kc/s5769908000 rounds/s  11.358ms per crypt_all()+
pass xfer: 287.040us, crypt: 23.537ms, result xfer: 160.480us
gws: 131072       5464Kc/s5464721000 rounds/s  23.985ms per crypt_all()
pass xfer: 578.080us, crypt: 46.686ms, result xfer: 360.160us
gws: 262144       5504Kc/s5504396000 rounds/s  47.624ms per crypt_all()
pass xfer: 1.202ms, crypt: 110.169ms, result xfer: 667.040us
gws: 524288       4679Kc/s4679511000 rounds/s 112.039ms per crypt_all()
pass xfer: 2.308ms, crypt: 207.786ms, result xfer: 1.372ms
gws: 1048576      4958Kc/s4958578000 rounds/s 211.467ms per crypt_all()
pass xfer: 4.616ms, crypt: 412.153ms (exceeds 250ms)
Calculating best LWS for GWS=65536
Testing LWS=64 GWS=65536 ... 55.629ms+
Testing LWS=128 GWS=65536 ... 66.295ms
Testing LWS=256 GWS=65536 ... 60.395ms
Calculating best GWS for LWS=64; max. 500ms single kernel invocation.
Raw speed figures including buffer transfers:
pass xfer: 10.880us, crypt: 2.992ms, result xfer: 7.520us
gws: 4096         1360Kc/s1360616000 rounds/s   3.010ms per crypt_all()!
pass xfer: 20us, crypt: 3.027ms, result xfer: 11.840us
gws: 8192         2678Kc/s2678104000 rounds/s   3.058ms per crypt_all()+
pass xfer: 37.120us, crypt: 3.352ms, result xfer: 21.600us
gws: 16384        4803Kc/s4803452000 rounds/s   3.410ms per crypt_all()+
pass xfer: 72.480us, crypt: 5.667ms, result xfer: 39.680us
gws: 32768        5669Kc/s5669674000 rounds/s   5.779ms per crypt_all()+
pass xfer: 143.520us, crypt: 11.138ms, result xfer: 78.400us
gws: 65536        5768Kc/s5768770000 rounds/s  11.360ms per crypt_all()+
pass xfer: 281.120us, crypt: 23.534ms, result xfer: 160.640us
gws: 131072       5466Kc/s5466800000 rounds/s  23.976ms per crypt_all()
pass xfer: 584.480us, crypt: 46.962ms, result xfer: 347.520us
gws: 262144       5473Kc/s5473374000 rounds/s  47.894ms per crypt_all()
pass xfer: 1.194ms, crypt: 103.104ms, result xfer: 716.480us
gws: 524288       4992Kc/s4992473000 rounds/s 105.015ms per crypt_all()
pass xfer: 2.324ms, crypt: 211.323ms, result xfer: 1.372ms
gws: 1048576      4876Kc/s4876647000 rounds/s 215.019ms per crypt_all()
pass xfer: 4.615ms, crypt: 414.910ms, result xfer: 2.669ms
gws: 2097152      4967Kc/s4967262000 rounds/s 422.194ms per crypt_all()
pass xfer: 9.250ms, crypt: 818.979ms (exceeds 500ms)
Local worksize (LWS) 64, global worksize (GWS) 65536
```

**Comment by crioux** [comment] 2016-08-16 17:46
Passing test on md5crypt-opencl:
```
$ export OPENCLBUILDOPTIONS=-O1
$ ./jtrexe --verb=5 --device=0 --format=md5crypt-opencl --test=5

Benchmarking: md5crypt-opencl, crypt(3) $1$ [MD5 OpenCL]... DONE
Raw:    3056K c/s

Detected avx2 instruction set
initUnicode(UNICODE, ASCII/ASCII)
ASCII -> ASCII -> ASCII
Device 0: Fiji [Radeon (TM) Pro Duo]
Loaded 61 hashes with 39 different salts to test db from test vectors
Options used: -I G:\l0phtcrack\lc7\build_Win64\dist\Beta\lcplugins\lc7jtr{9846c8cf-1db1-467e-83c2-c5655aa81936}\kernels -O1 -frontend=edg  -D__GPU__ -DDEVICE_INFO=522 -DSIZEOF_SIZE_T=8 -DDEV_VER_MAJOR=2004 -DDEV_VER_MINOR=6 -D_OPENCL_COMPILER -DPLAINTEXT_LENGTH=15  $JOHN/kernels/cryptmd5_kernel.cl
binary size 71920
Calculating best GWS for LWS=64; max. 250ms single kernel invocation.
Raw speed figures including buffer transfers:
pass xfer: 4.480us, crypt: 3.814ms, result xfer: 4.160us
gws: 1024        267816c/s267816000 rounds/s   3.823ms per crypt_all()!
pass xfer: 6.400us, crypt: 3.816ms, result xfer: 5.120us
gws: 2048        535049c/s535049000 rounds/s   3.827ms per crypt_all()+
pass xfer: 11.040us, crypt: 3.888ms, result xfer: 7.360us
gws: 4096         1048Kc/s1048449000 rounds/s   3.906ms per crypt_all()+
pass xfer: 19.840us, crypt: 4.260ms, result xfer: 11.840us
gws: 8192         1908Kc/s1908809000 rounds/s   4.291ms per crypt_all()+
pass xfer: 50.400us, crypt: 4.853ms, result xfer: 20.960us
gws: 16384        3327Kc/s3327051000 rounds/s   4.924ms per crypt_all()+
pass xfer: 72.480us, crypt: 6.706ms, result xfer: 39.680us
gws: 32768        4805Kc/s4805932000 rounds/s   6.818ms per crypt_all()+
pass xfer: 142.400us, crypt: 11.732ms, result xfer: 78.080us
gws: 65536        5482Kc/s5482679000 rounds/s  11.953ms per crypt_all()+
pass xfer: 285.600us, crypt: 23.173ms, result xfer: 162.880us
gws: 131072       5548Kc/s5548706000 rounds/s  23.622ms per crypt_all()+
pass xfer: 568us, crypt: 45.681ms, result xfer: 348.160us
gws: 262144       5625Kc/s5625639000 rounds/s  46.598ms per crypt_all()+
pass xfer: 1.197ms, crypt: 106.610ms, result xfer: 702.240us
gws: 524288       4831Kc/s4831698000 rounds/s 108.510ms per crypt_all()
pass xfer: 2.304ms, crypt: 201.640ms, result xfer: 1.385ms
gws: 1048576      5106Kc/s5106778000 rounds/s 205.330ms per crypt_all()
pass xfer: 4.680ms, crypt: 392.287ms (exceeds 250ms)
Calculating best LWS for GWS=262144
Testing LWS=64 GWS=262144 ... 210.070ms+
Testing LWS=128 GWS=262144 ... 201.880ms+
Testing LWS=256 GWS=262144 ... 201.517ms
Calculating best GWS for LWS=128; max. 500ms single kernel invocation.
Raw speed figures including buffer transfers:
pass xfer: 10.880us, crypt: 4.123ms, result xfer: 7.360us
gws: 4096        988989c/s988989000 rounds/s   4.141ms per crypt_all()!
pass xfer: 20.480us, crypt: 4.319ms, result xfer: 12.320us
gws: 8192         1882Kc/s1882214000 rounds/s   4.352ms per crypt_all()+
pass xfer: 36.800us, crypt: 5.869ms, result xfer: 20.960us
gws: 16384        2763Kc/s2763981000 rounds/s   5.927ms per crypt_all()+
pass xfer: 72us, crypt: 6.705ms, result xfer: 39.520us
gws: 32768        4807Kc/s4807060000 rounds/s   6.816ms per crypt_all()+
pass xfer: 144.160us, crypt: 11.780ms, result xfer: 78.400us
gws: 65536        5460Kc/s5460095000 rounds/s  12.002ms per crypt_all()+
pass xfer: 284.960us, crypt: 23.227ms, result xfer: 173.600us
gws: 131072       5533Kc/s5533751000 rounds/s  23.685ms per crypt_all()+
pass xfer: 572.960us, crypt: 46.272ms, result xfer: 348.800us
gws: 262144       5554Kc/s5554538000 rounds/s  47.194ms per crypt_all()
pass xfer: 1.174ms, crypt: 99.132ms, result xfer: 736.480us
gws: 524288       5188Kc/s5188775000 rounds/s 101.042ms per crypt_all()
pass xfer: 2.334ms, crypt: 203.336ms, result xfer: 1.324ms
gws: 1048576      5065Kc/s5065674000 rounds/s 206.996ms per crypt_all()
pass xfer: 4.601ms, crypt: 393.560ms, result xfer: 2.687ms
gws: 2097152      5231Kc/s5231776000 rounds/s 400.848ms per crypt_all()
pass xfer: 9.201ms, crypt: 773.984ms (exceeds 500ms)
Local worksize (LWS) 128, global worksize (GWS) 131072
```

**Comment by crioux** [comment] 2016-08-16 17:47
sha512 crypt test:

```
./jtrexe --verb=5 --device=0 --format=sha512crypt-opencl --test=5
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... Detected avx2 instruction set
initUnicode(UNICODE, ASCII/ASCII)
ASCII -> ASCII -> ASCII
Device 0: Fiji [Radeon (TM) Pro Duo]
Loaded 6 hashes with 4 different salts to test db from test vectors
Building the kernel, this could take a while
Options used: -I G:\l0phtcrack\lc7\build_Win64\dist\Beta\lcplugins\lc7jtr{9846c8cf-1db1-467e-83c2-c5655aa81936}\kernels -cl-mad-enable -frontend=edg  -D__GPU__ -DDEVICE_INFO=522 -DSIZEOF_SIZE_T=8 -DDEV_VER_MAJOR=2004 -DDEV_VER_MINOR=6 -D_OPENCL_COMPILER   $JOHN/kernels/cryptsha512_kernel_GPU.cl
binary size 646432
Build time: 9 seconds
Calculating best GWS for LWS=64; max. 100ms single kernel invocation.
Raw speed figures including buffer transfers:
xfer: 6.240us, crypt: 119x1.757ms, xfer back: 7.360us, prep: 3.351ms, pp: 6.625ms*, final: 149.600us, var: 1.765ms/1.764ms
gws: 1024          4654c/s23270000 rounds/s     220ms per crypt_all()!
xfer: 9.760us, crypt: 119x1.832ms, xfer back: 12us, prep: 3.353ms, pp: 87.360us, final: 147.840us, var: 1.760ms/1.761ms
gws: 2048          9479c/s47395000 rounds/s 216.055ms per crypt_all()!
xfer: 16.800us, crypt: 119x1.770ms, xfer back: 21.280us, prep: 3.346ms, pp: 87.840us, final: 148.480us, var: 1.766ms/1.765ms
gws: 4096         19137c/s95685000 rounds/s 214.033ms per crypt_all()!
xfer: 31.040us, crypt: 119x1.777ms, xfer back: 39.840us, prep: 3.752ms, pp: 89.280us, final: 150.080us, var: 1.777ms/1.780ms
gws: 8192         37960c/s189800000 rounds/s 215.802ms per crypt_all()+
xfer: 58.560us, crypt: 119x1.799ms, xfer back: 82.080us, prep: 4.412ms, pp: 98.240us, final: 157.760us, var: 1.796ms/1.795ms
gws: 16384        74899c/s374495000 rounds/s 218.745ms per crypt_all()+
xfer: 114.400us, crypt: 119x3.425ms, xfer back: 169.120us, prep: 7.778ms, pp: 140.800us, final: 253.120us, var: 3.425ms/3.421ms
gws: 32768        78747c/s393735000 rounds/s 416.113ms per crypt_all()+
xfer: 226.400us, crypt: 119x6.681ms, xfer back: 426.400us, prep: 15.186ms, pp: 241.760us, final: 436us, var: 6.663ms/6.672ms
gws: 65536        80820c/s404100000 rounds/s 810.885ms per crypt_all()+
xfer: 457.600us, crypt: 119x13.185ms, xfer back: 716.160us, prep: 30.163ms, pp: 529.280us, final: 770.400us, var: 13.148ms/13.140ms
gws: 131072       81967c/s409835000 rounds/s    1.599s per crypt_all()+
xfer: 914.240us, crypt: 119x26.157ms, xfer back: 1.423ms, prep: 59.514ms, pp: 1.206ms, final: 1.463ms, var: 26.157ms/26.104ms
gws: 262144       82528c/s412640000 rounds/s    3.176s per crypt_all()
xfer: 1.813ms, crypt: 119x52.098ms, xfer back: 2.688ms, prep: 125.868ms (exceeds 100ms)
Calculating best LWS for GWS=131072
Testing LWS=64 GWS=131072 ... 73.391ms+
Testing LWS=128 GWS=131072 ... 73.557ms
Testing LWS=256 GWS=131072 ... 73.618ms
Calculating best GWS for LWS=64; max. 200ms single kernel invocation.
Raw speed figures including buffer transfers:
xfer: 17.120us, crypt: 119x1.815ms, xfer back: 21.440us, prep: 3.359ms, pp: 4.273ms*, final: 152.320us, var: 1.829ms/1.824ms
gws: 4096         18215c/s91075000 rounds/s 224.858ms per crypt_all()!
xfer: 30.880us, crypt: 119x1.913ms, xfer back: 39.840us, prep: 3.651ms, pp: 89.120us, final: 150.240us, var: 1.912ms/1.912ms
gws: 8192         35353c/s176765000 rounds/s 231.714ms per crypt_all()+
xfer: 58.880us, crypt: 119x1.967ms, xfer back: 78.400us, prep: 4.455ms, pp: 101.280us, final: 157.440us, var: 1.969ms/1.973ms
gws: 16384        68432c/s342160000 rounds/s 239.416ms per crypt_all()+
xfer: 115.680us, crypt: 119x3.791ms, xfer back: 189.440us, prep: 7.779ms, pp: 140us, final: 256.640us, var: 3.786ms/3.779ms
gws: 32768        71363c/s356815000 rounds/s 459.167ms per crypt_all()+
xfer: 228us, crypt: 119x7.408ms, xfer back: 385.280us, prep: 15.491ms, pp: 243.360us, final: 434.240us, var: 7.408ms/7.414ms
gws: 65536        72902c/s364510000 rounds/s 898.960ms per crypt_all()+
xfer: 450.080us, crypt: 119x14.646ms, xfer back: 668us, prep: 29.244ms, pp: 516.160us, final: 786.880us, var: 14.650ms/14.642ms
gws: 131072       73831c/s369155000 rounds/s    1.775s per crypt_all()+
xfer: 1.064ms, crypt: 119x29.374ms, xfer back: 1.397ms, prep: 61.225ms, pp: 1.202ms, final: 1.436ms, var: 29.293ms/29.153ms
gws: 262144       73816c/s369080000 rounds/s  DONE
Speed for cost 1 (iteration count) of 5000
Raw:    70298 c/s

  3.551s per crypt_all()
xfer: 1.812ms, crypt: 119x58.409ms, xfer back: 2.663ms, prep: 131.548ms, pp: 2.518ms, final: 2.840ms, var: 58.300ms/60.311ms
gws: 524288       73162c/s365810000 rounds/s    7.166s per crypt_all()
xfer: 3.603ms, crypt: 119x117.364ms, xfer back: 5.493ms, prep: 291.841ms (exceeds 200ms)
Local worksize (LWS) 64, global worksize (GWS) 131072
```

**Comment by claudioandre** [comment] 2016-08-16 19:45
Slow, isn't it? If you have the opportunity and interest, could you please try something like this:

Set the env below and see if any gain is seen
```_CALIBRATE=1 ./jtrexe --verb=5 --device=0 --format=sha512crypt-opencl --test```

**Comment by solardiz** [comment] 2021-11-30 13:56
I think we should close this issue from 2016, as I revised md5crypt-opencl significantly in 2019, including addition of an amdgpu-pro driver bug workaround that _might_ have helped here (it did on other AMD GPUs).

@crioux I doubt you can/care to retest on the same hardware now? If you do that, let us know. We can always reopen if the problem is still present and is something for us to look into.

**Closed by solardiz** 2021-11-30 13:56 UTC
Labels: portability
