### ISSUE TITLE
telegram2john.py does not work

### ISSUE THREAD

**Issue by zloishax** [openwall/john#4413] opened 2020-10-23 16:12 UTC
Hey guys, I can not restore my telegram. it has a virtual number. 
https://github.com/openwall/john/blob/bleeding-jumbo/run/telegram2john.py i tried it through it fails gives an error

```
_C:\Users\pc\Desktop\Infinite\telegram2john.py 'C:/Game/Telegram Desktop'
Traceback (most recent call last):
  File "C:\Users\pc\Desktop\Infinite\telegram2john.py", line 179, in <module>
    process_xml_file(sys.argv[j])
  File "C:\Users\pc\Desktop\Infinite\telegram2john.py", line 142, in process_xml_file
    tree = ET.parse(filename)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38-32\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38-32\lib\xml\etree\ElementTree.py", line 584, in parse
    source = open(source, "rb")
OSError: [Errno 22] Invalid argument: "'C:/Game/Telegram"_
```

**Comment by solardiz** [comment] 2020-10-25 15:35
@zloishax What version of Telegram are you running the script against? This is probably a duplicate of #4387.

**Comment by zloishax** [comment] 2020-10-25 15:37
With the latest version, Yes, this is a duplicate, I have 2 telegrams on my computer

**Comment by solardiz** [comment] 2020-10-25 15:48
Thanks @zloishax. I'll close this issue now. You might want to help @philsmd and @magnumripper on #4387 by testing their work-in-progress on getting newer Telegram supported (so far just the revised extraction script, later also support in `john` itself).

**Closed as completed by solardiz** 2020-10-25 15:48 UTC
Labels: dupe

**Comment by ghost** [comment] 2020-10-26 13:45
@zloishax, could you please test JtR recent changes at https://raw.githubusercontent.com/openwall/john/8f923a4d943933508a58fa1f1fec04c5e42f1b24/run/telegram2john.py?

**Comment by zloishax** [comment] 2020-10-26 15:28
> @zloishax, could you please test JtR recent changes at https://raw.githubusercontent.com/openwall/john/8f923a4d943933508a58fa1f1fec04c5e42f1b24/run/telegram2john.py?

I have such an error, pycrypto is not installed, because I have python version 3.8 64bit to install pycrypto need python no more than 2.7

Solve the problem please. Thanks

**Comment by ghost** [comment] 2020-10-26 16:48
I agree that installing pycrypto is an adventure, but it works. Feel free to open a request asking to upgrade from `pycrypto` to `something better`.
![image](https://user-images.githubusercontent.com/1702923/97201960-c6ec3e00-1791-11eb-99b7-cecd4a010587.png)

**Comment by zloishax** [comment] 2020-10-27 04:42
> I agree that installing pycrypto is an adventure, but it works. Feel free to open a request asking to upgrade from `pycrypto` to `something better`.
> ![image](https://user-images.githubusercontent.com/1702923/97201960-c6ec3e00-1791-11eb-99b7-cecd4a010587.png)
> 
> 
> 

Okay, I'll uninstall python, reinstall it, and install the pycrypto module, I'll tell you what will happen soon.  thanks

**Comment by zloishax** [comment] 2020-10-27 05:39
> I agree that installing pycrypto is an adventure, but it works. Feel free to open a request asking to upgrade from `pycrypto` to `something better`.
> ![image](https://user-images.githubusercontent.com/1702923/97201960-c6ec3e00-1791-11eb-99b7-cecd4a010587.png)
> 
> 
> 

`"C:\Users\ALT AIR TRAVEL\Desktop\telegram2john.py" "C:\Users\ALT AIR TRAVEL\AppData\Roaming\telegram"
Traceback (most recent call last):
  File "C:\Users\ALT AIR TRAVEL\Desktop\telegram2john.py", line 179, in <module>
    process_xml_file(sys.argv[j])
  File "C:\Users\ALT AIR TRAVEL\Desktop\telegram2john.py", line 142, in process_xml_file
    tree = ET.parse(filename)
  File "C:\Users\ALT AIR TRAVEL\AppData\Local\Programs\Python\Python38-32\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Users\ALT AIR TRAVEL\AppData\Local\Programs\Python\Python38-32\lib\xml\etree\ElementTree.py", line 584, in parse
    source = open(source, "rb")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ALT AIR TRAVEL\\AppData\\Roaming\\telegram'`
