### ISSUE TITLE
Windows install - Build not working

### ISSUE THREAD

**Issue by Mikazukii05** [openwall/john#4969] opened 2021-12-23 19:04 UTC
I followed all the steps in the INSTALL WINDOWS folder but I have a problem with the build part, it does not work 

After putting this command in the CygWin64, I get this 
 
![Capture d’écran n069](https://user-images.githubusercontent.com/96594126/147282326-2cc2da69-b8f0-45c8-bb0b-5ed24096f0b8.png)

**Comment by solardiz** [comment] 2021-12-23 19:43
@Mikazukii05 Thanks for reporting. If you can, please use textual copy-paste instead of screenshots going forward.

@claudioandre-br This says the system is missing `sed` and `expr`. Do we need to update the Cygwin packages list to install? These are rather basic tools that perhaps were installed by default before, but maybe aren't always?

**Comment by Mikazukii05** [comment] 2021-12-23 20:26
I'll copy and paste it next time okay. 

What do you advise me to do ?
I installed gcc-core, libssl-devel, libgmp-devel, libOpenCL-devel and Make yesterday.

I checked the last version at the bottom so I think I have all the recent versions but I have this error. Do you have any idea what I can do to fix this error?

ps : sed 4.8-1  is installed but I can't find the expr.

**Comment by ghost** [comment] 2021-12-23 20:26
> Do we need to update the Cygwin packages list to install?

Cygwin is now at 3.3.3, no longer at 3.3.1 (I tested using this version). So maybe we need to update something but it's unlikely.

CI ran on Dec 20th using 3.3.3 [here](https://dev.azure.com/claudioandre-br/JohnTheRipper/_build/results?buildId=350&view=logs&j=b56efa78-2896-5fbd-a9f4-1cbf2f1ba17f&t=c15f49fc-4e3e-560e-6994-68b49deb11bd) and it worked. Anyway, I can try it myself sooner or later and confirm.

**Comment by magnumripper** [comment] 2021-12-23 20:33
@Mikazukii05 can you find a package called "coreutils" or something like that? If so, install it.

**Comment by Mikazukii05** [comment] 2021-12-23 20:46
@magnumripper   done,  I added COREUTILS and COREUTILS-DEBUGINFO , but the result does not change I still have this code : 

$ ./configure && make -s clean && make -sj4
./configure: line 473: sed: command not found
./configure: line 472: expr: command not found
./configure: line 473: sed: command not found
./configure: line 487: sed: command not found
: error: cannot create .lineno; rerun with a POSIX shell

Will it help me?

**Comment by solardiz** [comment] 2021-12-23 21:11
@Mikazukii05 You happened to at-mention an unrelated person above - you'd want to edit that.

It is puzzling that installing `coreutils` didn't make a difference - `expr` is normally part of `coreutils`.

For `sed`, you need to install a separate package probably called just that - `sed`.

Or maybe the issue is something entirely different - e.g., maybe you're running a weird shell? What does this say? -

```
echo $SHELL $0
/bin/sh --version
```

**Comment by ghost** [comment] 2021-12-23 21:26
Now I realized that the real problem is how you are using cygwin. Documentation should say:

Open a CygWin terminal using the Windows/graphical shortcut. **(is shortcut the Windows terminology, right?)**

Or you can run bash this way (we can recommend this? It seems we can, it is ok reading man on Linux):
```
REPLACE_USING_CYGWIN-PATH/bash --login -i
```

Or you can fix `$PATH` properly.

**Comment by Mikazukii05** [comment] 2021-12-23 21:52
@solardiz  Hey thank you for helping me , so i got that 

  `$ echo $SHELL $0`
/bin/bash /usr/bin/bash


`/bin/sh --version`

GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by Mikazukii05** [comment] 2021-12-23 21:58
@claudioandre-br  Hi,

° first of all to launch CygWin I do that

1) Launch cmd ,

2) I enter  inside` C:\cygwin64\bin\bash
`
- and I'm there. Isn't it a good way to use CygWin ? 

°Secondly I used the command `CYGWIN-PATH/bash --login -i`
and the command `$PATH `but nothing happened. 

I'm sending you the results on cmd :

CYGWIN-PATH' is not recognized as an internal or external command
or external command, an executable program or a command file.


( same things for `$PATH` )

and on CygWin i got this :



`$ CYGWIN-PATH/bash --login -i`
bash: CYGWIN-PATH/bash: No such file or directory





` $ $PATCH`

pugli@DESKTOP-R31LIJF /cygdrive/c/Users/pugli/OneDrive/Bureau/Johnici/john-bleeding-jumbo/src

**Comment by ghost** [comment] 2021-12-23 22:21
I reproduced the issue using 3.3.1 and I can say that the below statement is a proper fix.

@Mikazukii05, you  should run in CMD:
```
c:\cygwin64\bin\bash --login -i
```
Then `./configure` and so on.

I would say that you need guidance to improve your Linux skills. I leave you in @solardiz hands if you need further assistance.

**Comment by Mikazukii05** [comment] 2021-12-23 22:26
@claudioandre-br ` c:\cygwin64\bin\bash --login -i` actually worked but `./configure` didn't, ok thanks for your help anyway .
( I am in 3.3.3  if you have a link for the 3.3.1 i wouldn't say no)

$ ./configure
bash: ./configure: No such file or directory

**Comment by solardiz** [comment] 2021-12-24 00:14
@Mikazukii05 This means you didn't `cd` into the right directory. You should.

@claudioandre-br Is there anything we should improve in the documentation here? If not, let's just close this issue as it's then not something we need to track.

**Comment by solardiz** [comment] 2021-12-24 00:17
@Mikazukii05 BTW, is there any specific reason you want to build from source? You can also download a fairly recent Windows binary build by clicking the "Download Windows build" badge from `README.md` in this repo.

**Comment by ghost** [comment] 2021-12-24 00:31
> @claudioandre-br Is there anything we should improve in the documentation here?

I would say something like this is appropriate. Not sure if it's wanted:
```
diff --git a/doc/INSTALL-WINDOWS b/doc/INSTALL-WINDOWS
index 792a841da..a3ee2536c 100644
--- a/doc/INSTALL-WINDOWS
+++ b/doc/INSTALL-WINDOWS
@@ -22,8 +22,7 @@ system.
       - C:\cygwin64\setup-x86_64.exe -q -P libgmp-devel -P zlib-devel
       - C:\cygwin64\setup-x86_64.exe -q -P libOpenCL-devel -P libcrypt-devel
 
-    - Open a CygWin terminal. To do that, inside the Command Prompt, type:
-      - C:\cygwin64\bin\bash
+    - Open a CygWin terminal using the Windows Menu or a desktop shortcut.

```

**Comment by solardiz** [comment] 2021-12-24 00:38
```diff
-    - Open a CygWin terminal. To do that, inside the Command Prompt, type:
-      - C:\cygwin64\bin\bash
+    - Open a CygWin terminal using the Windows Menu or a desktop shortcut.
```

I think yes, we should make this edit. Will you?

**Closed as completed** 2021-12-24 01:32 UTC
Labels: documentation, question
