### ISSUE TITLE
SAPH hash with 32-byte salt not crackable

### ISSUE THREAD

**Issue by hsingll** [openwall/john#5155] opened 2022-06-01 19:57 UTC
I pull sap password hashes from usr02 table,and convert it to john password hashes file using sap2john.pl tool.

but when I run command `john password.txt --wordlist='wordlist.txt' --format=sapg`,no password hash is readed.only output`No password hashes loaded`.
it really confuse me.
file: [password.txt](https://github.com/openwall/john/files/8818431/password.txt)

Attach details about your OS and about john, including:
```
Version: 1.9.0-jumbo-1
Build: darwin19.0.0 64-bit x86_64 SSE4.2 AC
SIMD: SSE4.1, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
System-wide exec: /usr/local/Cellar/john-jumbo/1.9.0/share/john
System-wide home: /usr/local/Cellar/john-jumbo/1.9.0/share/john
Private home: ~/.john
CPU tests: SSE4.2
$JOHN is /usr/local/Cellar/john-jumbo/1.9.0/share/john/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
clang version: 11.0.0 (clang-1100.0.33.8) (gcc 4.2.1 compatibility)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 01010104f	(loaded: 0101010ff)
OpenSSL 1.1.1d  10 Sep 2019	(loaded: OpenSSL 1.1.1o  3 May 2022)
GMP library version: 6.1.2	(loaded: 6.2.1)
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by magnumripper** [comment] 2022-06-02 10:14
First, they are SAPH hashes, not SAPG. Just leaving out the `--format` option will usually auto-select correct format.

But also, the input file is including some quotes `"` that need to be edited out. Perhaps a bug in `sap2john`? Drop them, and the hashes will load.

**Comment by magnumripper** [comment] 2022-06-02 10:19
I can't spot any problem in `sap2john.pl` - I guess the original input file somehow had the erroneous quotes. Maybe `sap2john.pl` should trim them away.

**Comment by hsingll** [comment] 2022-06-02 13:03
> First, they are SAPH hashes, not SAPG. Just leaving out the `--format` option will usually auto-select correct format.
> 
> But also, the input file is including some quotes `"` that need to be edited out. Perhaps a bug in `sap2john`? Drop them, and the hashes will load.

Thank you!.
it didn't show  "No password hashes loaded" without quotes `"`.
Could it be caused by my wrong steps?
1.I download usr02 as xlsx document. [Original file.xlsx](https://github.com/openwall/john/files/8823921/Original.file.xlsx)
2.I save original file as Tab delimited Text (.txt) .This is because `sap2john.pl` can't read the xlsx file when I test.[output.txt](https://github.com/openwall/john/files/8823940/800.txt)
there is `"` in output.txt.
3.run command `./sap2john.pl output.txt > password.txt`.there is `"` in password.txt too.

but no password cracked when correct password in wordlist.
demo hash files:[demo.txt](https://github.com/openwall/john/files/8824222/demo.txt)
wordlist with true password:[wordlist.txt](https://github.com/openwall/john/files/8824237/wordlist.txt)
command with log:
```
john demo.txt --wordlist=wordlist.txt
Using default input encoding: UTF-8
Loaded 1 password hash (saph, SAP CODVN H (PWDSALTEDHASH) [SHA-1/SHA-2 128/128 SSE4.1 4x2])
Cost 1 (hash type [1:SHA1 2:SHA256 3:SHA384 4:SHA512]) is 4 for all loaded hashes
Cost 2 (iteration count) is 15000 for all loaded hashes
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:00 DONE (2022-06-02 21:25) 0g/s 180.0p/s 180.0c/s 180.0C/s Init123456..890123
Session completed
```
log file:[john.log](https://github.com/openwall/john/files/8824262/john.log)

**Comment by solardiz** [comment] 2022-06-04 19:29
@hsingll Why did you close this issue? Re-opening at least until we know the reason. Thanks.

**Comment by frank-dittrich** [comment] 2022-06-05 00:36
You are not supposed to load the list as xlsx dorcument. Just download it as plain text.

**Comment by hsingll** [comment] 2022-06-05 11:01
> @hsingll Why did you close this issue? Re-opening at least until we know the reason. Thanks.

Because I understand it's not a software problem, it's something I'm doing wrong.
I shouldn't download xlsx and save as plain text, I should download as plain text.

As for the second question, I think it may be because my mbp computing power is not enough.
With SHA-512 salt and 15000 iterations, it didn't crack even if the correct password is on the first line of wordlist.
But with SHA-1 salt and 1024 iterations, it works good.

**Comment by solardiz** [comment] 2022-06-05 15:38
> I think it may be because my mbp computing power is not enough.

No, that can't be it. On a slower computer, this would merely take longer, not terminate without finding the password _if_ you do in fact have the correct password in the wordlist.

**Comment by solardiz** [comment] 2022-06-05 16:34
So the issue is we only handle salts of up to 16 bytes, and this one hash has a 32-byte salt. A sub-issue is we fail to reject the unsupported salts. I have a patch half-ready.

**Closed as completed** 2022-06-05 19:31 UTC
Labels: bug
