### ISSUE TITLE
Inconsistent OpenCL error handling in format-specific vs. common code

### ISSUE THREAD

**Issue by kevingy** [openwall/john#4044] opened 2019-07-05 12:31 UTC
### Steps to reproduce ###
Using john-1.9.0-jumbo-1-win64 from Openwall, run:
`john --test --format=RAR5-opencl`
from the run directory

### Results: ###
This error is observed:
```
Device 2: Intel(R) HD Graphics 4000
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... 0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1828 - clWaitForEvents
```

### Notes: ###
I don't know anything about the code or the interface with OpenCL, but these notes might (or might not) help tracking down the problem.
- _john --test --format=RAR5_ works on the same machine without error
- _john --test --format=rar-opencl_ works on the same machine without error
- The RAR5-opencl benchmark test works on another machine with an Nvidia GPU

### System configuration ###
See attached.
[build-info.txt](https://github.com/magnumripper/JohnTheRipper/files/3362653/build-info.txt)
[opencl-devices.txt](https://github.com/magnumripper/JohnTheRipper/files/3362656/opencl-devices.txt)

**Comment by kevingy** [comment] 2019-07-07 16:46
BTW, I'm getting the same error for 7z-opencl:

`Will run 4 OpenMP threads
Device 2: Intel(R) HD Graphics 4000
Benchmarking: 7z-opencl, 7-Zip (512K iterations) [SHA256 AES OpenCL]... (4xOMP) 0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1828 - clWaitForEvents`

**Comment by magnumripper** [comment] 2019-07-09 17:01
My first, second and third guesses would be this is a driver/runtime problem (ie. with your Intel OpenCL driver). Just for curiosity, would the version of said driver satisfy Hashcat's requirements?

**Comment by kevingy** [comment] 2019-07-09 17:57
That's a good question. I attempted to run to benchmark RAR5 using this commandline:
> hashcat-5.1.0>hashcat64 --benchmark -m 13000

That resulted in the following
```
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

* Device #2: Intel's OpenCL runtime (GPU only) is currently broken.
             We are waiting for updated OpenCL drivers from Intel.
             You can use --force to override, but do not report related errors.
No devices found/left.

Started: Tue Jul 09 12:46:28 2019
Stopped: Tue Jul 09 12:46:28 2019
```

When I added the --force parameter, I got this:
```
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz, skipped.
* Device #2: Intel(R) HD Graphics 4000, 350/1400 MB allocatable, 16MCU

Benchmark relevant options:
===========================
* --force
* --optimized-kernel-enable

Hashmode: 13000 - RAR5 (Iterations: 32767)

Speed.#2.........:      294 H/s (52.65ms) @ Accel:16 Loops:4 Thr:512 Vec:1

Started: Tue Jul 09 12:47:13 2019
Stopped: Tue Jul 09 12:47:50 2019
```

I don't know for certain if that means that HashCat didn't use OpenCL or if it used OpenCL without error. 294 H/s is approximately with the non-OpenCL John result of 273 c/s. For RAR3 on this same hardware, the OpenCL performance is about double the non-OpenCL. If that holds for RAR5, I would expect approximately 550 H/s using OpenCL. My gut is that it didn't use OpenCL when "--force"d.

Does that answer your question? Does that mean that your first, second, and third guesses are correct - it's an Intel problem, not a JtR problem?

**Comment by magnumripper** [comment] 2019-07-09 18:01
Yeah, until you prove me wrong, I will assume so 😉 

Would it be possible for you to try a hashcat-approved driver version and report back?

**Comment by solardiz** [comment] 2019-07-09 18:16
FWIW, from the information posted here, it looks like hashcat at least passed its self-test on that GPU for that mode correctly, and was able to benchmark it.

> My gut is that it didn't use OpenCL when "--force"d.

That's impossible. hashcat 5.1.0 is OpenCL-only.

**Comment by solardiz** [comment] 2019-07-09 18:18
magnum, we can test and try to fix our formats to work on HD Graphics 4000 on "well", with whatever Linux driver version we have there. Right now, some formats work and some fail.

Edit: by "fix" I mean "workaround whatever driver issues we run into". This might or might not be worth our time.

**Comment by magnumripper** [comment] 2019-07-09 18:22
> FWIW, from the information posted here, it looks like hashcat at least passed its self-test on that GPU for that mode correctly, and was able to benchmark it.
> 
> > My gut is that it didn't use OpenCL when "--force"d.
> 
> That's impossible. hashcat 5.1.0 is OpenCL-only.

Yes that's correct, but nonetheless it's marked as a "bad version".

> magnum, we can test and try to fix our formats to work on HD Graphics 4000 on "well", with whatever Linux driver version we have there. Right now, some formats work and some fail.

Only unless that version is marked as bad by hashcat. If it is, I simply can't waste any time on it. Even if it's NOT marked as bad, I have a crazy list of things I need to do with much higher priority.

**Comment by magnumripper** [comment] 2019-07-09 18:26
I see now you wrote "we" and not "you" (as in me) 🤣 but anyway I wouldn't advise anyone to look into a driver that Atom has banned. It's bad enough anyway, for sure.

**Comment by kevingy** [comment] 2019-07-09 18:26
> magnum, we can test and try to fix our formats to work on HD Graphics 4000 on "well", with whatever Linux driver version we have there. Right now, some formats work and some fail.

So far, all of my tests have been using the Windows driver, not the Linux driver. That said, I have an identical laptop with Debian 10 installed where I can test Linux, if will help.

That said, if magnum says that this is such a low priority that it's not going to get cycles regardless, I don't know that it's worth investing the time to continue.

**Comment by kevingy** [comment] 2019-07-09 18:27
> Would it be possible for you to try a hashcat-approved driver version and report back?

It is possible, if I can find the approved driver. I've been looking for the download on the Intel site since your request. I haven't been able to find it.

**Comment by magnumripper** [comment] 2019-07-09 18:28
I think it's pointed to by hashcat docs, or in the forums or something. Can't remember right now.

**Comment by kevingy** [comment] 2019-07-09 18:30
I see that the site says
> Intel GPUs on Windows require "OpenCL Driver for Intel Iris and Intel HD Graphics"

Google can't find "OpenCL Driver for Intel Iris and Intel HD Graphics" outside of anything other than Hashcat docs. I'll keep digging.

**Comment by solardiz** [comment] 2019-07-09 18:30
I think atom bans drivers very easily for issues that might be hashcat-specific (not hashcat bugs, but also not necessarily affecting JtR). That said, Intel's OpenCL is quite poor. L0phtCrack 7 blacklisted Intel GPUs altogether.

Anyway, rar5-opencl works on HD Graphics 4000 in i7-4770K on "well":

```
[solar@well run]$ ./john -test -form=rar5-opencl -dev=6 
Device 6: Intel(R) HD Graphics
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... Build log: fcl build 1 succeeded.
fcl build 2 succeeded.
bcl build succeeded.

DONE
Speed for cost 1 (iteration count) of 32768
Raw:    406 c/s real, 256000 c/s virtual
```

The above is about 3 times slower than the CPU:

```
[solar@well run]$ ./john -test -form=rar5 
Will run 8 OpenMP threads
Benchmarking: RAR5 [PBKDF2-SHA256 256/256 AVX2 8x]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 32768
Raw:    1335 c/s real, 167 c/s virtual
```

**Comment by magnumripper** [comment] 2019-07-09 18:33
My previous macbook had a HD Graphics 4000 and IIRC it was usually slower than CPU although the macOS drivers were actually fairly usable. That piece of chip (no pun intended ;-) simply doesn't have much value for compute.

**Comment by solardiz** [comment] 2019-07-09 18:36
I'll close this as an "external issue". There's no indication we have a bug, the format works on a similar Intel GPU, as above, presumably with another driver, and our team lacks resources to experiment with different Intel driver versions and work around issues.

@kevingy Please feel free to add more detail to this issue anyway, if/once you have any. Thanks!

**Comment by kevingy** [comment] 2019-07-09 18:38
@solardiz @magnumripper Thank you both for your help. I'll keep looking for the driver. If I can find it, I'll report back for posterity.

As has been said, if OpenCL is of no benefit anyway, there is no need to spend valuable time on this.

**Comment by solardiz** [comment] 2019-07-09 18:40
OpenCL might not be faster, but you should be able to run both the CPU and the OpenCL format at once, in separate `john` invocations, for higher cumulative speed.

**Comment by ghost** [comment] 2019-07-10 12:40
It is easy to find a problem when using Intel drivers. Below, it works on Intel GPU but fails on Intel CPU (and works when using the "same" CPU with the AMD driver).
```
$ $JtR --test --format=sha256crypt-opencl -dev=7
Device 7: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
Benchmarking: sha256crypt-opencl, crypt(3) $5$ (rounds=5000) [SHA256 OpenCL]... Build log: Compilation started
Compilation done
Linking started
Linking done
Device build started
Device build done
Kernel <kernel_crypt> was successfully vectorized (8)
Done.
0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1794 - clWaitForEvents
```

```
$ $JtR --test --format=sha256crypt-opencl -dev=6
Device 6: Intel(R) HD Graphics
Benchmarking: sha256crypt-opencl, crypt(3) $5$ (rounds=5000) [SHA256 OpenCL]... Build log: fcl build 1 succeeded.
fcl build 2 succeeded.
bcl build succeeded.

DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1066 c/s real, 42666 c/s virtual
```

```
$ $JtR --test --format=sha256crypt-opencl -dev=5
Device 5: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
Benchmarking: sha256crypt-opencl, crypt(3) $5$ (rounds=5000) [SHA256 OpenCL]... DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1448 c/s real, 363 c/s virtual
```
****

To cause an "invalid event", we have to be overwriting the event memory address.  But only on Intel? **Very unlikely**. It smells like an Intel bug.

**Comment by ghost** [comment] 2020-03-13 13:29
I tried the same on Linux with Celeron N3050, beignet 1.3.2, LLVM 7. Here are some interesting results:

1. JtR can create `~/.john` directory but afterwards it cannot create `~/.john/kernels` directory, so it will say "Error creating binary cache file".
2. However, `john --format=rar-opencl --test` *seem* to work and it is faster than `john --format=rar --test`:
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) Error creating binary cache file: No such file or directory
DONE
Raw:    278 c/s real, 15360 c/s virtual
```
```
Will run 2 OpenMP threads
Benchmarking: rar, RAR3 (length 5) [SHA1 128/128 SSE2 4x AES]... (2xOMP) DONE
Raw:    41.1 c/s real, 24.4 c/s virtual
```
3. `john --format=rar5-opencl --test` does not work even when the "kernels" directory is not present:
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... Error creating binary cache file: No such file or directory
0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1827 - clWaitForEvents
```
4. When there is "kernels" directory (after manually creating it), both formats fail with the same error:
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) 0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1827 - clWaitForEvents
```
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... 0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1827 - clWaitForEvents
```
---
I found https://github.com/CNugteren/CLBlast/issues/66#issuecomment-248993477 which leads to https://github.com/CNugteren/CLBlast/commit/d595a8ed7e416dd40c2971ef5e3ec7f36b7db362. Can we try similar workaround for JtR?

**Comment by solardiz** [comment] 2020-03-13 14:13
> CL_INVALID_EVENT (-58) error in opencl_common.c:1827 - clWaitForEvents

This line number corresponds to 1.9.0-jumbo-1. I doubt it'd make a difference for this issue, but can you also try our latest code from this repo?

> I found [CNugteren/CLBlast#66 (comment)](https://github.com/CNugteren/CLBlast/issues/66#issuecomment-248993477) which leads to [CNugteren/CLBlast@d595a8e](https://github.com/CNugteren/CLBlast/commit/d595a8ed7e416dd40c2971ef5e3ec7f36b7db362). Can we try similar workaround for JtR?

As I understand, their change isn't a workaround, but is a bug fix adding previously-missed checks for the status of the previous OpenCL API call. We already check the status of every such call. Specifically, in 1.9.0-jumbo-1 we have:

```c
        // Activate events. Then clear them later.
        for (i = 0; i < MAX_EVENTS; i++)
                multi_profilingEvent[i] = &benchEvent[i];

        // Timing run
        count = global_work_size * ocl_v_width;
        result = self->methods.crypt_all(&count, autotune_salts);
        if (result > 0)
                self->methods.cmp_all(binary, result);

        HANDLE_CLERROR(clWaitForEvents(1, &benchEvent[main_opencl_event]),
                       "clWaitForEvents");
```

where e.g. `opencl_rar5_fmt_plug.c` has this:

```c
static int crypt_all(int *pcount, struct db_salt *salt)
{
        int i;
        const int count = *pcount;
        int loops = host_salt->rounds / HASH_LOOPS;
        size_t *lws = local_work_size ? &local_work_size : NULL;

        global_work_size = GET_NEXT_MULTIPLE(count, local_work_size);

        loops += host_salt->rounds % HASH_LOOPS > 0;

        // Copy data to gpu
        BENCH_CLERROR(clEnqueueWriteBuffer(queue[gpu_id], mem_in,
                CL_FALSE, 0, global_work_size * sizeof(pass_t), host_pass, 0,
                NULL, multi_profilingEvent[0]), "Copy data to gpu");

        // Run kernel
        BENCH_CLERROR(clEnqueueNDRangeKernel(queue[gpu_id], crypt_kernel,
                1, NULL, &global_work_size, lws, 0, NULL,
                multi_profilingEvent[1]), "Run kernel");

        for (i = 0; i < (ocl_autotune_running ? 1 : loops); i++) {
                BENCH_CLERROR(clEnqueueNDRangeKernel(queue[gpu_id], split_kernel,
                        1, NULL, &global_work_size, lws, 0, NULL,
                        multi_profilingEvent[2]), "Run split kernel");
                BENCH_CLERROR(clFinish(queue[gpu_id]), "clFinish");
                opencl_process_event();
        }
        BENCH_CLERROR(clEnqueueNDRangeKernel(queue[gpu_id], final_kernel,
                1, NULL, &global_work_size, lws, 0, NULL,
                multi_profilingEvent[3]), "Run final kernel");

        // Read the result back
        BENCH_CLERROR(clEnqueueReadBuffer(queue[gpu_id], mem_out,
                CL_TRUE, 0, global_work_size * sizeof(crack_t), host_crack, 0,
                NULL, multi_profilingEvent[4]), "Copy result back");

        return count;
}
```

As you can see, all calls are wrapped in `BENCH_CLERROR`, which is:

```c
/* Use this macro for OpenCL Error handling in crypt_all() */
#define BENCH_CLERROR(cl_error, message)          \
        do { cl_int __err = (cl_error); \
                if (__err != CL_SUCCESS) { \
                        if (!ocl_autotune_running || options.verbosity >= VERB_MAX) \
                                fprintf(stderr, "%u: OpenCL %s error in %s:%d - %s\n", \
                                        NODE, get_error_name(__err), __FILE__, __LINE__, message); \
                        else if (options.verbosity > VERB_LEGACY) \
                                fprintf(stderr, " %u: %s\n", NODE, get_error_name(__err)); \
                        if (!(ocl_autotune_running || bench_or_test_running)) \
                                error(); \
                        else \
                                return -1; \
                } \
        } while (0)
```

Hmm, the logic here is a bit complicated. @claudioandre-br @magnumripper This looks like it's possible for an error to be silently ignored in some cases during auto-tune and benchmark? Perhaps this is wrong, and we should at least propagate the error so that we don't attempt further dependent calls? Maybe that's our bug here? Re-opening for this discussion.

**Comment by solardiz** [comment] 2020-03-13 14:22
Maybe the combination of sometimes ignoring OpenCL errors in per-format code and never ignoring them in dependent calls in the shared code is wrong.

@86423355844265459587182778 Can you try replacing `HANDLE_CLERROR` with `BENCH_CLERROR` or `SOFT_CLERROR` (and let us know which you chose) on that line 1827 in `opencl_common.c`?

**Comment by ghost** [comment] 2020-03-14 02:39
Replacing `HANDLE_CLERROR` with `BENCH_CLERROR` (Version: 1.9.0-jumbo-1) partially solves the problem - at least benchmarks for both formats appear to run successfully. However I still have to manually create the "kernels" directory to silence the "Error creating binary cache file" message.

`john --format=rar-opencl --test` (No "kernels" directory):
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) Error creating binary cache file: No such file or directory
DONE
Raw:    281 c/s real, 19200 c/s virtual
```
`john --format=rar5-opencl --test` (No "kernels" directory):
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... Error creating binary cache file: No such file or directory
DONE
Speed for cost 1 (iteration count) of 32768
Raw:    194 c/s real, 25600 c/s virtual
```
`john --format=rar-opencl --test` (With "kernels" directory):
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) DONE
Raw:    281 c/s real, 15360 c/s virtual
```
`john --format=rar5-opencl --test` (With "kernels" directory):
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... DONE
Speed for cost 1 (iteration count) of 32768
Raw:    194 c/s real, 15360 c/s virtual
```

**Comment by ghost** [comment] 2020-03-14 03:38
This time `HANDLE_CLERROR` is replaced with `SOFT_CLERROR` (Version: 1.9.0-jumbo-1). `rar-opencl` works but `rar5-opencl` fails.

`john --format=rar-opencl --test` (No "kernels" directory):
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) Error creating binary cache file: No such file or directory
DONE
Raw:    280 c/s real, 15360 c/s virtual
```
`john --format=rar5-opencl --test` (No "kernels" directory):
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... Error creating binary cache file: No such file or directory
0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1827 - clWaitForEvents
0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1830 - clGetEventProfilingInfo start
```
`john --format=rar-opencl --test` (With "kernels" directory):
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) DONE
Raw:    288 c/s real, 30720 c/s virtual
```
`john --format=rar5-opencl --test` (With "kernels" directory):
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... 0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1827 - clWaitForEvents
0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1830 - clGetEventProfilingInfo start
```

**Comment by solardiz** [comment] 2020-03-14 11:22
Thanks @86423355844265459587182778.

So it looks like we have two issues here - one is inconsistent handling of errors between format-specific code and common code, and the other is with the "kernels" directory.

Can you please also repeat these tests on our current code from this repo (not 1.9.0-jumbo-1)? Please first test it as-is, then with `BENCH_CLERROR` on the line in `opencl_common.c` for which the same error would likely be reported. (I wonder if the issue with the "kernels" directory is possibly already gone or changed. We made relevant changes since 1.9.0-jumbo-1.)

As to `SOFT_CLERROR` resulting in errors from `clGetEventProfilingInfo`, my guess is this could also occur with `BENCH_CLERROR` on the `clWaitForEvents` call, but did not due to pure luck. We probably have the events in an inconsistent state there, so these calls can appear to succeed or fail "randomly". Unfortunately, for `clGetEventProfilingInfo` we probably shouldn't silently ignore errors as we'd end up tuning using "random" fake timings.

@claudioandre-br @magnumripper Can you suggest a proper fix here? Maybe if `clWaitForEvents` returns an error when in benchmark or auto-tune, don't complain and don't abort, but skip the dependent calls to `clGetEventProfilingInfo` and set the timings to some fixed values that would make sense in this case (perhaps causing this benchmark run to be ignored for auto-tuning purposes)?

BTW, there are 2 more instances (for a total of 3) of this code pattern in `opencl_common.c`. While the issue visibly occurs for only one of them in the reports here, we should probably fix all of them.

**Comment by ghost** [comment] 2020-03-15 03:16
I noticed that the current code looks for `opencl` directory instead, and the directory bug is still here (i.e. requires manually creating it).

At f47aa64, as-is (without `BENCH_CLERROR` patch):
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) Error creating binary cache file: No such file or directory
LWS=16 GWS=384 (24 blocks) DONE
Raw:    269 c/s real, 12800 c/s virtual
```
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... Error creating binary cache file: No such file or directory
0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1810 - clWaitForEvents
```
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) LWS=8 GWS=384 (48 blocks) DONE
Raw:    278 c/s real, 12800 c/s virtual
```
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... 0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1810 - clWaitForEvents
```

**Comment by ghost** [comment] 2020-03-15 05:07
f47aa64 + `BENCH_CLERROR` patch:
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) Error creating binary cache file: No such file or directory
LWS=128 GWS=384 (3 blocks) DONE
Raw:    280 c/s real, 19200 c/s virtual
```
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... Error creating binary cache file: No such file or directory
LWS=8 GWS=384 (48 blocks) DONE
Speed for cost 1 (iteration count) of 32768
Raw:    194 c/s real, 15360 c/s virtual
```
```
Will run 2 OpenMP threads
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (2xOMP) LWS=8 GWS=384 (48 blocks) DONE
Raw:    282 c/s real, 15360 c/s virtual
```
```
Device 1@PC: Intel(R) HD Graphics Cherryview
Benchmarking: RAR5-opencl [PBKDF2-SHA256 OpenCL]... LWS=8 GWS=384 (48 blocks) DONE
Speed for cost 1 (iteration count) of 32768
Raw:    194 c/s real, 12800 c/s virtual
```

**Comment by solardiz** [comment] 2020-03-15 16:09
Thanks @86423355844265459587182778.

Now I'd really like to hear from @claudioandre-br and @magnumripper on both issues. Please?

**Comment by solardiz** [comment] 2020-05-27 22:45
FWIW, since I realized what's going on here, I am patching `HANDLE_CLERROR` with `BENCH_CLERROR` on those uses around line 1800 in `opencl_common.c` whenever I see a certain platform fail to run a certain format for me with similar errors, and this helps. For example, `nt-opencl` wouldn't run on Xeon Phi for me without this hack; with the hack, it does.

We ought to address this issue properly before next release. It's a high priority one.

**Comment by magnumripper** [comment] 2020-09-23 16:16
> This looks like it's possible for an error to be silently ignored in some cases during auto-tune and benchmark? Perhaps this is wrong, and we should at least propagate the error so that we don't attempt further dependent calls? Maybe that's our bug here? Re-opening for this discussion.

Well that is exactly what `BENCH_CLERROR` was introduced for. We have these alternatives:
`SOFT_CLERROR` will just print the error
`HANDLE_CLERROR` will print the error and abort
`BENCH_CLERROR` is designed for `crypt_all()` and autotune: If autotune is running (and only then), it will silently `return -1;` _which is (supposedly) recognized and acted on by the autotune code_. Bumped verbosity may make the error message show as well. But if autotune is NOT running, it will behave mostly like `HANDLE_CLERROR` and abort.

Perhaps some autotune code does not catch the returned `-1`?

Oh wait, we also have `bench_or_test_running` there. That's possibly a bug - I do not think we handle that "error return" from bench or test.

**Comment by magnumripper** [comment] 2020-09-23 16:20
It was introduced long ago, 462f2b4b6

**Comment by magnumripper** [comment] 2020-09-23 16:24
Anyway if we replace some `HANDLE_CLERROR` in opencl_common.c as you mentioned, we should probably just use `SOFT_CLERROR`, or is the `return -1` appropriate?

Edit: I see `opencl_find_best_lws()` is void - it shouldn't even compile using `BENCH_CLERROR` unless the `return -1` is optimized away...

**Comment by solardiz** [comment] 2020-09-24 07:25
As I wrote earlier:

"We probably have the events in an inconsistent state there [...]. Unfortunately, for `clGetEventProfilingInfo` we probably shouldn't silently ignore errors as we'd end up tuning using "random" fake timings.

[...] Maybe if `clWaitForEvents` returns an error when in benchmark or auto-tune, don't complain and don't abort, but skip the dependent calls to `clGetEventProfilingInfo` and set the timings to some fixed values that would make sense in this case (perhaps causing this benchmark run to be ignored for auto-tuning purposes)?"

So I think we should consider the different possible failure modes and add code to handle them gracefully. Simply using a different existing macro without making other changes hides the problem in some cases, but isn't a proper fix (will likely auto-tune wrong in those cases).

**Comment by solardiz** [comment] 2020-09-25 18:03
Also, why do we tend to use `HANDLE_CLERROR` in `set_salt()` yet `BENCH_CLERROR` in `crypt_all()`?

**Comment by ghost** [comment] 2020-09-25 18:15
Ok, we should change that. But, `set_salt()` is not important for auto tuning (when errors will occur). 

In fact, an error in `set_salt()` while tuning is bad omen

**Comment by magnumripper** [comment] 2020-09-25 18:19
> Also, why do we tend to use `HANDLE_CLERROR` in `set_salt()` yet `BENCH_CLERROR` in `crypt_all()`?

Because we can't `return -1;` from `void set_salt()`. We could use `SOFT_CLERROR` or introduce a new one that is more like `BENCH_CLERROR` except never tries to return a value.

**Comment by solardiz** [comment] 2020-09-25 18:45
OK, I'm actually fine with potential errors in `set_salt()` being fatal. We're not seeing spurious ones.

**Comment by magnumripper** [comment] 2021-04-19 14:56
> [...] Maybe if `clWaitForEvents` returns an error when in benchmark or auto-tune, don't complain and don't abort, but skip the dependent calls to `clGetEventProfilingInfo` and set the timings to some fixed values that would make sense in this case (perhaps causing this benchmark run to be ignored for auto-tuning purposes)?"

I tried to do exactly this in #4675. Like I said there, I'm not sure how to test it as I currently can't reproduce profiling errors.

**Closed as completed** 2021-04-19 19:39 UTC
Labels: bug
