### ISSUE TITLE
Build error under termux - .a files not found

### ISSUE THREAD

**Issue by bubbelbadHD** [openwall/john#5109] opened 2022-04-10 08:54 UTC
clang-13: error: no such file or directory: 'aes/aes.a'
clang-13: error: no such file or directory: 'secp256k1/secp256k1.a'
clang-13: error: no such file or directory: 'ed25519-donna/ed25519-donna.a'
clang-13: error: no such file or directory: 'poly1305-donna/poly1305-donna.a'
make[1]: *** [Makefile:1472: ../run/john] Error 1

What does this mean. I have even run the configure file it tells everything is don't when I run make -s clean && make -sj4 it show that error.

Pls give me a fix :).
![Screenshot_20220410-142429](https://user-images.githubusercontent.com/77578305/162610581-47460500-3e96-48a7-83e7-42902ac8ce89.png)

**Comment by solardiz** [comment] 2022-04-11 17:27
@bubbelbadHD Please provide more information - what operating system/version are you on, and the _full_ build log (please capture it to a file e.g. with `&> log.txt`, then attach to here). Thanks.

**Comment by solardiz** [comment] 2022-04-17 19:19
The screenshot shows this is in `termux`, so apparently on Android. The errors suggest the `.a` files were not created. A guess would have been that the system could lack `ar`, however I've just tried temporarily removing `ar` from a normal Linux system (not Android/termux) and then the build fails much earlier on trying to create those `.a` files - not on trying to use them. Also, `ar` normally comes from `binutils`, which also provides the assembler - so without that package installed the build should have failed before it even reached the point of trying to create the `.a` files. Thus, the problem is more likely different.

Anyhow, we don't need to track this as an issue (it's most likely not an issue with our project) and there's no communication from OP, so I'm closing the issue. However, more comments can be added to it anyway, if needed.

**Closed as completed by solardiz** 2022-04-17 19:19 UTC
Labels: question
